### ISSUE TITLE
request user profile information from user when they first start the app

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#1000]
This will only happen once. The information in the profile should be used to automatically populate the first translator when they start a new target translation (but allow them to edit it).

When the backup service is running only target translations that have a translator should be backed up. We may want to allow the backup service to automatically add a missing translator using the profile so that backups can continue without interruption.

**Comment by neutrinog** [comment]
We need to  collect the following from the user when the start the app.

* name/alias
* email
* phone (optional)

Eventually we may support multiple user profiles in the app so let's go ahead and prepare for that (at least as far as the ui is concerned).

I'd like to insert a new activity in the start up process. Look at `SplashScreenActvitiy.openMainActivity()`, this is where the home activity is started. Instead of starting the home activity let's start the new activity that will allow users to choose which profile to load or create a new one.

In this new activity we will check if a user profile has already been set up. If a profile exists then we will proceed to start the home activity (what is currently happening in the `openMainActivity` method). From the user's point of view they won't actually see this new activity if a profile exists because the home activity will have started before the new activity even has time to draw.

If no profile exists then immediately open a dialog that will accept the required info described above. Once they fill out the info and click ok the home activity should be started (if they cancel the app should close).

This process will change a bit once we begin supporting multiple profiles. For example:

* list of available profiles
* button to add a new profile
* can cancel creating a profile without closing the app
* etc.

**Comment by neutrinog** [comment]
we'll need to keep track of the profile information some how. I propose creating a new `Profile` class to hold the data and then add a new method `AppContext.getProfile()` to retrieve the open profile. We could have similar methods `openProfile(Profile profile)` and `getProfiles()` that would open a particular profile or list all available profiles respectively.

**Comment by jshuma** [comment]
I've started on [a branch](https://github.com/jshuma/ts-android/commits/issue1000) to begin this. Here's a brief overview of what I've got so far:
* Adds a new `Person` class as a base class for `NativeSpeaker`. The profile is stored in `Person` directly, while `NativeSpeaker` doesn't add any additional functionality to it.
* Adds `getProfiles()` and `setProfiles()` to `AppContext`, relying on simple Java serialization of `List<Person>`. On failure it acts as if nothing was stored. This is brittle (particularly in the case of making changes to the format of `Person`) but simple enough for now.
* Creates `ProfileActivity` and `ProfileActivityFragment` for display at app start.
* The splash screen kicks off `ProfileActivity`. If it finds a profile, it proceeds directly to `HomeActivity` without stopping. If it doesn't find a profile, it prompts the user to enter some data, and stores the entry (or exits, without proceeding to `HomeActivity`, if the user cancels).

Potential future work:
* Unify `ProfileActivityFragment` with `ProfileFragment` and/or `fragment_publish_profile.xml` from the publishing flow. Right now the profile is too coupled with the publishing flow to be usable as a standalone activity at the start of the app; parts that are relevant to both should be factored out. As part of this, a more user-friendly interface could be added.
* Switch to a more future-proof serialization strategy.
* Multiple user support. Allow entering multiple profiles. If there are multiple profiles, `ProfileActivity` could make the user pick one before proceeding, or it could just store a default.
* Use the stored information to pre-populate translator information. (Right now, nothing actually uses the entered profile information for anything.)
* Put something in the settings screen allowing modifying or deleting the defaults, as it might be slightly annoying for the user's initial entry to be set in stone forever without any way (at least in the app) to change it.
* Consider unifying `Person` and `NativeSpeaker`, in case the distinction between the two is not useful or meaningful.

I think I've got some more work to do on this before it's ready to checkpoint as its own pull request. In the meantime, I'm open to feedback on what's there so far and on the plans for further development.

**Comment by neutrinog** [comment]
I'm not sure we want NativeSpeaker to subclass Person because eventually we may want to store additional information in Person like login info, additional profile details (to connect to account backends on the server). Manually copying the needed info from a Person into a new NativeSpeaker should be fine.

Right now we're planning to move towards using https://gogs.io at the git backend. I'm not completely certain we will need to store any extra info on Person, but for now I think keeping things separate will avoid future issues with tightly coupled items.

**Comment by neutrinog** [comment]
also activities should extend `BaseActivity`

**Comment by jshuma** [comment]
OK, I did some more work on this and added a [pull request](https://github.com/unfoldingWord-dev/ts-android/pull/1226). Since `NativeSpeaker` and `Person` don't need to share a base class, I renamed `Person` to `Profile`. At this point, `NativeSpeaker` and `Profile` are two distinct (but quite similar) implementations, and `NativeSpeaker` can be created from a `Profile`. Everything in `TargetTranslation` uses `NativeSpeaker`, and the formats for `NativeSpeaker` and `Profile` can change without them breaking each other. This information is persisted in the target translation at create time, meaning that existing translations will intentionally not be populated with these details.

I tested this by populating fresh account details, then verifying that these account details can be seen in the translation info screen, as well as on the publishing screen (for newly-created translations only).

**Comment by neutrinog** [comment]
This looks good. Except if I click on submit without entering any information it will allow me to continue into the app. We need to validate the input to ensure they've entered at least a name and email.

I went ahead and merged the pull request because there were some conflicts with other pull requests. So please open a new one with this fix.
