### ISSUE TITLE
Support Parsing Information

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-android#1001]
We need to support providing parsing information for words in the source text.  Primarily this will be for Greek, Hebrew and Aramaic, but could extend to other languages too.

@sampeckham We will likely need a UI drawn up for this.

@neutrinog We'll need to work out how to represent this information in the catalog as well.

**Comment by neutrinog** [comment]
I'm not sure what you mean by parsing information. Could you elabroate @jag3773

**Comment by jag3773** [comment]
I knew you would ask @neutrinog !  Part of speech, person, number, gender, verbal conjugation, etc.  On desktop apps and websites these are often implemented as pop up on hover.  Possibly we could implement this as a pop up on tap?

**Comment by neutrinog** [comment]
@jag3773  In order to accurately support this we'll need to provide this information inline in the source translation. How do you plan to implement that? We had issues doing that with  key terms before.

**Comment by neutrinog** [comment]
This is primarily for the Greek and Hebrew.

**Comment by klappy** [comment]
Moved to concern in tC
