### ISSUE TITLE
Project Modal Dialoge update

### ISSUE THREAD

**Issue by sampeckham** [unfoldingWord-dev/ts-android#1010]
The Project Modal dialog from the "i" on the Home screen needs updating with new options and improved design.

Functions:
- Delete (should show confirm dialog)
- Print (any print setup dialog)
- Share (send the whole project to another tablet)

@jag3773 
Do we want to add a Publish option too?
We currently do not indicate the published status of a project, only the progress, should we indicate it?

![screen shot 2015-11-16 at 14 17 49](https://cloud.githubusercontent.com/assets/323212/11184001/e186d762-8c6c-11e5-8690-84f7b2287f25.png)

**Comment by jag3773** [comment]
Yes and Yes @sampeckham

**Comment by neutrinog** [comment]
@jag3773 @sampeckham for all dialogs do we want just use a tap outside of the dialog and the hardware back button to close the dialogs? Right now there is a little inconsistency with some dialogs using the afore mentioned methods and some using a dismiss button on the dialog.

**Comment by sampeckham** [comment]
All dialogues should be quotable by tapping back and tapping outside. 

Having Dismiss button depends on context. If the dialogue is a message or prompting an action that may want to be avoided (ie. Are you sure you Amat to delete?) then it should have a cancel or dismiss button. If it's purely user triggered and informational like Project dialogue then it needs no button. This is all per Google guidelines.

**Comment by neutrinog** [comment]
I've added a new issue https://github.com/unfoldingWord-dev/ts-android/issues/1013 for adding the published status.
