### ISSUE TITLE
use git tags to indicate when a project has been successfully published

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#1011]
this will replace the `READY` file that we are currently relying on.

> EDIT: for now we will maintain support for the `READY` file until the server is updated to read the tags.

**Comment by PhotoNomad0** [comment]
@neutrinog - Here is a swag at the format.  Tag name would be "Published -"+time.  And then message would contain string returned by getCommitHash().

**Comment by neutrinog** [comment]
we don't need to store the commit hash because that's already associated with the tag. I don't know if our current git library supports this but you don't need to add a message when creating a tag. Also let's make everything lowercase and no spaces to make parsing easier on the server side. e.g.

```
"published-" + System.currentTimeMillis()
```
