### ISSUE TITLE
Swipe behaviour to change Source/Translation card

### ISSUE THREAD

**Issue by sampeckham** [unfoldingWord-dev/ts-android#1016]
Currently, the app allows swiping Right to Left (RTL) to move from Source to Translation and allows swiping Left to Right (LTR) to move from Translation to Source.

I wonder if this makes sense. I found myself swiping wondering why I had to go in a certain direction, when the card appeared in the same right hand spot each time.

Previously, we played with the card poking out on the right for the Translation and poking out the left side for Source. We moved away from this switching sides idea, so I wonder whether swiping different directions is that obvious?

The movement of the card you swipe goes with the direction of swipe, but I feel like rather than a Back and Forward analogy, whether a circular analogy is more intuitive?  
ie. Swipe either direction to change card (which would be doubly cool if the card went whichever direction you chose to swipe). 

Not a big deal, but be interesting to see user behaviour on this.

**Comment by neutrinog** [comment]
I see what you mean. It should be fairly easy to allow swiping in both directions. So you could either swipe back and forth or in a circle.

**Comment by neutrinog** [comment]
@PhotoNomad0 all the animations for moving cards in either direction is already there. We just need to allow users to swipe either left or right and animate accordingly. Should be a pretty simple update.
