### ISSUE TITLE
if a push fails due to an authentication failure re-generate and re-register the ssh keys

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#1032]
We should first prompt the user if they would like to try again. If they choose to try again we should re-generate the keys and re-register with the server before performing another push. 

This is necessary because if someone discovers another users's device id they could register their own public key to gain access to the repos for that device. The original user would then lose access to their repository. Allowing users to re-register their keys (without going into the developer settings) will help translators to easily re-gain access to their repos.

This can also help resolve problems that occur with issues on the server.

**Comment by neutrinog** [comment]
we already have methods for regenerating the ssh keys including a ui in the developer tools. We'll just need to create a new task that handles all of this.

**Comment by PhotoNomad0** [comment]
@neutrinog - is this only on publish and save to cloud?  Are there any other places this needs to be added?

**Comment by neutrinog** [comment]
Technically there is another location. when you want to browse for your backups online and you have a fresh install of the app or you had previously manually regenerated your ssh keys, the check for backups would fail. This is mostly due to the fact that I never added in the code to register the ssh key if it had not already been registered (oops!). That hasn't been an issue because most people will not be uninstalling/regenerating their ssh keys. 

That's a separate issue that should probably be fixed before fixing the actual issue at hand.

**Comment by PhotoNomad0** [comment]
@neutrinog - I am looking in UploadTargetTranslationTask.pushRepo() and my guess is that an ssh authentication error would throw a TransportException.  Does that sound right or am I going down the wrong path?

**Comment by neutrinog** [comment]
I'm not sure. If you try regenerating the ssh key in the developer settings then use the debugger to step through it you should be able to find what exception is thrown.

**Comment by PhotoNomad0** [comment]
Thanks, that worked.
