### ISSUE TITLE
level 2 and 3 being deleted

### ISSUE THREAD

**Issue by markellishancock** [unfoldingWord-dev/ts-android#1058]
Mark Thrash
We are beginning a MAST here in Ghana to work together to check French OBS to level 2 and 3. We also translated Philemon. When the translators click "done" it either deleted the data or repeats it into the next 2 or 3 chunks. HELP!!

**Comment by neutrinog** [comment]
related to https://github.com/unfoldingWord-dev/ts-android/issues/1055, possibly https://github.com/unfoldingWord-dev/ts-android/issues/1053
