### ISSUE TITLE
Backup on version 3

### ISSUE THREAD

**Issue by markellishancock** [unfoldingWord-dev/ts-android#1093]
Right now it seems tS backups to the same file.  It does not look like it backs up to individual files.  I am told version 2x did this and it would be good.

**Comment by neutrinog** [comment]
could you describe this a little more?

**Comment by PhotoNomad0** [comment]
@markellishancock @neutrinog - I think the confusion is that the backup just creates a single tstudio file.  Christine said the older version had separate files for each translated chunk.  They thought this was helpful for doing data recovery.

If I understand correctly the backup tstudio file is actually a zip file that contains all the translated chunks as text files.  So once unzipped we do have separate files for each translated chunk, but we also have the benefit of a revision history in git.
