### ISSUE TITLE
Import from online needs to register the ssh keys first if necessary

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#1102]
Right now it is only trying to read from the server. So if you haven't already registered the ssh keys with the server you'll need to perform a backup or a publish first (either of which will register the ssh keys if needed).

We need to add support for registering the keys to the import from online as well.

**Comment by neutrinog** [comment]
@PhotoNomad0  this was the issue I mentioned to you before regarding registering the ssh key.

**Comment by PhotoNomad0** [comment]
This is addressed in PR #1273

**Comment by PhotoNomad0** [comment]
This is addressed in PR #1273, but handled a little differently.  In case of auth failure, I prompt user if they want to register keys and retry.
