### ISSUE TITLE
Support Audio Recording

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-android#116]
If we can fit this into 2.1.0 that would be great, otherwise 2.2.

We need to support recording an audio translation of a given project in addition to written translation.

**Comment by jag3773** [comment]
I think we should support 3gp and mp3.  I think we want to default to mp3 but have a setting that could toggle that back to 3gp.  Brad can weigh in on what his thoughts are.

**Comment by studiofortyone** [comment]
MP3 format/44.1kHz/128kbps should be set as the default for recording. The only "lesser quality" we should consider supporting would be MP3/22kHz/64kbps if somebody was in a real jam. We don't want to compromise further than that or get into other lower quality lossy formats. What would it take to build in a provision in tS for the option of WAV and/or FLAC format? The majority of recording scenarios probably would not be able to make use of this, but it would be great to equip those that are interested and able to do lossless recording as a selectable option, not the default. Could tS be set up with 3 quality levels for recording as such:

Level 1 - lowest quality - MP3/22kHz/64kbps (selectable option)
Level 2 - standard quality - MP3/44.1kHz/128kbps (default setting)
Level 3 - best quality - WAV or FLAC (selectable option)

Thanks guys!
Brad
uW Audio Engineer

**Comment by jag3773** [comment]
This will be through tR.
