### ISSUE TITLE
apply styles to tA articles

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#1187]
http://stackoverflow.com/questions/28380475/how-to-set-font-size-and-text-color-in-webview

We need to set the font size, typeface and colors.

The webview in question is in `com.door43.translationstudio.newui.translate.ReviewModeFragment.renderTranslationArticle()`

The font size can be change by the user so be sure to get the font size using `Typography.getFontSize()`. This method will always return the correct font size.

We may need to use this in other webviews later on so it might be a good idea to add a new method to the `Typography` class that takes in the webview and context and does whatever is necessary to set up the typography in the webview.

**Comment by jshuma** [comment]
Added a [pull request](https://github.com/unfoldingWord-dev/ts-android/pull/1221)
