### ISSUE TITLE
why is there a place for device name in the app...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1188]
Notes
======
why is there a place for device name in the app when it is already on thesettings

Environment
======
Environment Key | Value
:----: | :----:
version | 3.1.0
build | 109
UDID | 5b6cd5a04ac8d25b
Android Release | 5.0.2
Android SDK | 21
Brand | samsung
Device | gt510wifi

**Comment by neutrinog** [comment]
this bug report does not make any sense.
