### ISSUE TITLE
Request to display intro to Psalms in TS

### ISSUE THREAD

**Issue by DonRitchey** [unfoldingWord-dev/ts-android#1189]
This issue is related to Help Desk ticket 1510:

Request for someone to fix the problem that keeps the intro to Psalms such as 3 and 4 from displaying in TS.

Researched Slack and Github issues to find out if this is already being addressed:

From November 25th Slack:
Question: Is there already a plan to make the Psalm superscriptions (first line intros) appear, or do I need to send a help request?

Response: are superscriptions what we are seeing here? https://github.com/unfoldingWord-dev/ts-android/issues/994

Response: No, isssue 994 is for the \ms code. We also need the \d code to work. Both are found at the beginning of Psa 90.

Github issue 994 was thought to be related but this is a different issue that needs to be resolved.

**Comment by neutrinog** [comment]
@jshuma you may need to talk to @jag3773 about this one.

**Comment by jag3773** [comment]
This issue was moved to unfoldingWord-dev/ts-requirements#14
