### ISSUE TITLE
Mark 9:46 is missing in both English ULB and UDB in 3.1.0-109

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord-dev/ts-android#1190]

**Comment by neutrinog** [comment]
this should be fixed once we re-build the api.

**Comment by PhotoNomad0** [comment]
Feedback from @ChrisJarka is that this verse has this verse is not present in all verses.  There is a note in the the previous verse.  This is not a ts-android issue, but is the UDB and ULB source.  The plan is to add a note to the sources.  We should close this.
