### ISSUE TITLE
support translating tN

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#1193]
We could provide two ways for users to translate notes. The first method will be during a book translation. In the same way that users will be able to create footnotes (see https://github.com/unfoldingWord-dev/ts-android/issues/1197) they will be able to create a translationNote. They must select the reference that they are adding a note to and then enter a note.

When a chunk has translationNotes added to it a note icon can be dispalyed on the targetTranslation card. Clicking on this icon will display an interface in which users can see and possibly edit their translation notes.

> Note: we cannot indicate translationNotes inline with the text due to complexities with keeping the note data separate from the passage text.

Another method of translating notes will be to allow users to start a new note translation project (one will be started under the hood in the situation described above). When they do so they will be able to navigate the chapters and chunks of the book they are translating notes for. The source in this case will be their translation of the book. In place of the traditional  targetTranslation card will be an interface where they can add a translationNote for the source text. The english (or a more appropriate language if available) translationNotes will be available in the resources for reference.

The benefit of this interface is translators will be able to view their translation notes right beside their translation.

> Note: we could possibly allow users to easily move back and forth between the two projects mentioned above. e.g. when they are translating in the notes project the source card could provide a button that would allow them to jump back to the book project so they can edit that chunk.

**Comment by neutrinog** [comment]
@jag3773 bump

**Comment by jag3773** [comment]
Sounds right.  Note that option 2 is the higher priority.  We need this on Desktop version asap too.

**Comment by neutrinog** [comment]
@tjklemz @cdwhitfield73 fyi. ^^
We'll schedule to have this implemented in desktop soon. Please provide any input.

**Comment by neutrinog** [comment]
we will not support translating tNin the android app
