### ISSUE TITLE
chapter titles, references, and project titles need to be validated during the publishing process 

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#1196]
right now we are only validating the frames.

**Comment by neutrinog** [comment]
@PhotoNomad0 this occurs in the first stage of the publishing activity. All of the validation occurs in a task `ValidationTask`.

Not every project has chapter titles or reference. You can check the source to see if it does or not.

**Comment by cckozie** [comment]
@neutrinog Is there a way for me test this?

**Comment by neutrinog** [comment]
@cckozie if the project title, chapter title, or chapter reference (as appropriate) is empty then when you begin to publish it will display them as warnings a long with any incomplete chunks. If they are complete then they won't appear at all in the warning list.

**Comment by PhotoNomad0** [comment]
My understanding is that if any of these are not marked done , then they will be flagged at publish time.  Haven't checked about marking something empty as done.

**Comment by cckozie** [comment]
Can't fully test until #1520 and similar are fixed.

**Comment by neutrinog** [comment]
@PhotoNomad0 @cckozie I've already fixed #1520. It will be in the next build.
