### ISSUE TITLE
organize user interface guidelines in wiki

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#1214]
There have been a lot of issues created regarding UI design. We need to go through the current open/closed issues and place all of these guidelines (especially the images) in the requirements wiki https://github.com/unfoldingWord-dev/ts-requirements/wiki/Design-Guidelines

**Comment by neutrinog** [comment]
be sure to look through https://github.com/unfoldingWord-dev/ts-android/issues and https://github.com/unfoldingWord-dev/ts-desktop/issues for design guidelines. However, most of the UI guidelines will be found in the ts-android repository.

**Comment by soccerhand** [comment]
Gleaned a lot of info - still need to organize it.

**Comment by neutrinog** [comment]
thanks. If you want to go ahead and place things on that page I can help organize it

**Comment by soccerhand** [comment]
Thanks man that would be awesome - you are probably in a better position to organize it anyway. I just put some more stuff out there with some rudimentary organization.
I was imagining breaking this out into several sub pages (all the images on one page is overwhelming). Just a thought. I'll turn this over to you now - just let me know what else you need.
https://github.com/unfoldingWord-dev/ts-requirements/wiki/Design-Guidelines

**Comment by soccerhand** [comment]
Most of the invision designs Sam did required a login, so I didn't get anything from those. I did link to the one that I could see (the Tablet UI).
