### ISSUE TITLE
Allow users to change their default profile info in the settings.

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#1228]
This should go under the General settings.
I think just a clickable row that opens a dialog where the user can edit their profile info.

For the settings item title the element like this
**Profile**
name, email, phone

related to #1000

**Comment by jshuma** [comment]
Added a [pull request](https://github.com/unfoldingWord-dev/ts-android/pull/1230).

Screen shots:
<img width="852" alt="screen shot 2016-01-07 at 3 31 09 pm" src="https://cloud.githubusercontent.com/assets/7755451/12186010/cd9e1674-b553-11e5-8c77-0a4c347b610b.png">

<img width="553" alt="screen shot 2016-01-07 at 3 31 22 pm" src="https://cloud.githubusercontent.com/assets/7755451/12186011/d2a598d6-b553-11e5-9300-7c5a7fc1b0a5.png">

**Comment by neutrinog** [comment]
Great. Can you remove "Your" from each of the fields?

**Comment by jshuma** [comment]
Done.

**Comment by neutrinog** [comment]
also when you rotate the device the listener on the dialog breaks. I usually end my `onCreate` methods with a check for existing dialogs and reattach the listener.

Here's an example from a different project
```
Fragment prev = getFragmentManager().findFragmentByTag(SetPinDialog.TAG); 
if(prev != null) {
       ((SetPinDialog)prev).setOnClickListener(pinDialogListener);
}
```

**Comment by jshuma** [comment]
Wow, that's a great catch. Updated.
