### ISSUE TITLE
migrate to using USFM in app rather than USX.

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#1250]
We'll need to update the api to serve USFM as well

**Comment by jag3773** [comment]
Relates to https://github.com/unfoldingWord-dev/ts-requirements/issues/12

**Comment by neutrinog** [comment]
When we make this change we need to add a migration path to convert old verse tags in the target translation.

**Comment by neutrinog** [comment]
this will just be for verse markers until #1288 is complete.

**Comment by PhotoNomad0** [comment]
@neutrinog @jag3773 - where do I find out about the USFM format?

**Comment by neutrinog** [comment]
@PhotoNomad0 there are links to documentation in the lower part of this page http://paratext.org/about/usfm. 

Verses are formatted like this `\v #`

**Comment by PhotoNomad0** [comment]
@neutrinog - what I am understanding so far is that we need to:
* add a USFX to TranslationFormat
* create a USFXRenderer that for now will be similar to USXRenderer except for verse parsing.
* on import we will need to detect USX format and convert to USFX format.
* also when the app is upgraded, it will detect and convert current translation projects from USX to USFX format.

I suppose there is a flag in the manifest that identifies the translation format.

**Comment by neutrinog** [comment]
There's no USFX. The formats we are dealing with are `USFM` (old/current) and `USX`.

**Comment by PhotoNomad0** [comment]
@neutrinog - Oops revised format names in question.  Will we run into issues with having to support older USFM versions?

**Comment by neutrinog** [comment]
> NOTE: I edited the comments above to use the correct terminology. 

The steps you've defined above look good. However, keep in mind anything we do with USFM at this point is temporary until we complete #1288.

The manifest does not currently indicate which format the translation is in, I will update the spec to include this information and we will just assume if it's not defined it is USX so we can be sure to migrate everything.
