### ISSUE TITLE
Create ui for handling merge conflicts

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#1290]
Please see #1255 for details on what the ui should look like. 

Users should not be allowed to move verse markers or directly edit the text in a chunk that has a merge conflict until they choose one of the following:
- keep green text
- keep red text
- keep both (for manually editing)

Until they choose one of the above if they tap on the chunk card they should be presented with a dialog explaining their options with appropriate confirmations/previews when making a selection.

**Comment by neutrinog** [comment]
follow the design seen in the desktop app.

**Comment by PhotoNomad0** [comment]
ts-desktop issue is: https://github.com/unfoldingWord-dev/ts-android/issues/1290

**Comment by cckozie** [comment]
If there are more than two conflicts in a chunk, multiple conflicts appear in one of the boxes with the old <<<<<<<<<<HEAD, etc. codes showing.

**Comment by cckozie** [comment]
Also, when there is a single conflict in the chunk it looks like the font is enlarged. This may confuse the translator, especially if there are line breaks in the text, since the formatting now appears differently. This is the case when the project is displayed immediately after the merge. If I exit the project and then go back into it, the font is the normal size.

**Comment by PhotoNomad0** [comment]
> If there are more than two conflicts in a chunk, multiple conflicts appear in one of the boxes with the old <<<<<<<<<<HEAD, etc. codes showing.

@cckozie - This is the case where there are nested conflicts - that is where there was an unresolved merge conflict, and then another change is merged in.  If there are more than one line changed in a normal merge, each line changed will be shown as orange.

Do we have a UI design for handling multi-nested merge conflicts?

**Comment by PhotoNomad0** [comment]
> Also, when there is a single conflict in the chunk it looks like the font is enlarged. This may confuse the translator, especially if there are line breaks in the text, since the formatting now appears differently. This is the case when the project is displayed immediately after the merge. If I exit the project and then go back into it, the font is the normal size.

@cckozie - Having trouble following this, or maybe I am just not seeing this.  Can you give me screen shots?

**Comment by PhotoNomad0** [comment]
> Also, when there is a single conflict in the chunk it looks like the font is enlarged. This may confuse the translator, especially if there are line breaks in the text, since the formatting now appears differently. This is the case when the project is displayed immediately after the merge. If I exit the project and then go back into it, the font is the normal size.

Think I found a bug causing inconsistent font sizing.  Rolling out a fix for this.

**Comment by cckozie** [comment]
@PhotoNomad0 If you follow the steps outline in #1659 you will see that the warning about a merge conflict is displayed upon the second and third imports, but I don't see the conflict displayed in any of the chunks. I don't believe there really is any conflict, and the error message is displayed by mistake. (No conflict is reported when following the same procedure in desktop)

**Comment by cckozie** [comment]
Still fails in build 143

**Comment by cckozie** [comment]
Also, the git control characters are displayed in chunks that contain conflicts when in read mode.
![screenshot_2016-11-18-15-19-28](https://cloud.githubusercontent.com/assets/8171759/20447082/922dfeea-ada2-11e6-9d7d-8fe951ae052d.png)

**Comment by cckozie** [comment]
I've run across another situation where conflicts are detected/displayed when I don't think a conflict actually exists (at least not one that is detectable with tS). Here is the file I used and process I followed:
[1479828200979_en_PHP_Philippians.usfm.zip](https://github.com/unfoldingWord-dev/ts-android/files/606837/1479828200979_en_PHP_Philippians.usfm.zip)
1. Imported USFM file
2. Added a source text to the imported USFM project
3. Uploaded the project to doo43
4. Exported the project to USFM
5. Deleted the project
6. Imported the USFM file from step 4 above
7. Imported the door43 project from step 3 above
It now shows a conflict in every chunk except the title chunk, chapter chunks, and last chunk

**Comment by PhotoNomad0** [comment]
> I've run across another situation where conflicts are detected/displayed when I don't think a conflict actually exists (at least not one that is detectable with tS). Here is the file I used and process I followed:
> [1479828200979_en_PHP_Philippians.usfm.zip](https://github.com/unfoldingWord-dev/ts-android/files/606837/1479828200979_en_PHP_Philippians.usfm.zip)
> 1. Imported USFM file
> 2. Added a source text to the imported USFM project
> 3. Uploaded the project to doo43
> 4. Exported the project to USFM
> 5. Deleted the project
> 6. Imported the USFM file from step 4 above
> 7. Imported the door43 project from step 3 above
> It now shows a conflict in every chunk except the title chunk, chapter chunks, and last chunk
> 

@cckozie - looking at this there are issues with extra linefeeds, chapter labels, etc.  We already have an issue to make USFM export and USFM imports identical.

**Comment by cckozie** [comment]
The icon indicating that there are conflicts should be displayed regardless of which viewing mode they are in. Currently it is only displayed when in review mode.

**Comment by cckozie** [comment]
It is much better now, as I'm only seeing conflicts in the first chunk of each chapter. In the original usfm file, there is a /p /c /s /p marker each on its own line at the beginning of each chapter. It looks like the \c and \s markers are getting stripped out leaving the two /p markers. In the export to usfm, the additional line feeds between the two /p markers are stripped out. In the export to door43 they are not stripped out. So the difference that apparently causes the merge conflicts is the difference in line feeds between the /p markers.
In any case, this isn't a problem with the UI for merge conflicts, so I am passing this issue.
