### ISSUE TITLE
the Bible words are duplicating on the checking...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1302]
Notes
======
the Bible words are duplicating on the checking chunks

Environment
======
Environment Key | Value
:----: | :----:
version | 3.1.0
build | 110
UDID | 345d81bb2e44e64a
Android Release | 5.1.1
Android SDK | 22
Brand | google
Device | grouper

**Comment by jag3773** [comment]
@neutrinog and @jag3773 I updated the tS app yesterday and today and now my tW in a Bible chunk are duplicated! Please note on the attached pic the duplication of tW in a chunk
![screenshot_20160225114113](https://cloud.githubusercontent.com/assets/9850185/13329290/0b937ff8-dbc1-11e5-864a-cb97d9a819db.png)

**Comment by neutrinog** [comment]
this is probably because they downloaded updates from the server and we did not clear out the old translation words. We need to either only add new ones or delete everything and add everything.

**Comment by neutrinog** [comment]
This appears to have already been fixed since 3.1. They should update their app to the latest version.
