### ISSUE TITLE
Include License File

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-android#1309]
See https://github.com/unfoldingWord-dev/ts-requirements/issues/8 for more details

**Comment by neutrinog** [comment]
The license file is now part of the target translation spec. https://github.com/unfoldingWord-dev/ts-requirements/wiki/Target-Translation#folder-structure. We will need to include the license file in the migration of target translations as well.

**Comment by neutrinog** [comment]
when a target translation is created or migrated from an older version a new `LICENSE.md` file will be added to it's directory.

**Comment by cckozie** [comment]
Tested on Android 5.1.1
