### ISSUE TITLE
Allow users to change the target language of their translation

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-android#1319]
See unfoldingWord-dev/ts-requirements#33 for full details

If Jack starts translating in a language x then Jill starts translating in a language Y but then realize Jack chose the wrong language code they need a way to fix that and merge their translations.

Providing a setting some place where you can change the target language would solve this. However, we probably don't want to make this too prominent to avoid people accidentally switching their languages, and be sure to offer plenty of warnings and explainations.

**Comment by neutrinog** [comment]
and the resource

**Comment by PhotoNomad0** [comment]
@neutrinog - is this something I could work on?

**Comment by neutrinog** [comment]
this is being handled as part of #807.

**Comment by neutrinog** [comment]
reference what desktop has implemented.

**Comment by cckozie** [comment]
The app does allow me to change the target language. However, if that project already exists with the selected target language, the user should be warned and give the option to either cancel or the change or merge the project with the existing one. Currently if I change the language to be the same as an existing project for that book, I end up with two projects with the same book and language.

**Comment by PhotoNomad0** [comment]
@cckozie - have submitted a pull request that checks for existing projects and prompts user to merge.

**Comment by cckozie** [comment]
In 11.0 - 153
1. Imported a Philippians ULB English demo 1 project.
2. Changed it to English demo 2.
3. Imported a different (no shared history) Philippians ULB English demo 1 project.
4. Changed the project from step 2 back to English demo 1.
Now there are two Philippians ULB English demo 1 projects. The two were not merged.

**Comment by PhotoNomad0** [comment]
@cckozie - what account should i import this from to reproduce this?

**Comment by cckozie** [comment]
@PhotoNomad0 Use the ones for users qa99 and qa8.

**Comment by PhotoNomad0** [comment]
@cckozie - see the problem now.  Thanks, good catch.

**Comment by cckozie** [comment]
The app really should gray out the current language so that it cannot be selected as the new language. I'll write that up and put it in the backlog.
