### ISSUE TITLE
Implement Link Format

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-android#1323]
There are more details on this new feature found here: unfoldingWord-dev/ts-requirements#23

**Comment by neutrinog** [comment]
See requirements for block reason

**Comment by neutrinog** [comment]
This is mostly complete except for parsing Bible references.

**Comment by cckozie** [comment]
Bible references are not displayed as link as of travis build 1164.

**Comment by cckozie** [comment]
Some links are not displayed as links
![screenshot_2017-02-17-16-34-29](https://cloud.githubusercontent.com/assets/8171759/23084271/22baa316-f527-11e6-82da-756a49f48469.png)

**Comment by cckozie** [comment]
![screenshot_2017-02-17-15-40-28](https://cloud.githubusercontent.com/assets/8171759/23084396/b3102058-f527-11e6-9978-bb32abd9d2a8.png)
![screenshot_2017-02-17-16-34-29](https://cloud.githubusercontent.com/assets/8171759/23084397/b315de1c-f527-11e6-81ba-125f415568b0.png)

**Comment by cckozie** [comment]
The problem noted directly above has been resolved, but in my interpretation of the original requirement, support for Bible links should be part of this issue.

**Comment by neutrinog** [comment]
@cckozie  or @ChrisJarka do we have any Bible references in any of the helps? It would be nice to have an example to work against.

**Comment by cckozie** [comment]
@neutrinog I've been testing with I Chronicles 6:16-18. The first and third Notes refer back to another chunk.

**Comment by neutrinog** [comment]
@cckozie those links are problematic because they do not indicate the book. You and I can tell by context that it's the current book, but programatically it's much more difficult. 

e.g. if I search for a `chapter:verse` and link it to the current book we can run into problems if there are links like `different_book chapter:verse`.

If we are certain there will never be references to other books great. we can parse the links as is, otherwise we need to prefix them with the book name.

**Comment by cckozie** [comment]
@neutrinog The "fix" was put into desktop v11 with that assumption, so I think it makes sense to make that change in Android too.

**Comment by ChrisJarka** [comment]
@neutrinog Sorry, I could swear I responded to this.  There should never ever be a time when the chapter:verse link would not be in the same book. (Ignore the double negative.) And the link should always point to a previous spot in the same book.

**Comment by neutrinog** [comment]
this if fixed.
