### ISSUE TITLE
Create front-end for GOGS

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-android#1334]
Create the front-end interfaces for the work completed in #1259 

- [x] A way to create an account on git.door43.org (if needed)
- [x] A way to sign into said account
- [x] A way to associate the SSH key of the device with the user's account
- [x] A way to associate the local repo with the remote repo, which would have the form of [useraccount]/[reponame]
- [x] Pushing probably already built and may not need to change

**Comment by neutrinog** [comment]
started refactoring profiles to support gogs. Loosly following the proposed profile process. We'll get that ironed out tomorrow hopefully.

**Comment by neutrinog** [comment]
the ui for logging in the app is almost done. Just need to finish hooking up the backend.

**Comment by neutrinog** [comment]
This is just about finished. Backing up and restoring has also been migrated to use gogs. The last bit remaining is to correctly handle merge conflicts that arise from changes on the server.

**Comment by cckozie** [comment]
See #1443 - Could not create new door43 account

**Comment by cckozie** [comment]
See #1447 bug report
