### ISSUE TITLE
Import translations by other users from GOGS 

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-android#1343]
Refer to developing requirements in unfoldingWord-dev/ts-requirements#41

**Comment by cckozie** [comment]
When importing a translation from GOGS, extra text appears in the chunk when there is a merge conflict.
Android project before import:
![screenshot_2016-05-19-14-12-59](https://cloud.githubusercontent.com/assets/8171759/15406960/4ca08bcc-1dce-11e6-9d90-119ecdf89014.png)

GOGS project:
![3jn qa1](https://cloud.githubusercontent.com/assets/8171759/15406988/6e826cd8-1dce-11e6-9891-4e5228e638ff.jpg)

Android project after merge:
![screenshot_2016-05-19-14-27-03](https://cloud.githubusercontent.com/assets/8171759/15407006/83fdeb32-1dce-11e6-8fc3-152a5d438c1b.png)

**Comment by neutrinog** [comment]
@cckozie this is intentional because it provides the groundwork for rendering the merge conflicts in a meaningful way.

**Comment by cckozie** [comment]
@neutrinog I don't see that extra stuff in desktop and like that approach better.
