### ISSUE TITLE
Import USFM Data

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-android#1344]
See https://github.com/unfoldingWord-dev/ts-requirements/issues/42

**Comment by cckozie** [comment]
Cannot import a partial book.

**Comment by cckozie** [comment]
When importing a file that is missing a chapter marker, the app indicates that no errors were found, but it does not import the chapter without the chapter marker. Here's the file I used for testing:
[php_usfm_NoC1.usfm.zip](https://github.com/unfoldingWord-dev/ts-android/files/273693/php_usfm_NoC1.usfm.zip)

**Comment by cckozie** [comment]
Tested on 8.0 - 130
Extra line feeds when importing usfm files
![screenshot_2016-05-20-07-37-51](https://cloud.githubusercontent.com/assets/8171759/15427920/f7e7a6fc-1e5d-11e6-85f8-4899797f3937.png)

**Comment by cckozie** [comment]
We should import the text in chunks even if the verse markers are missing.

**Comment by PhotoNomad0** [comment]
@cckozie @neutrinog - will look into the issue with missing chapter - that should fail.  The requirements we agreed to is that this is to only accept complete usfm files.  I believe the use case was that user wants to import text created with a different bible editor.  If we accept incomplete usfm files it will increase the complexity of this issue greatly, and we will have to agree upon expected behaviors in all failure modes (e.g. warning messages, and where will we put unknown data).

**Comment by neutrinog** [comment]
@cckozie @PhotoNomad0  If they are missing a chapter or verse marker then the imported text will potentially have super chunks that contain text from several other chunks. This is not ideal but should not break things. We just need to make sure to adhere to the correct number of chapters and chunks in each chapter as indicated by https://api.unfoldingword.org/bible/txt/1/mat/chunks.json

**Comment by cckozie** [comment]
Merge is not working properly. One of these files has only chunk 1 defined, the other has only chunks 2 and 3 defined. After importing both projects, I only end up with the data from the first one imported.
[en-x-demo1_phm_text_ulb-B.zip](https://github.com/unfoldingWord-dev/ts-android/files/282390/en-x-demo1_phm_text_ulb-B.zip)
[en-x-demo1_phm_text_ulb-C.zip](https://github.com/unfoldingWord-dev/ts-android/files/282389/en-x-demo1_phm_text_ulb-C.zip)

**Comment by neutrinog** [comment]
@PhotoNomad0 when importing the usfm are we placing it in a temporary target translation dir first then performing a merge between it and any existing target translation?

**Comment by neutrinog** [comment]
see the spec here https://github.com/unfoldingWord-dev/ts-requirements/wiki/Importing-a-Target-Translation#importingrestoring

**Comment by PhotoNomad0** [comment]
Temporary directory yes. Then we do merge.

**Comment by PhotoNomad0** [comment]
I probably need to rethink this.  Git merges are not helpful here since there is no history with the USFM import.  So the choices of merge and overwrite effectively become either clobber or ignore.  Maybe instead of using git for merge on USFM import we probably only want to copy over the non-empty chunks.  Then if the target cell is empty we give choice whether to overwrite or keep?

**Comment by PhotoNomad0** [comment]
Merging with empty chunks displays merge conflict text.  Not pretty, but text is not lost.

**Comment by PhotoNomad0** [comment]
@cckozie 
```
Tested on build 131 (same as later issues noted in desktop #366)
Merge is not working properly. One of these files has only chunk 1 defined, the other has only chunks 2 and 3 defined. After importing both projects, I only end up with the data from the first one imported.
en-x-demo1_phm_text_ulb-B.zip
en-x-demo1_phm_text_ulb-C.zip
```
Your comment here must be for a different issue.  This issue is about USFM data import, but these are tstudio files.
