### ISSUE TITLE
Tag repos to indicate when published

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-android#1350]
Please see all of the details at https://github.com/unfoldingWord-dev/ts-requirements/issues/37

Some of the features have been implemented; especially on the Android side. Some features need to be cleaned up. Please read all of the comments on the requirements.

**Comment by neutrinog** [comment]
@PhotoNomad0 the tagging is already set up we just need to make sure the tag is formatted correctly. See `TargetTranslation.setPublished()`.

**Comment by PhotoNomad0** [comment]
@neutrinog - it doesn't look like the TargetTranslation.setLegacyPublished() method needs to be touched since PublishFragment is calling TargetTranslation.setPublished() before calling  TargetTranslation.setLegacyPublished().

**Comment by neutrinog** [comment]
When a target translation is published a new git tag will be added to the target translation repository (the directory is the repository). You can view tags on a repository by using the command line and navigating to the directory and running `git tag`. There are also gui applications for viewing git repositories as well.

**Comment by PhotoNomad0** [comment]
@neutrinog @RRohrssen  - confused here.  Is there more to be done on this?  I thought this was finished since the pull request is merged.

**Comment by neutrinog** [comment]
just leaving some notes for Chris. I left notes in a few of these issues. Just ignore them :)
Everything in the QA board is "done".

**Comment by cckozie** [comment]
Tested on Android 5.1.1
I did a publish and also exported the project. There is only one file in the zip, the txt. Running git tag shows nothing. What am I missing?
