### ISSUE TITLE
No Overwrite warning on backup

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-android#1357]
Make sure these boxes are checked before submitting your issue -- thank you!
- [X] Check that you are using the [latest version](https://github.com/unfoldingWord-dev/ts-android/releases/latest) of the app.
- [X] Check that a similar issue has not already been opened.

See https://github.com/unfoldingWord-dev/ts-requirements/issues/60

**Comment by neutrinog** [comment]
are you referring to creating a backup or restoring a backup?

**Comment by RRohrssen** [comment]
This is from restoring a backup.

**Comment by PhotoNomad0** [comment]
@neutrinog - i don't think this is needed anymore.  We no longer over-write projects, only merge them.
