### ISSUE TITLE
Inconsistencies between Android and desktop apps

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1362]
@cckozie commented on [Mon Mar 21 2016](https://github.com/unfoldingWord-dev/ts-requirements/issues/62)

Terminology:
Android: "My translations"    Desktop: "Home"
Android: "Import"                  Desktop: "Restore"

On Android, the last source language for OBS is right justified, on desktop it is left justified.

When attempting to mark an empty chunk as done, Android pops up a Confirm dialog, desktop pops up a Missing data dialog.

Android OBS questions show references, desktop does not

Android shows attached files when sending feedback, desktop does not.

Android shows the Publish state on the info screen, desktop does not.

When selecting a target language on Android, clicking the magnifying glass shows positions the cursor to a place to enter the search. The desktop show the "Choose a target language" text, clicking the magnifying glass doesn't do anything. That is probably not intuitive for many users.

**Comment by cckozie** [comment]
Issue moved to [unfoldingWord-dev/ts-desktop #483](https://github.com/unfoldingWord-dev/ts-desktop/issues/483) via [**ZenHub.io**](https://www.zenhub.io/)

**Comment by PhotoNomad0** [comment]
@cckozie - on this item: _On Android, the last source language for OBS is right justified, on desktop it is left justified._

I think you are talking about the "choose source translations" dialog.  It looks like the issue is that the language at the bottom is a right to left language.  Seems to be working as designed by Google.  This may be difficult to fix.

**Comment by PhotoNomad0** [comment]
@cckozie @neutrinog - this is technically not an issue, but multiple issues.  Even if we don't split these, for each item we should have a UI design person specify which is the desired behavior rather than just "make Android and Desktop the same".

**Comment by cdwhitfield73** [comment]
I agree with Bruce's comment above and said the same things months ago about the desktop issue stating the same thing.  We need someone to decide on each point which way we are going to conform to.  Several of these issues have already been addressed though.  As for the source language (arabic) displaying as right justified, we have changed Desktop to match android, so please don't switch android!

**Comment by PhotoNomad0** [comment]
Marked blocked.  This issue does not have enough information to implement.

**Comment by neutrinog** [comment]
I adjusted some text in android to match desktop. This should probably be closed and new issues opened.

**Comment by cckozie** [comment]
Moving remaining differences to new issues in ts-requirements.
