### ISSUE TITLE
Source language not set on imported project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1365]
tS 5.0, Android 5.1.1
The source languages that were selected for a project are not automatically selected after performing an import of that project.

@cckozie commented on [Mon Mar 21 2016](https://github.com/unfoldingWord-dev/ts-requirements/issues/59)

**Comment by neutrinog** [comment]
> Note: we should only use the recorded source translations in the manifest if the app settings does not have a record of open source translations. This will allow the user to open/close sources at will.

**Comment by cckozie** [comment]
Tested on Android 5.1.1
