### ISSUE TITLE
Get Travis Unit Test working

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-android#1378]
Make sure these boxes are checked before submitting your issue -- thank you!

- [] Check that you are using the [latest version](https://github.com/unfoldingWord-dev/ts-android/releases/latest) of the app.
- [] Check that a similar issue has not already been opened.

**Comment by neutrinog** [comment]
the unit tests are now all working. Still trying to get travis working.

**Comment by neutrinog** [comment]
this is working! However some times you must force travis to run the tests again for them to pass. This could still use some looking into but at least it's sorta working.

**Comment by cckozie** [comment]
I see that some tests passed and some failed. I think we need better than "sorta working".
