### ISSUE TITLE
Using on Marshmallow device, installed tS 5.0, ...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1382]
Notes
======
Using on Marshmallow device, installed tS 5.0, updated libraries.  When starting new project I select my target language but tS returns to home screen and displays "error" as a message on bottom of screen.  At this point I was expecting to click on icon to select source language but tS always returns to home screen after selecting target language.

Environment
======
Environment Key | Value
:----: | :----:
version | 5.0
build | 117
UDID | a1eb0296200fef8
Android Release | 6.0.1
Android SDK | 23
Brand | google
Device | angler

**Comment by neutrinog** [comment]
this has been fixed in 7.0
