### ISSUE TITLE
Received error message after the following: 1. ...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1383]
Notes
======
Received error message after the following: 1.  Clicked on Start a new translation, 2. Selected Afaraf as target, 3. At this point error message displays and I am returned to my home screen.  I will now delete all project libraries and update all and try again.  Please let me know how to fix this issue.  Thanks, Don Ritchey

Environment
======
Environment Key | Value
:----: | :----:
version | 5.0
build | 117
UDID | a1eb0296200fef8
Android Release | 6.0.1
Android SDK | 23
Brand | google
Device | angler

**Comment by neutrinog** [comment]
fixed in 7.0
