### ISSUE TITLE
This test ran after deleting all libraries and ...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1384]
Notes
======
This test ran after deleting all libraries and then updating all libraries, still received "error" message on bottom of home screen.

Environment
======
Environment Key | Value
:----: | :----:
version | 5.0
build | 117
UDID | a1eb0296200fef8
Android Release | 6.0.1
Android SDK | 23
Brand | google
Device | angler

**Comment by neutrinog** [comment]
fixed in 7.0
