### ISSUE TITLE
Update the migration of target translations to occur whenever the app starts

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#1400]
Right now we are depending on checking if there is an update. However, if someone uninstalls the app and installs a new version this will fail. Automatically running the migration every time will solve this.

**Comment by neutrinog** [comment]
target translations will now be automatically updated from an older version of the target translations (created by v5.0 app) every time the app starts. This handles the particular use case where a user may first uninstall v5 (or any "old" version) of the app before installing v6.

**Comment by cckozie** [comment]
QA checked OK.
