### ISSUE TITLE
update the target translation adapter on the home page to use tasks for loading translation progress

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#1410]
Right now we are using a `ThreadableUI` which is deprecated. Placing this code in a `ManagedTask` instead will allow us to batch cancel the counting tasks from the activity by assigning a group id to each task. We should cancel all tasks in the ondestroy method of the home activity. Also, we should cache the translation progress of the target translations while on the home page. However we must be careful this cache gets emptied correctly when we import anything or edit a translation.

**Comment by neutrinog** [comment]
this has been fixed.

**Comment by cckozie** [comment]
What is the "while" screen?

**Comment by neutrinog** [comment]
typo.
