### ISSUE TITLE
Long Language names overflow the language column on the projects screen

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord-dev/ts-android#1424]
Long Language names overflow the language column on the projects screen.  With the effect that cannot click on the info button nor see the progress indicator.  To reproduce select the following language on a 7" tablet:

"Originally called Occidental; then Interlingue after WWII" code "ie"

The result is that you cannot delete the project after importing.

**Comment by neutrinog** [comment]
This can be fixed with some tweaks to the layout xml.

**Comment by cckozie** [comment]
Works in 11-153
