### ISSUE TITLE
Multiple issues with the Print option

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1429]
6.0, Android 5.1.1
Printing OBS: unchecked images, clicked include incomplete chunks, clicked print, chose  Google Drive. App appears to be hung, but clicking back triangle twice gets me back to the project.(I let it hang for a few minutes before backing out)
Printing OBS: Chose ES File manager and a folder for the pdf. A small message appears briefly stating "Operation is not supported".
Printing OBS: Chose Bluetooth. Sending message came up but was followed by file not sent message. Both briefly shown briefly.
What options are do we actually support? I could only get email and dropbox to work.
Is there anyway to prevent unsupported options to not appear in the list?

**Comment by PhotoNomad0** [comment]
@neutrinog - it seems like it might be easier just to disable the sharing of pdf since so little of it works.  The user can always use the filemanager to share if they need to.

**Comment by neutrinog** [comment]
I seem to recall a similar issue pertaining to this.
We cannot accurately determine all the valid apps for exporting. To do so would require us to know about every conceivable app. 

We can however, ensure the app is correctly following the api for file providers. That is, if the app is correctly following Google's specification, it's the responsibility of third party applications to handle our files correctly.

**Comment by cckozie** [comment]
This is no longer an issue after the changes were made to allow the user to select the path and file name for the pdf export.
