### ISSUE TITLE
trying to begin a new translation

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1442]
Notes
======
trying to begin a new translation

Environment
======
Environment Key | Value
:----: | :----:
version | 7.0
build | 123
UDID | aec37215833e82ce
Android Release | 5.1.1
Android SDK | 22
Brand | Allwinner
Device | octopus-bt1077

**Comment by neutrinog** [comment]
@cckozie can you describe this bug some more? I don't see any problems with starting translations.

**Comment by cckozie** [comment]
See 1441. Details are there.

**Comment by cckozie** [comment]
Starting a new translation still fails on build 126 on NeuTab device running Android 5.1.1

**Comment by neutrinog** [comment]
seriously.... I'm starting to thing you have a possessed device. ;)

**Comment by PhotoNomad0** [comment]
@cckozie - can you give me the exact model of the table you have?  I'm going to request one for development.

**Comment by cckozie** [comment]
Since this issue only appeared on a specific device and worked on several others running Android 5.1.1, we decided as a team to not address this issue at this time.
