### ISSUE TITLE
Type in verse markers while typing

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-android#1457]
Tom has a team of typists. The typists take the handwritten work that was completed during a MAST event and type them into translationStudio. Their workflow seems to be interrupted and the team frustrated by having the verse markers reset and manually placing them in again and again after every edit. They would like to be able to just type the numbers in while typing the verse in and not having them reset later.

**Comment by neutrinog** [comment]
@RRohrssen this already functions as expected in android.

**Comment by cckozie** [comment]
1. I entered text with verse markers as per the first screenshot.
2. I exited edit mode and saw that the verse marker bubbles were as expected.
3. I dragged the verse 8 marker back to the beginning of the text in the chunk.
4. I went back into edit mode and saw that the verse 8 marker is still shown to be where it was originally placed. The verse 8 marker now shows in different places depending on whether or not I am in edit mode.
![screenshot_2016-05-19-12-32-40](https://cloud.githubusercontent.com/assets/8171759/15403486/cdf22ca4-1dbe-11e6-8311-d666209f3971.png)
![screenshot_2016-05-19-12-32-48](https://cloud.githubusercontent.com/assets/8171759/15403495/db51f6ae-1dbe-11e6-924d-7842305a09a3.png)
![screenshot_2016-05-19-12-32-57](https://cloud.githubusercontent.com/assets/8171759/15403500/e3d703dc-1dbe-11e6-8fda-a15c3f7a81bd.png)
![screenshot_2016-05-19-12-33-04](https://cloud.githubusercontent.com/assets/8171759/15403507/eae8ca8e-1dbe-11e6-94b3-80ae6df71aa2.png)

**Comment by PhotoNomad0** [comment]
@cckozie - good catch.  I see the error also and am looking into the cause.

**Comment by PhotoNomad0** [comment]
@neutrinog @cckozie  - it looks like dragging the verse markers is not triggering a save of the chunk.  When you click out of edit mode the text read back from file has the text in the old position.  Do we want to pull this into this sprint?

**Comment by PhotoNomad0** [comment]
@neutrinog @cckozie - it looks like we may have additional issues.  For example the user can enter more that one verse 1 which gets saved into the document even though only the first instance of verse one is shown in the app.

**Comment by neutrinog** [comment]
@PhotoNomad0 if there are duplicates or verses that do not belong in the chunk they should be removed.

**Comment by PhotoNomad0** [comment]
@neutrinog @cckozie - **Correction:** it looks like dragging the verse markers is not triggering a save of the chunk only in the case the drag is off screen (including start of card). It looks like that issue is a two line fix.

**Comment by cckozie** [comment]
If I type in a verse marker that is not supposed to be in the chunk and then exit edit mode, it is not displayed as a bubble, but when I go back into edit mode, I see that it is still there.

**Comment by PhotoNomad0** [comment]
@neutrinog - I thought the philosophy here was to only check verse markers when they click done.

**Comment by cckozie** [comment]
Tested in 8.0 - 131
Display of verse markers is now consistent in both edit and non-edit review modes.
Verse markers typed in when in review mode are not displayed in blind translate mode.
If verse markers are typed in when in blind translation mode, and then the user switches to review mode and then back again, the verse markers are not displayed.
When marking chunk as done, if there are multiple markers for the same verse, the error message displayed is "Verse markers are out of order" rather than "Duplicate verse markers".

**Comment by neutrinog** [comment]
@PhotoNomad0 correct, checking only occurs when they click done. Therefore users should be allowed to create any verse markers they want in any order and they should remain visible in edit mode and review mode.

Summarizing some things still needing to be changed:
1. display text form of verse markers while in the chunk (blind draft) mode.
2. correct warning dialog to use correct wording when verses are out of order or there are duplicates. If both have occurred it is probably sufficient to display the first error that occurs.

**Comment by cckozie** [comment]
Testing on build 137:
The verse markers are now displayed in blind draft mode
Error messages are now correct for out of range and duplicate verse markers
