### ISSUE TITLE
project is missing after trying to publish then...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1470]
Notes
======
project is missing after trying to publish then app crashes when rotating while merge conflict dialog is open

Environment
======
Environment Key | Value
:----: | :----:
version | 7.0
build | 128
UDID | 29fc019efc78c5c1
Android Release | 5.1.1
Android SDK | 22
Brand | OnePlus
Device | OnePlus
Log history
======
```java
5/11/16 9:03 AM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation aa_2jn_text_reg
5/11/16 9:03 AM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation aa_1jn_text_reg
5/11/16 9:01 AM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation aa_2jn_text_reg
5/11/16 9:01 AM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation aa_1jn_text_reg
5/11/16 9:00 AM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation aa_1jn_text_reg
5/11/16 8:57 AM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation aa_1jn_text_reg
     

```

**Comment by neutrinog** [comment]
this is because the manifest had a merge conflict in it which corrupted the target translation.

**Comment by neutrinog** [comment]
as a precaution the apps should always make sure the master branch is checked out when loading target translations. And the merging should be done in a temporary branch.

**Comment by neutrinog** [comment]
for simplicity this was resolved by just choosing `ours` for the manfiest.json when it has a merge conflict.

**Comment by cckozie** [comment]
@neutrinog Is there something to be tested on this one?

**Comment by neutrinog** [comment]
I thought this was already tested. You'll need to create a merge conflict between the server and the app. You can just use what you've been doing to test the merging when importing except you'll be uploading them to the server.

A merge conflict dialog should appear when when you try to upload the last one. Rotate the device at this point and it should **not** crash.
