### ISSUE TITLE
Formatting being lost

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1473]
Afekhafe Araromi in #translationstudio channel 5/5/16
Another thing I noticed with tS-Android is that the ENTER key is of no use; I guess I may be wrong. But I tried typing in a part of a chunk in the form of poetry, and it still joined every line together.

Moved from #89 in ts-requirements

**Comment by neutrinog** [comment]
right now the app is stripping out the new lines when it is saved. We'll just need to stop doing that.

**Comment by cckozie** [comment]
Line breaks are only displayed in edit mode, and they disappear as soon as I view a chunk in review mode.

**Comment by cckozie** [comment]
Tested on 8.0 - 130
Extra line breaks now appear in the source language and in projects imported from usfm.
![screenshot_2016-05-20-07-37-51](https://cloud.githubusercontent.com/assets/8171759/15428421/e0cb6064-1e60-11e6-99a7-cffabb36d9c9.png)

**Comment by cckozie** [comment]
![screenshot_2016-05-20-07-56-00](https://cloud.githubusercontent.com/assets/8171759/15428481/349cef1e-1e61-11e6-8a9b-7dbd42b76b4c.png)
