### ISSUE TITLE
On Publish if there is a Chunk Conflict, selecting Review differences removes the project

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord-dev/ts-android#1474]
@neutrinog, @cckozie  - a very serious bug that can cause loss of all data in a project in ts-android.

- **Problem:** On Publish if there is a Merge Conflict, selecting Review changes returns to Home Screen where the project is no longer listed.

- **Initial Steps:** import tstudio project, publish this project, and delete project from app.  Changed to new device. Import same tstudio project, select publish, do upload, on Chunk Conflicts dialog, click on review differences.
 
- **Alternate Easier Steps:** import tstudio project, publish this project, make change on first chunk, publish again.  Deleted project from app.  Import same tstudio project, select publish, do upload, on Chunk Conflicts dialog, click on review differences.
 
- **Results:** App returns to Home Projects screen and the project is no longer listed.

- **Troubleshooting:** It looks like the TargetTranslationActivity is being launched to resolve the merge conflicts.  This fails with invalid target id: es_phm_text_reg.  The project has already been deleted.  It looks like pull command in PullTargetTranslationTask is leaving the project in a corrupted state. Error: _"mergeResult = Merge of revisions 80104d8eaaf82ed3f4e6d28d6bca904c2d387b83, aad8de10b20970aec8560991ee1a58ac804d4598 with base a503b58be7af858a60720ae008fb63399771ad5e using strategy recursive resulted in: Conflicting. "_  It looks like the project folder is still present on the device, but the app no longer recognizes it as valid.

- **App Version:** this is in the develop branch.

**Comment by PhotoNomad0** [comment]
It looks like git merge markers are left in manifest that cause a crash parsing the json:

<<<<<<< HEAD
{"target_language":{"id":"es","direction":"ltr","name":"español"},"translators":["blm","blm2","Bruce McLean"],"generator":{"name":"ts-android","build":128},"package_version":6,"type":{"id":"text","name":"Text"},"project":{"id":"phm","name":"PHM"},"resource":{"id":"reg","name":"Regular"},"source_translations":[{"resource_id":"ulb","language_id":"en","checking_level":"3","date_modified":20151120,"version":"2.0.0-beta15"},{"resource_id":"udb","language_id":"en","checking_level":"3","date_modified":20151120,"version":"2.0.0-beta15"}],"finished_chunks":["01-01","01-04","01-08","01-10","01-14","01-17","01-21","01-00","00-title"],"format":"usfm"}
=======
{"target_language":{"id":"es","direction":"ltr","name":"español"},"translators":["blm","blm2","Bruce McLean"],"generator":{"name":"ts-android","build":128},"package_version":6,"type":{"id":"text","name":"Text"},"project":{"id":"phm","name":"PHM"},"resource":{"id":"reg","name":"Regular"},"source_translations":[{"resource_id":"ulb","language_id":"en","checking_level":"3","date_modified":20151120,"version":"2.0.0-beta15"},{"resource_id":"udb","language_id":"en","checking_level":"3","date_modified":20151120,"version":"2.0.0-beta15"}],"finished_chunks":["01-04","01-08","01-10","01-14","01-17","01-21","01-00","00-title","01-01"],"format":"usfm"}
>>>>>>> branch 'master' of git@git.door43.org:photonomad0/es_phm_text_reg.git

**Comment by neutrinog** [comment]
@PhotoNomad0 I found this bug yesterday and already have a fix for it.

**Comment by neutrinog** [comment]
related to #1470
