### ISSUE TITLE
Allow changing file name when printing

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1505]
Currently the user does not get the option to change the file name or storage location when printing. We shouldn't assume that the user will not want to change at least one of these.

**Comment by cckozie** [comment]
This is now very confusing. The app does allow me to change the destination folder and then the file name, but after I click the OK button, it brings up the Android Print dialog which allows me to select from its list of options for saving the file. At this point the pdf has already been saved to the previously selected location/file, so the Android Print dialog should really not be displayed as I believe it will only confuse the user.

**Comment by PhotoNomad0** [comment]
@cckozie - I agree with you that it is confusing.  Since I will be missing stand-ups for the next couple days, can you get consensus with Christine and Klappy?  If they are on board, I can take that out.

**Comment by ChrisJarka** [comment]
I don't know if there will be stand-ups for the rest of the week. 
Let's keep it simple for the end user. If they saved the file already - why have them asked to save it again?

BTW - thank you for letting the user not only choose the file name but where to save it. :)

**Comment by cckozie** [comment]
This works now when printing Bible projects, but not for OBS when printing images.
After requesting to print OBS with images, it is unclear to the user what to do after the image download is complete because the downloading dialog stays on the screen. I could not find a way to get the print generated with images.

**Comment by PhotoNomad0** [comment]
@cckozie - I went through the process of printing and it succeeded.  There is a long pause at the end of download for unzipping images before printing.  Maybe this is the issue here.  I will add status updates for the unzipping of 600 images.
