### ISSUE TITLE
tstudio project merge is not working properly

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1518]
Same issue as #525 in desktop.
The chapter 1, verse 1 text in these two files is slightly different. The merge process does not detect the difference and thus only displays the text from one of the projects for that chunk.
[en-x-demo1_php_text_ulb.2016-05-18_10.34.31.tstudio.zip](https://github.com/unfoldingWord-dev/ts-android/files/282432/en-x-demo1_php_text_ulb.2016-05-18_10.34.31.tstudio.zip)
[en-x-demo1_php_text_ulb.tstudio.zip](https://github.com/unfoldingWord-dev/ts-android/files/282431/en-x-demo1_php_text_ulb.tstudio.zip)

**Comment by neutrinog** [comment]
@cckozie you don't need to zip those files. They are already zipped.

**Comment by neutrinog** [comment]
@cckozie you don't need to zip the `.tstudio` files. They are already zipped.

**Comment by neutrinog** [comment]
@cckozie I suspect the test is not set up correctly. The two version of the text *must* have conflicting changes not only with regard to the content of the chunks but also with regard to the git history. e.g. Each project needs to have a change that the other does not have. Or more specifically you must perform one edit in the chunk of one project and another edit in the same chunk in the other project.

I looked at both the files you attached above and they both share the same history.

**Comment by neutrinog** [comment]
@cckozie use these files for your test

[1464209778_en-x-demo1_phm_text_reg.tstudio.zip](https://github.com/unfoldingWord-dev/ts-desktop/files/282997/1464209778_en-x-demo1_phm_text_reg.tstudio.zip)

[1464209472_en-x-demo1_phm_text_reg.tstudio.zip](https://github.com/unfoldingWord-dev/ts-desktop/files/282999/1464209472_en-x-demo1_phm_text_reg.tstudio.zip)

**Comment by neutrinog** [comment]
you should be able to use these files to perform the same test in desktop however I'm getting this error https://github.com/unfoldingWord-dev/ts-desktop/issues/602

**Comment by cckozie** [comment]
I thought I had created the files separately. Started over with 2 new files and it does work as expected. My bad!
