### ISSUE TITLE
Unexpected results after publishing

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1521]
It looks like a merge of the projects occurs on the device when doing a publish (upload).

Chunk 1 before the publish:
![screenshot_2016-05-25-17-51-59](https://cloud.githubusercontent.com/assets/8171759/15558787/7b0291b2-22a2-11e6-9aef-54839eb9a66a.png)

Chunk 1 after the publish:
![screenshot_2016-05-25-17-53-05](https://cloud.githubusercontent.com/assets/8171759/15558806/97b51f64-22a2-11e6-99fa-a509dc84b7db.png)

**Comment by neutrinog** [comment]
@cckozie this is the expected result. As indicating in the publishing spec https://github.com/unfoldingWord-dev/ts-requirements/wiki/Publishing
