### ISSUE TITLE
Enhance error dialog when upload fails

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1527]
See #1455.
Tell the user more that Upload Failed, if we know more (e.g. connection problem, merge conflicts, etc.)
At a minimum, ask them to try again or to send feedback.

**Comment by neutrinog** [comment]
@cckozie this more of a design issue rather than Q/A. We already provide users with an option to provide feedback. This should go through ts-requirements.

**Comment by PhotoNomad0** [comment]
@neutrinog @cckozie - what do we want to change here?  
Since we already handle merge conflicts with a different prompt.  Would it be sufficient to add a new prompt if the device is not connected to the internet?

**Comment by cckozie** [comment]
@PhotoNomad0 @neutrinog We should tell the user whatever we know about why it failed. The merge conflicts is currently handled, we should always inform the user if they don't have an Internet connection and they try to do something that requires it. (And in that case sending feedback is not a solution). I think we currently handle permissions problems. I'm not sure if there's anything else that would cause it to fail or not, but we should always tell the users what the problem is, if we know.

**Comment by PhotoNomad0** [comment]
We already have a special alert for auth failure.  So I am adding an check for internet access on upload failure.  Since that could have dropped out.

**Comment by cckozie** [comment]
We now have messages for no Internet and merge when project exists on door43 (in another issue), so I'm passing this at v11-153.
