### ISSUE TITLE
USX paragraph markers showing in source text

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/ts-android#1530]
There are USX paragraph markers showing in the English ULB
See Jude 1:5-6

https://team43.slack.com/files/aaserhna/F1DC66V2T/img_20160601_185601.jpg

**Comment by ChrisJarka** [comment]
And this chunk https://door43.org/en/bible/notes/luk/04/01

**Comment by cckozie** [comment]
See 1530
