### ISSUE TITLE
provide font settings for both the source translation and target translation

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#1549]
font size and face should be available for both the source and target.

**Comment by cckozie** [comment]
Changing the target font while in a project does not change all of the target cards until the app is closed and reopened or the device is rotated. Sometimes it changes some cards, sometimes it doesn't change any.
![screenshot_2016-11-11-14-16-18](https://cloud.githubusercontent.com/assets/8171759/20228971/84b137b6-a819-11e6-92d5-497bcbfe66da.png)

**Comment by cckozie** [comment]
This issue is resolved as of build 144.
