### ISSUE TITLE
Russian source text doesn't show up

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1560]
Notes
======
Russian source text doesn't show up

Environment
======
Environment Key | Value
:----: | :----:
version | 9.0
build | 138
UDID | 6adad74dc2587886
Android Release | 5.0.2
Android SDK | 21
Brand | samsung
Device | gt58wifi
Log history
======
```java
7/5/16 4:17 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_jas_text_reg
7/5/16 4:17 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_jas_text_reg
7/5/16 4:10 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
7/5/16 4:10 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_php_text_reg
7/5/16 4:00 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_mat_text_reg
7/5/16 4:00 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_mat_text_reg
     

```

**Comment by neutrinog** [comment]
@benjore : I performed a fresh install from Google Play and Russian displays correctly in Mark. 
I tested on two different tablets.

Just to confirm, you clicked on "Update Library' from the home screen then downloaded the `ru` language for the project on your device? You will have to download it for each project in which you want to use it.

**Comment by neutrinog** [comment]
related to https://github.com/unfoldingWord-dev/ts-android/issues/1561

**Comment by neutrinog** [comment]
I tested on an LG with Android 5.0.2 and it works. So that rules out Android at least for this version.

**Comment by neutrinog** [comment]
@benjore I did find a bug where the app is incorrectly displaying RU as a source translation before it has been downloaded. This will cause the project to be blank if you select RU as a source translation. However if you enter "update library" and download RU for that project then try to open the project again it should work.
