### ISSUE TITLE
DownloadSourceLanguageTask is broken

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord-dev/ts-android#1576]
The constructor for DownloadSourceLanguageTask is asking for a sourceLanguageId, but it then passes that to mLibrary.getResources() which wants a sourceLanguageSlug.  According to @neutrinog DownloadSourceLanguageTask should be switched to using sourceLanguageSlug.  But that means that ServerLibraryDetailFragment will need to be fixed then, because it is passing in item.sourceLanguage.getId() into DownloadSourceLanguageTask.  Should pass in sourceLanguageSlug instead.

There is also a bug in DownloadSourceLanguageTask that just returns success=true if mLibrary.getResources() returns an empty list.  So invalid sourceLanguageSlug are being ignored.

**Comment by neutrinog** [comment]
`item.sourceLanguage.getId()` is returning the slug already. The method just has old terminology. The same is true for the download task. The only thing "needing" to be changed is the actual names of the parameters.
