### ISSUE TITLE
Resource API Client Module

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#1588]
Build the programming interface of the module and methods for pulling data from the api. This will utilize the index module and resource container module to actually index and store the data.

**Comment by neutrinog** [comment]
waiting for the module to finish publishing to bintray

**Comment by cckozie** [comment]
App does not properly deal with disruptions to downloading. The user will incorrectly receive the "Update finished successfully message" in each of these conditions:
1. There is no Internet connection available
2. The Internet connection is disrupted during the download
3. The tablet goes to sleep during the download

**Comment by cckozie** [comment]
When no internet connection is available:
--Update List of Available Source Texts: It looks like it's working as it indicates progress as n of 738, but when that part completes it informs the user that the update failed and they should check their internet connection. They should be warned right away that there is no internet connection.
--Download Available Source Texts: It allows the user to make all of the choices, and when Download is clicked, an error message is presented that 0 source texts were successful, and n download attempts failed. When the red ! icon is clicked, the message indicates that the source was not found on the server. Ideally the user should be warned immediately when selecting the menu option if the Internet is not available, and again when the download button is clicked.
--Update List of Available Target Languages: Update failed message is properly displayed almost immediately. No further action needed.
--Check for Update to translationStudio: You are already using the latest version of translationStudio message is displayed. How can it know this without being able to get to the Internet?

When the Internet connection is lost during the process:
--Update List of Available Source Texts: This appears to work properly
--Download Available Source Texts: It looks like the source that is in the process of being download when the connection fails wrongly gets flagged as successful. The following sources do fail, but again the detailed message is Source Not Found on Server which is not accurate.
--Update List of Available Target Languages: This appears to work properly.
--Check for Update to translationStudio: I can't tell, it happens so quickly. Is the app actually doing anything?

I'll add more after testing for the tablet going to sleep.

**Comment by cckozie** [comment]
I ran the Update List of Available Source Texts. It reported several new source texts available. I ran the update for English for a couple of the gospels. Later when I created a new Philippians project, English ULB and UDB were only displayed in the "Available Online" group. I assume this is because an updated version was available online. In this case, they should still appear in the Available group rather than the Available Online group, and when selected as a source to use and they are moved to the Selected group, they should be shown with the circular arrow to indicate that there is a newer version available.

**Comment by neutrinog** [comment]
@PhotoNomad0 passing this off to you since you know the source list dialog better than me at this point.

**Comment by neutrinog** [comment]
@PhotoNomad0 nevermind, I need more to work on. Taking this back :)

**Comment by neutrinog** [comment]
I also noticed that when downloading an available online source the list is not updated after the download is finished.

**Comment by cckozie** [comment]
Looks good in travis build 1134
