### ISSUE TITLE
Provide sort options for project list

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1593]
See desktop issue 785.
![image](https://cloud.githubusercontent.com/assets/8171759/18496309/82fa0b30-79ea-11e6-8722-737f5e101ac2.png)
![image](https://cloud.githubusercontent.com/assets/8171759/18496335/ac57d3cc-79ea-11e6-9935-676c01b2f334.png)
![image](https://cloud.githubusercontent.com/assets/8171759/18496349/d3867df4-79ea-11e6-8bf5-213084b505db.png)

**Comment by cckozie** [comment]
The user's sort options should be saved and set as the default sort options when the app is reopened.

**Comment by PhotoNomad0** [comment]
Now saving sort settings.
