### ISSUE TITLE
update url given to user after upload

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#1604]
requirements at https://github.com/unfoldingWord-dev/ts-requirements/issues/176

**Comment by cckozie** [comment]
Is this issue in translationStudio - 9.0 (141) #18?
My testing shows 2 problems.
1. The previous success screen with the link to the project has been changed as follows:
Was...
![screenshot_2016-09-28-06-37-14](https://cloud.githubusercontent.com/assets/8171759/18894722/3063d43c-84da-11e6-88d2-24454f5a567e.png)

Now is...
![screenshot_2016-09-27-17-36-11](https://cloud.githubusercontent.com/assets/8171759/18894730/3b252bd2-84da-11e6-95ec-63169f1c0619.png)

2. When the "VIEW ONLINE" link is clicked, it takes me to the old git.door43.org/... page.

**Comment by neutrinog** [comment]
@cckozie the new url is currently a redirect. This is the expected behavior.

**Comment by neutrinog** [comment]
@cckozie is this still failed?

**Comment by cckozie** [comment]
This is what is displayed when the user clicks DETAILS on the Success dialog.
@klappy Is this what we want to display for the repo URL?
![screenshot_2017-01-25-09-20-02](https://cloud.githubusercontent.com/assets/8171759/22296413/b1e92742-e2df-11e6-8629-0a7ba4321e57.png)

**Comment by klappy** [comment]
I like the link that explicitly says, "view online" 
According to Jesse in some issue along the way maybe in the requirements, there was something to use and show only the one link, https://door43.org/u/klappy/en-x-demo1_jas_text_reg which will redirect the users to the appropriate place, currently it redirects to the repo on the gogs server, later it will redirect to the live site.

Let's make it look closer to desktop:

<img width="967" alt="screen shot 2017-02-08 at 7 03 39 pm" src="https://cloud.githubusercontent.com/assets/118073/22763192/40a0ff8a-ee31-11e6-977c-d80bd9526511.png">

**Comment by neutrinog** [comment]
I updated the dialog to look like desktop. However, I left the details button alone. That's simply there to provide context to anyone trying to debug issues. If you want to change that then we may as well remove it since it'll lose it's purpose.
