### ISSUE TITLE
Modify the dialogs displayed when user attempts to upload a conflicting project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1605]
I worked with Christine to determine what is desired for a standard solution across both platforms for the situation where the user attempts to upload a project to door43 when a different project with the same name already exists on the user's door43 account. These are the changes we would like implemented on Android:
1. Remove this dialog from the workflow:
   ![screenshot_2016-09-21-10-23-09](https://cloud.githubusercontent.com/assets/8171759/18765380/168005f2-80db-11e6-8bb5-0bf2e4acf73d.png)
2. Add the word "changes" between "those" and "now" on this dialog:
   ![screenshot_2016-09-21-10-28-30](https://cloud.githubusercontent.com/assets/8171759/18765370/0b173c62-80db-11e6-93c9-8a97da7f39d2.png)

**Comment by PhotoNomad0** [comment]
@cckozie @ChrisJarka - current code shows this message.  Clicking no will leave things unchanged and clicking yes will take you to resolve merge conflicts.

<img width="1532" alt="screen shot 2016-10-04 at 9 56 13 am" src="https://cloud.githubusercontent.com/assets/14238574/19077014/e5afa9fe-8a18-11e6-9f38-dcc54cd5d613.png">

**Comment by ChrisJarka** [comment]
The second and third screen shots are the best. The blame is not on the end-user. The second screen shot with 'Project Change Detected' is much more descriptive than 'Error'.

**Comment by PhotoNomad0** [comment]
@ChrisJarka - thank you.  Will change text to second screen.

**Comment by cckozie** [comment]
Please note the text in 2. on the first comment on this issue and add the word "changes" as noted there.

**Comment by cckozie** [comment]
I uploaded a project to door43 that already existed with a different history. The dialog came up indicating the various processes being run, but when it disappeared, I did not receive either a success of failure message, it just went back to the Upload/Export Options menu. When I look in the repo, all content is from prior dates.

**Comment by cckozie** [comment]
The top line relates to the upload from comment above.
![screenshot_2017-01-25-04-31-34](https://cloud.githubusercontent.com/assets/8171759/22265533/11ea9912-e242-11e6-9a8e-3eca542b821f.png)

**Comment by cckozie** [comment]
When I attempted to upload the project a second time, then it worked but I was not informed of the existing project, and on the device I now see conflicts in every chunk although I doubt they are all legit.

**Comment by cckozie** [comment]
Tried this again with new projects. Same result upon uploading; no indication that there was a project on door43 with no shared history, and no success or failure message. The project was merged on the device and it looks good, with conflicts in 2 chunks.

**Comment by cckozie** [comment]
Tried this one more time with projects that do not have any conflicting chunks. Same result as before, as there was no indication of the existing project and no success or failure message.

**Comment by cckozie** [comment]
When the second project was uploaded with the project open, the merged in data (data in chunks from the first upload that were blank in the second project) were not displayed until I closed and then reopened the project.

**Comment by PhotoNomad0** [comment]
> I uploaded a project to door43 that already existed with a different history. The dialog came up indicating the various processes being run, but when it disappeared, I did not receive either a success of failure message, it just went back to the Upload/Export Options menu. When I look in the repo, all content is from prior dates.

Found issue that resolve merge conflict dialog was not being shown, and that translation chunks were not being redrawn after merge conflict.

**Comment by cckozie** [comment]
Looks good in travis build 1134
