### ISSUE TITLE
Cannot send feedback

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1608]
Running 9.0(141)#15 on Android 5.1.1
When sending Feedback I get a "Success" message on the device, but the issue does not appear in the repo. Multiple attempts.

**Comment by cckozie** [comment]
Still fails in build 144

**Comment by PhotoNomad0** [comment]
@cckozie - this is working now.  Saw my feedback on github.

**Comment by cckozie** [comment]
@PhotoNomad0 Still fails for me on build 149. Gives me the message: "Upload failed. Upload of feedback failed.

**Comment by cckozie** [comment]
log says: the github oauth2 token is missing

**Comment by PhotoNomad0** [comment]
@cckozie - this is working now. Saw my feedback on github.

**Comment by cckozie** [comment]
Still broken here on 11.0 - 153. Message = Upload of feedback failed.

**Comment by cckozie** [comment]
Fixed in travis build 1123.
