### ISSUE TITLE
Add filter to show only chunks with conflicts

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1610]
When displaying a project that has one or more chunks with conflicts, display a new icon indicating that. When the user clicks that icon, switch to review mode (if not already in that mode), and only display the chunks with conflicts. After all conflicts have been resolved, remove the conflict icon and display the project in the normal review mode. Pattern after desktop as shown here:
![conflict_filter](https://cloud.githubusercontent.com/assets/8171759/18844154/a7846a44-83e1-11e6-87f6-c67c1a2694c8.png)

**Comment by PhotoNomad0** [comment]
Waiting for resource containers

**Comment by cckozie** [comment]
The filter works in build 146, but the conflict icon is not highlighted when it is active.

**Comment by cckozie** [comment]
The icon indicating that there are conflicts should be displayed regardless of which viewing mode they are in. Currently it is only displayed when in review mode.

**Comment by PhotoNomad0** [comment]
This may be scope creep here.

**Comment by cckozie** [comment]
The conflict icon is still not highlighted when it is active. It is not obvious to the user if they are in conflict filter mode or in review mode.

**Comment by PhotoNomad0** [comment]
@cckozie - OK, get what you are meaning now.  You are talking about the icon background being highlighted along with the icon which was highlighted.

**Comment by cckozie** [comment]
And looking at it again, now I do see that the icon was being highlighted, it just wasn't very obvious when the background of the review mode icon was highlighted. Sorry for the confusion.
