### ISSUE TITLE
Cannot export project to external SD card

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1637]
![screenshot_2016-10-07-18-11-06](https://cloud.githubusercontent.com/assets/8171759/19206842/7f675ba6-8cb1-11e6-83a5-5b7d36785a6d.png)
I follow the instructions in this dialog, but after clicking Select SD Card and waiting for it to grant access, the file did not get saved there. It did create the Download/translationStudio folder, but it is empty. When I attempted the export again, I immediately get the message below.
![screenshot_2016-10-07-18-19-27](https://cloud.githubusercontent.com/assets/8171759/19206986/7f5cca46-8cb2-11e6-8668-e74c48b6ff00.png)

**Comment by cckozie** [comment]
This is what happens using travis build 1164:
I followed the instructions on this first screen (The text should be fixed to insert needed spaces)
![screenshot_2017-02-17-12-20-03](https://cloud.githubusercontent.com/assets/8171759/23075811/76592c1e-f503-11e6-8504-a8ac8053f70a.png)

**Comment by PhotoNomad0** [comment]
@cckozie - fixed a few possible exceptions that I could find.  Not sure if I fixed the exact issue you saw (could not reproduce it).  Also added option to developer tools to reset SD card access to simplify testing.

**Comment by cckozie** [comment]
We should look at merging in #1888 with this issue. All exports that allow writing to the SD need to have the same workflow.

**Comment by cckozie** [comment]
This has been fixed from a technology standpoint, but the export to SD card needs some work on the verbiage used to prompt the user through the process when the SD card is not enabled. I'm passing this issue and creating another one to deal with that issue.
