### ISSUE TITLE
Issues with Update Languages

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1642]
It may be appropriate to make this an Epic and create individual issues for each of these:
1. If I ran the Update Languages option from the 3 dot menu and then lose my Internet connection, when I choose a book and then source language to update, the update appears to run but then the icon returns to the circular arrow without giving the user any error message.
2. The English language source takes anywhere from 12 to 55 seconds to run depending on the size of the book. (some) Other languages only take 3 or 4 seconds regardless of book which leads me to wonder whether anything is actually being downloaded.
3. It is ambiguous as to what the status is where there is no icon present on one of the book/language lines/buttons. I think a downarrow icon would be appropriate for any book/language that is now available but has never been downloaded.
   ![image](https://cloud.githubusercontent.com/assets/8171759/19321895/d383b3c0-9084-11e6-8726-031c3f32de51.png)
4. I think the text in this message should read; "Download the updated {language name} source text for {book name}?"
   ![image](https://cloud.githubusercontent.com/assets/8171759/19322054/89013e2a-9085-11e6-9bea-189b0928ce67.png)
5. The reference to "project" in this dialog is confusing. It should read something more like; "Delete the {language name} source text for {book name}? It will still be available for download at another time."
   ![image](https://cloud.githubusercontent.com/assets/8171759/19322216/297a70d8-9086-11e6-9120-66b1bcd00716.png
6. After a Draft source text is downloaded the screen should remain on the Drafts tab rather than returning to the Languages tab.
7. If the sidebar that lists the languages is so narrow that a book name wraps, the status icon is not displayed for that book.
8. If Update Library is run without an Internet connection, there is no warning or error message. It just displays the list of books as though it had actually worked.
9. The icon indicating that the most recent text is on the device should be a filled in checkbox rather than a bookmark.

**Comment by neutrinog** [comment]
@cckozie this entire UI is going away. It will look like desktop.

**Comment by cckozie** [comment]
That may change. We had a discussion over lunch about some of the potential user misunderstandings and other issues about the way it is being done in desktop.

**Comment by klappy** [comment]
No longer relevant with new resource container implementation. Superseded with new UI/workflow.
