### ISSUE TITLE
Inappropriately sized chunk cards

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1643]
In this Jude project many of the chunk cards are significantly larger than they should be. This screenshot is from the verse 5 chunk.
![image](https://cloud.githubusercontent.com/assets/8171759/19322960/f6c7048c-9088-11e6-8136-73c0195808e6.png)

**Comment by neutrinog** [comment]
this is probably because it has a ton of helps. Did you check if that is true?

**Comment by cckozie** [comment]
It wasn't caused by the helps, but has been fixed as of travis build 1164.
