### ISSUE TITLE
Modify the way that the text search works

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1652]
After demoing the text search enhancement to Christine, she would like to see some changes made to the way we implemented it. Those changes would make the search function more similar to the way it is implemented in most browsers. 
1. Do not filter out the chunks that do not contain the searched for text.
2. Add up/down or next/previous clickable icons to allow the user to move to the next/previous hit.
3. Display the total number of hits found in the text being searched.
4. Remember whether the user selected to search in the source text or the target text, and default the selection dropdown to that option the next time search is invoked.

**Comment by cckozie** [comment]
There are a couple issues here:
2. I wasn't very clear on what I meant by "next hit". I actually meant next/previous chunk with a hit. When there are chunks that have several hits within, it makes it cumbersome to get to the next chunk with hits.
4. It looks like the app always defaults to searching the source regardless of any previous search actions.

**Comment by PhotoNomad0** [comment]
Changed to step by chunks.

**Comment by cckozie** [comment]
Stepping by chunks now works.
Search by source or translation option now defaults to last used.
But all highlighting should be in yellow. It looks like the first hit in the chunk is now highlighted in blue.
