### ISSUE TITLE
short term fix to question chunks numbered by verse

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#1657]
see https://github.com/unfoldingWord-dev/ts-requirements/issues/190 for a description of the issue and the short term solution.

**Comment by cckozie** [comment]
It looks like only the first question for each chunk is being displayed.

**Comment by neutrinog** [comment]
@cckozie you'll need to provide an example. I'm seeing all the questions show up.

**Comment by cckozie** [comment]
It looks like this may have changed in the latest build, but there is still a problem with resources.
I created a new project for 2Th with English ULB as the source. 
When the project opened, I see only Notes for chapter 1, chunk 1 although there are also Words for this chunk. After scrolling down and up a couple times, I now see both Notes and Words for this chunk.
When the project opened, I see Notes and Words for the next few chunks, although there are also Questions for these chunks. After closing and reopening the project I now also see the Questions.

**Comment by neutrinog** [comment]
Try that. There was a lot of noise e.g. things telling the list to re-render more often than was needed. I tested it on 2 Th and it seems to be working well now.

**Comment by cckozie** [comment]
It is definitely better now. The resource cards appear blank for a couple seconds when the project is first created, but it looks like all of the tabs then show.

**Comment by cckozie** [comment]
I don't know if this is related or not, but I'm not seeing any Words in Psalms.

**Comment by neutrinog** [comment]
FYI: The slight delay of the resources being shown is because they are being loaded in a sub-task so that the rest of the screen does not have to wait to load. It also keeps the scrolling from getting bogged down.

**Comment by neutrinog** [comment]
@cckozie I cannot reproduce the words missing in Psalms.
They take a bit longer to load but they do eventually show up. I see notes, words, and questions in chapter 1 chunk 1 in Psalms ulb.

**Comment by cckozie** [comment]
@neutrinog This is interesting. On my Nexus running 5.1.1 I've waited for 10+ minutes and they are still not showing. On my LG running 5.0.2 they appear in Psalms after a few seconds.
On my Nexus I do see Words in Numbers, but I don't see them on my LG. Very strange!

**Comment by cckozie** [comment]
After more testing on 3 devices, it appears to be somewhat random. The info above for the Nexus and LG holds true after closing and reopening both the app and the projects. In other instances, when the project is created the Words may be missing and not appear until after I close and reopen the project. On others, they do appear after a few seconds. Doesn't seem to follow any particular pattern.

**Comment by neutrinog** [comment]
@cckozie I tried loading numbers on my LG as well. Everything works for me. In all your tests are you using English ULB?

**Comment by cckozie** [comment]
Yes

**Comment by neutrinog** [comment]
@cckozie fyi the original purpose of this issue has been fixed. Which is mildly related to https://github.com/unfoldingWord-dev/ts-android/issues/1865.

**Comment by neutrinog** [comment]
just finished refactoring a ton of the review mode code.

**Comment by cckozie** [comment]
I don't know if this is the same or related, but I created a new issues #1967 which has similar symptoms. I'm going to leave this open until that one is resolved.
