### ISSUE TITLE
the app runs slowly on Android < 5.0

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#1658]
@neutrinog commented on [Wed Oct 26 2016](https://github.com/unfoldingWord-dev/ts-desktop/issues/872)

This is very likely due to file i/o operations. The app has to copy all the packaged resource containers onto the device the first time the app is run. Then the first time you open a project it has to extract the related resource container(s). Lastly, on subsequent project opens the app still has to load the yaml and json from the container. 

> Note: The yaml library we are using is known to be rather slow.

**Comment by PhotoNomad0** [comment]
@neutrinog - think this was an Android Studio quirk.  When debugger disconnected the problem went away.  After rebooting PC, even with USB debugging it runs much faster.
