### ISSUE TITLE
Allow importing of local resource containers

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#1660]
@cdwhitfield73 commented on [Fri Oct 14 2016](https://github.com/unfoldingWord-dev/ts-desktop/issues/863)

Add UI (potentially in the Import Options Menu) to allow users to provide a local resource container that would then be copied into the Library folder for the app to access.

**Comment by cckozie** [comment]
I have created and imported a resource container. (It's a slightly modified and renamed version of the ULB for 1th. I updated the json.package file with the new name) I now see that it has been added to the resource_container folder on the device, but it is not displayed as a source language option when creating a project for its book. (The same resource container does appear as a source option when tested on desktop)

**Comment by neutrinog** [comment]
@cckozie can you give me the file you imported?

**Comment by cckozie** [comment]
@neutrinog - Here ya go
[en_1th_ulb_ck (1).zip](https://github.com/unfoldingWord-dev/ts-android/files/756049/en_1th_ulb_ck.1.zip)

**Comment by neutrinog** [comment]
This is actually an issue pertaining to https://github.com/unfoldingWord-dev/ts-android/issues/1678.
I'm half done with a fix.
