### ISSUE TITLE
re-organize import menu

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#1661]

**Comment by neutrinog** [comment]
![image](https://cloud.githubusercontent.com/assets/166412/19813816/31131e3c-9cf0-11e6-807d-8d2412da2fe3.png)

**Comment by neutrinog** [comment]
the info button needs to open http://help.door43.org/en/knowledgebase/9-translationstudio in a browser.

**Comment by cckozie** [comment]
The correct page to open is now 
http://help.door43.org/en/knowledgebase/9-translationstudio/docs/3-import-options
