### ISSUE TITLE
Finish migrating app to use resource containers.

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#1662]

**Comment by cckozie** [comment]
I'm not sure that this is the correct issue for this problem, but I don't know where else to put it.
The reference chunk in OBS stories is no longer being displayed. (Looks like they're not in the resource_containers folder)
In V9.0:
![screenshot_2017-01-25-11-04-26](https://cloud.githubusercontent.com/assets/8171759/22301558/228d94f4-e2f1-11e6-996e-0e25b6e3bc65.png)

In V11.0:
![screenshot_2017-01-25-11-08-05](https://cloud.githubusercontent.com/assets/8171759/22301604/394c1e40-e2f1-11e6-8b33-e16c64839ff5.png)

**Comment by neutrinog** [comment]
I think it's being displayed at the bottom of the chapter now.

**Comment by neutrinog** [comment]
chunks are now sorted correctly.

**Comment by cckozie** [comment]
Interesting...
Now it's displayed after the chapter heading in review mode, but at the end of the chapter in blind edit and read mode.
In Andorid v9, it was after the chapter heading in both review mode and blind edit mode, and it was not displayed at all in read mode.
In Desktop v11, it is at the end of the chapter in both review mode and blind edit mode, and it is not displayed in read mode.
In the printed book, it is at the end of the chapter.
In the unfoldingWord app, it isn't displayed at all.
Gonna get Klappy's input on this one. It seems like it should be the same in both review and blind edit mode, just need to decide where.

**Comment by cckozie** [comment]
As of travis build 1134 the Bible reference chunk appears after the story title in all 3 modes.
