### ISSUE TITLE
passages notes are not showing up correctly in 1CH

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#1667]
See the first chunk in 1ch for an example.

The note markup is 
```
<note caller="+" style="f"> <char style="ft">Some versions omit </char> <char style="fqa">The sons of ... </char> <char style="fqa">, but others include this expression. </char> </note>
```
However the message displayed when clicking on the note shows
```
Some versions omit  , but others include this expression.
```

We need to look at the usfm spec to check if this is an issue with the markup or the app. We've seen similar issues before so I suspect this is an issue with the markup.

**Comment by cckozie** [comment]
Desktop displays this note correctly.

**Comment by neutrinog** [comment]
This is fixed, however the syntax is still invalid. The proper formatting of the note should be

```
<note caller="+" style="f"> <char style="ft">Some versions omit </char> <char style="fq">The sons of ... </char> <char style="ft">, but others include this expression. </char> </note>
```

where

* the first occurrence of `fqa` was changed to `fq`
* the last occurrence of `fqa` was changed to `ft`

Until the note syntax is fixed the result will look like

```
Some versions omit "The sons of ... , but others include this expression"
```

instead of 

```
Some versions omit "The sons of ...", but others include this expression
```
