### ISSUE TITLE
Spike: Research how to Implement new workflow for updating sources

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/ts-android#1677]
Research what it will take to implement new workflow for updating sources.

Create tasks and putting them in the Sprint Task Backlog.

**Comment by PhotoNomad0** [comment]
Effort estimate breakdown based on old PPT:

2 - modify update options prompt.  Add link to update options help page.  Add check for apk update.

2 - modify check for new and updated source texts - _it looks like this maps from update source._ 
- Need to add cancel button while updating. 
- Need to add number of items updated to results.  _We don't yet have a way to get that count?  It looks like we just request and overwrite existing data - waiting for response from Joel._

2 - get new target languages.   Need to add cancel button while updating. Need to show results.
- Need to add cancel button while updating. 
- Need to add number of items updated to results.  _We don't yet have a way to get that count?  It looks like we just request and overwrite existing data - waiting for response from Joel._

8 - implement view new and updated sources workflow.  
- Need to create a new dialog as per UI design.  Complicated navigation and filtering rules.
- Need to be able to query resources by either book or language.  
- Need to add search filter on list.  What are the matching rules?  For books, presume case insensitive initial text matching.  For languages, presume case insensitive matching of language name.  _Do we search the english transliteration also?_

3 - need to modify project source language selection dialog - move from two to three sections.

@klappy @cckozie @neutrinog - first pass at breaking this down and points for each piece.

**Comment by PhotoNomad0** [comment]
[Library Update_13.pptx](https://github.com/unfoldingWord-dev/ts-android/files/589785/Library.Update_13.pptx)
