### ISSUE TITLE
Modify update options prompt

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord-dev/ts-android#1690]
Modify update options prompt. Add link to update options help page. Add check for apk update.

see #1677
and unfoldingWord-dev/ts-requirements#189

**Comment by PhotoNomad0** [comment]
Blocked - Waiting for URL for help link.

**Comment by cckozie** [comment]
@PhotoNomad0 The URL is in unfoldingWord-dev/ts-requirements#189

**Comment by cckozie** [comment]
We decided to remove the "takes a while" text from the menu since it is shown on the Updating dialog.
From desktop:
![image](https://cloud.githubusercontent.com/assets/8171759/22345503/f543aada-e3c5-11e6-91f0-6178bc57fbb5.png)
