### ISSUE TITLE
Problem with updateCatalogs not persisting language updates

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord-dev/ts-android#1698]
What I see:  after launching the app I do "Get New Target Languages" and see 27 languages added.  Then I do it a second time and see 0 languages added.  If I exit the app and run "Get New Target Languages" I will again see 27 languages added.  Then I do it a second time and see 0 languages added.

In UpdateCatalogsTask, I call App.getLibrary().index.getTargetLanguages() and save the slugs before the call to App.getLibrary().updateCatalogs().  Afterwards I call App.getLibrary().index.getTargetLanguages() and check to see if any of the language slugs were not present at in the first call.

**Comment by PhotoNomad0** [comment]
@neutrinog 

It looks like these languages are re-add after app starts up and then "Get New Target Languages"  is run.

I/com.door43.translationstudio.tasks.UpdateCatalogsTask: Initial target languages count: 7717
I/com.door43.translationstudio.tasks.UpdateCatalogsTask: Unigue target languages slug count: 7717
I/com.door43.translationstudio.tasks.UpdateCatalogsTask: Final target languages count: 7739

I/com.door43.translationstudio.tasks.UpdateCatalogsTask: New target languages 1: aon-x-woginara
I/com.door43.translationstudio.tasks.UpdateCatalogsTask: New target languages 2: bzf-x-duo
I/com.door43.translationstudio.tasks.UpdateCatalogsTask: New target languages 3: iru-x-nayak
I/com.door43.translationstudio.tasks.UpdateCatalogsTask: New target languages 4: ium-x-lantien
I/com.door43.translationstudio.tasks.UpdateCatalogsTask: New target languages 5: kfi-x-kukkekuruba
I/com.door43.translationstudio.tasks.UpdateCatalogsTask: New target languages 6: khz-x-kalo
I/com.door43.translationstudio.tasks.UpdateCatalogsTask: New target languages 7: kml-x-lubo
I/com.door43.translationstudio.tasks.UpdateCatalogsTask: New target languages 8: mai-x-dehati
I/com.door43.translationstudio.tasks.UpdateCatalogsTask: New target languages 9: mwq-x-chora
I/com.door43.translationstudio.tasks.UpdateCatalogsTask: New target languages 10: nst-x-shekyu
I/com.door43.translationstudio.tasks.UpdateCatalogsTask: New target languages 11: nut-x-xuong
I/com.door43.translationstudio.tasks.UpdateCatalogsTask: New target languages 12: pex-x-matsungan
I/com.door43.translationstudio.tasks.UpdateCatalogsTask: New target languages 13: qaa-x-0d6670
I/com.door43.translationstudio.tasks.UpdateCatalogsTask: New target languages 14: qaa-x-1bd91c
I/com.door43.translationstudio.tasks.UpdateCatalogsTask: New target languages 15: qaa-x-38ffdc
I/com.door43.translationstudio.tasks.UpdateCatalogsTask: New target languages 16: qaa-x-5aa27b
I/com.door43.translationstudio.tasks.UpdateCatalogsTask: New target languages 17: qaa-x-731b78
I/com.door43.translationstudio.tasks.UpdateCatalogsTask: New target languages 18: qaa-x-7bba3f
I/com.door43.translationstudio.tasks.UpdateCatalogsTask: New target languages 19: qaa-x-b8828c
I/com.door43.translationstudio.tasks.UpdateCatalogsTask: New target languages 20: qaa-x-cf4e7c
I/com.door43.translationstudio.tasks.UpdateCatalogsTask: New target languages 21: qaa-x-d03abb
I/com.door43.translationstudio.tasks.UpdateCatalogsTask: New target languages 22: qaa-x-ea4c5a
I/com.door43.translationstudio.tasks.UpdateCatalogsTask: New target languages 23: qaa-x-ff419b
I/com.door43.translationstudio.tasks.UpdateCatalogsTask: New target languages 24: sps-x-bubuka
I/com.door43.translationstudio.tasks.UpdateCatalogsTask: New target languages 25: tel-x-bestalu
I/com.door43.translationstudio.tasks.UpdateCatalogsTask: New target languages 26: tel-x-yauedhi
I/com.door43.translationstudio.tasks.UpdateCatalogsTask: New target languages 27: tis-x-abra

**Comment by PhotoNomad0** [comment]
This may not be a problem anymore.

**Comment by neutrinog** [comment]
Correct. This issue has been resolved recently. There was a bug in the insert commands.
