### ISSUE TITLE
Verse markers have disappeared

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1705]
I was testing on issue 1659. I imported the 3 projects, did a print, then I exported the project to USFM and noticed that there were no verse markers in the file. Looked back at the project and saw that they were missing there too. 
![screenshot_2016-11-18-15-36-22](https://cloud.githubusercontent.com/assets/8171759/20447572/3dead2f6-ada5-11e6-9a8f-ebbb2ca73e2b.png)

**Comment by cckozie** [comment]
In other projects they show only as \v n, and never as the draggable drop icons.

**Comment by PhotoNomad0** [comment]
When I look on Door43 (https://git.door43.org/qa4/en-x-demo1_mrk_text_reg/src/master/01/04.txt), there are no verse markers present in the source.

**Comment by PhotoNomad0** [comment]
@cckozie - can you point me to an example where the verses "show only as \v n, and never as the draggable drop icons."?

**Comment by PhotoNomad0** [comment]
@cckozie - I also see an issue when done is selected, text gets changed to a very different chunk.  Very bad user experience.

**Comment by cckozie** [comment]
In previous versions tS automatically inserted any missing verse markers (initially there wasn't the ability to type them in), so that is the behavior I was expecting.

**Comment by PhotoNomad0** [comment]
@cckozie - thanks, will check into it.

**Comment by cckozie** [comment]
This is fixed in build 146.
