### ISSUE TITLE
Unusual result after importing a USFM file

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1716]
I imported this USFM file. Everything was as expected (verses 1 and 2 missing) except that when I scrolled down to chunk 15, it was showing the verse markers as \V n instead of the teardrop icon. After closing and reopening the app it looked good. This seems to be intermittent since additional imports of the same file sometimes gave me the "problem" results above, and sometimes everything was correct.

[php_usfm_NoV.usfm.txt](https://github.com/unfoldingWord-dev/ts-android/files/632539/php_usfm_NoV.usfm.txt)

![screenshot_2016-12-06-06-55-02](https://cloud.githubusercontent.com/assets/8171759/20906421/9a4dd442-bb0d-11e6-86c4-3bfe37be3264.png)

**Comment by PhotoNomad0** [comment]
@cckozie @neutrinog - I could reproduce this initially, but when I added logging it started rendering correctly.  It appears to be an artifact of the switch to background rendering.  How it is supposed to work is that the target is preloaded with raw text and then when the render completes it is replaced with the rendered text.  But for some reason it doesn't always redraw.  Appears to be a timing issue.  Looking into this.

**Comment by cckozie** [comment]
This appears to be fixed in travis build 1164
