### ISSUE TITLE
There should be a dialog that warns users that they are importing a project that already exists

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1762]
Something similar to
![image](https://cloud.githubusercontent.com/assets/8171759/22212784/931996e6-e157-11e6-85ad-df52d40119bb.png)
Currently it just does the merge and then informs user if there were conflicts. The user may regret having done the merge but has no way to stop it.

**Comment by cckozie** [comment]
It looks like the warning now only appears if there will be a merge conflict. The user should be warned regardless of whether or not there is a conflict because he may have accidentally chosen the wrong file to import. The should first be warned that the project exists, and then if there are conflicts detected, warned about that.
On desktop, the user is warned about the existing project (see screenshot at top of this issue), and when the Merge option is selected, the merge is performed. If conflicts were detected during the merge they received a message like this:
![image](https://cloud.githubusercontent.com/assets/8171759/23225419/79992288-f8f7-11e6-8409-ee5b10fb18a3.png)
I'm checkin with Christine to get her input on the desired workflow/messages.

**Comment by cckozie** [comment]
We need input from Christine on the verbiage and workflow for the various scenarios of conflict/no conflict.

**Comment by cckozie** [comment]
Current conflict dialog
![screenshot_2017-03-13-14-48-24](https://cloud.githubusercontent.com/assets/8171759/23967877/9dea7356-098e-11e7-9d8e-141b35b3e331.png)

**Comment by cckozie** [comment]
Modify the workflow when importing a project that already exists on the device with no shared history to display a dialog before executing the import similar to the screenshot from desktop in the first comment on this issue . Also, when conflicts will be created by the import, add the phrase "with differences in some chunks" after the word "locally" in the verbiage.

**Comment by PhotoNomad0** [comment]
Changed merge conflict dialog to read like "Project Already Exists" dialog above.  Added merge conflict summary dialog.

**Comment by cckozie** [comment]
This is looking much better now, but there should be a couple changes on the summary dialog. Please change the heading to "Merge Complete" and the first sentence to "The projects have been merged."
![screenshot_2017-03-27-09-02-02](https://cloud.githubusercontent.com/assets/8171759/24365381/5c193722-12db-11e7-8e9a-e1bcf66f82a3.png)
