### ISSUE TITLE
When importing a project that causes a conflict, there is no import successful message displayed

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1763]
A success message is displayed at other times when importing a project file, but not if the import causes a conflict. When the user clicks OK on the message indicating that there were conflicts, the app takes them immediately into the project.

**Comment by PhotoNomad0** [comment]
@cckozie - not sure what to do here in a sense the import is not yet successful until the user completes the merge.  We could add a success message box before the merge conflict needs to be resolved message box, but it seems to add an unnecessary box to acknowledge.  Maybe if we just changed the verbiage on the merge conflict message box?

**Comment by cckozie** [comment]
@PhotoNomad0 Yes, you are correct. Since we automatically open it if there were conflicts, the success message is irrelevant. This should not be a problem after #1762 is implemented.

**Comment by PhotoNomad0** [comment]
@cckozie - nevermind - I can see now that there are some problems that need cleanup.  Like there is no way to cancel the merge.
