### ISSUE TITLE
Should be able to change the name and location of project file being exported

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1764]
Currently the system just names it and puts it where it wants. The user should be able to specify both the name and location that the file is saved to.

**Comment by cckozie** [comment]
This would also make it more consistent with the way we hand exporting usfm and pdf.

**Comment by cckozie** [comment]
There are a few questions I have concerning how we have implemented this and am waiting for feedback from Christine on them.
1. I believe that we should no longer prepend a timestamp to the default file name. 
2. If a file already exists with the name chosen by the user, we should warn the user of that conflict.
3. If the file already exists we should give the user the same options he would get when copying and pasting a file using an Android file manager.
![screenshot_2017-02-23-15-34-17_960](https://cloud.githubusercontent.com/assets/8171759/23314520/f6b40602-fa87-11e6-89e6-bcb4ce6ea73f.png)

**Comment by cckozie** [comment]
As outlined above, please remove the timestamp from the default project file name displayed to the user. If the file name the user specifies already exists in the selected folder, display a warning dialog similar to above with these changes:
Heading: Overwrite file?
Text: As above, but remove the second and third paragraphs (source and destination)
Remove the Apply to all radio button
Otions: Cancel, Rename, Overwrite
Cancel returns user to Upload/Export menu
Rename returns user to file naming dialog
Overwrite does it

**Comment by ChrisJarka** [comment]
I agree with most of what Kos has in his comment above. Here are just two thoughts.

How about instead of:
The same filename exists. Do you want to overwrite _filename_?
Have this:
Notice: The same filename exists. Do you want to rename or overwrite the existing file?

And then...
It might be nice to see what is already there and a date of the file. Something like:

Existing file: name only (no directory tree)
Size:
Date:

**Comment by cckozie** [comment]
If Christine's second suggestion, show existing file info, is going to significantly delay getting the new warning dialog completed, we'll create a new issue for that for implementing that part later down the road.

**Comment by PhotoNomad0** [comment]
@cckozie - will take a look to see what it will take to get file size and date.  That part is a bit complicated for the SD card.
