### ISSUE TITLE
Project file names are obscured when choosing a project file to import

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1765]
The system obscures the actual file name by replacing it with the project name. If the user has multiple similar projects (as could easily be the case when merging offline), the only way the files can be distinguished is by a timestamp, but the timestamp is in a different format than what is displayed when doing the export.

![screenshot_2017-02-17-11-48-08](https://cloud.githubusercontent.com/assets/8171759/23076691/1338f660-f507-11e6-8648-7463425d3e9d.png)

**Comment by PhotoNomad0** [comment]
@neutrinog @cckozie - How should we make this look?

**Comment by cckozie** [comment]
@PhotoNomad0 Just show the full file name so that the user can find it using the name they gave it when they exported it or copied it onto their device.

**Comment by PhotoNomad0** [comment]
@neutrinog - does this sound OK to you?  You spent a lot of time getting this appearance.
