### ISSUE TITLE
Problem with wrapped text in chunk headers

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1776]
![screenshot_2017-01-25-10-59-06](https://cloud.githubusercontent.com/assets/8171759/22306125/9e827cf2-e303-11e6-9060-3db41aea6983.png)

**Comment by cckozie** [comment]
The same issue exists in Bible books when the target font is larger than "normal".

**Comment by cckozie** [comment]
In desktop we do not change the size of the text in the headers so this is not a problem.

**Comment by neutrinog** [comment]
removed the text sizing.

**Comment by cckozie** [comment]
Much better, but still truncating bottom of below the line text.
![screenshot_2017-02-24-10-53-11](https://cloud.githubusercontent.com/assets/8171759/23311497/ed846cb8-fa7b-11e6-8845-f27c4cfb3f1e.png)

**Comment by cckozie** [comment]
Much better but below the line characters are still getting truncated.
![screenshot_2017-02-24-11-29-24](https://cloud.githubusercontent.com/assets/8171759/23311617/557da21c-fa7c-11e6-81ee-b591ed9212b2.png)
