### ISSUE TITLE
Blank screen displayed for several seconds when creating a new project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1804]
After selecting the desired source on a new project, main window goes blank for several seconds with no indication that anything is happening. In creating a Romans project it was blank for 7 seconds. When creating a Psalms project it was blank for 17 seconds. These timings were done on the LG tablet that I was given by WA. There should be either a spinning wheel or dialog indicating that the project (or source language or whatever) is being loaded so that the user doesn't assume the app is hung.

**Comment by PhotoNomad0** [comment]
Good suggestion.

**Comment by cckozie** [comment]
looks good in 1170
