### ISSUE TITLE
Resources should not be displayed when the UDB is the source text

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1813]
Per Christine. Desktop v11 was changed to work that way.

**Comment by neutrinog** [comment]
@cckozie it's displaying the resources based on what it's finding in the api. If we really don't want to display the resources then the api needs to be updated.

**Comment by klappy** [comment]
If the API is updated, how will that affect Desktop? Also, how much effort would it take to address it via API vs addressing it in Android to match Desktop?

**Comment by neutrinog** [comment]
updating the api should not affect desktop in any way. I'm not certain what would be needed to update the api. I can put in a quick hack to disable everything for UDB, but we really should fix the api at some point, though it may be worth waiting for the next iteration of the api to do so.
