### ISSUE TITLE
Disable selecting resource projects for import from door43

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1824]
Currently Android displays in bold the full book name of a project and the full project name in a much smaller font. Since the tq and tn projects are also displayed with just the book name in bold, it is very easy for the user to not realize that it is resource project and not a text project. When a user chooses to import a resource project a message is displayed that just states "The translation could not be restored". It would be nice if the projects that are not importable into Android would be grayed out/disabled to prevent the user from choosing them. It would also be good to add the word "Notes" or "Questions" to the book name in bold so it would be easy to determine why they can't be imported.
![screenshot_2017-02-10-12-20-17](https://cloud.githubusercontent.com/assets/8171759/22838578/6eda3cf8-ef8b-11e6-9a7f-5036efc9f787.png)

**Comment by PhotoNomad0** [comment]
Work items I see in here
- Grey out projects that are not importable.
- Disable projects that are not importable.
- For non-importable projects, add the word "Notes" or "Questions" to the book name in bold

**Comment by PhotoNomad0** [comment]
From John Wood: 
Bruce, I think a warning like that for unknown names would be great, coupled with tS not importing the project after download if it's not supported. It might be good to be clear about what project types _are_ supported in the message. You might also talk with Jesse about adding a message to gogs on rename that warns the user that renaming a project makes it difficult for some tools to work properly with it.

**Comment by cckozie** [comment]
Please change the "OK" link to "Import". 
I think it is a little confusing the way it is. Does OK mean OK, I've read it and understand? Or does it mean OK, go ahead an import it anyway. I think it requires the user to look at the other option to figure that out. Changing it to "Import" should make it very clear.

**Comment by PhotoNomad0** [comment]
More from John Wood:
 if the name is not standard we could flag a message saying something like, “translationStudio does not recognize the project type from the name of this project. Currently, translationStudio only supports Scripture and Open Bible Stories projects. If this is not one of those types of projects it will not be imported into translationStudio."
