### ISSUE TITLE
Labeling of target cards has changed from v9

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1826]
Below are screen shots from v11 and v9. The project was imported from usfm.
The target card labels should be changed back to the v9 text, as **now it does not show the user the book name once he scrolls down from the top.**
Also note that the book title from the usfm file is displayed in both the title card and as the label on all of the chapter title cards. The last screen shot is from desktop which I think has good labeling on the project title and chapter title cards.
V11
![screenshot_2017-02-10-17-51-54](https://cloud.githubusercontent.com/assets/8171759/22847552/48b1291a-efb3-11e6-881d-31e203fd2b0e.png)

V9
![screenshot_2017-02-10-17-05-07](https://cloud.githubusercontent.com/assets/8171759/22847564/5a5f7e5a-efb3-11e6-8bfb-187defb9d5fe.png)

Desktop
![image](https://cloud.githubusercontent.com/assets/8171759/22847571/69aaad6c-efb3-11e6-976c-8175b6af6972.png)

**Comment by neutrinog** [comment]
@cckozie this changed because before we did not have a translatable chapter title for Bible projects. So we defaulted to using the title of the book instead.
However, now that we have switched to allowing the translation of the chapter title we are using that.

**Comment by cckozie** [comment]
Checking with Klappy.

**Comment by klappy** [comment]
What we are missing is an idea of context, it seems as though we have no indicator of what book we are in once we start scrolling. Showing the book name seems important here. It has more value than the word chapter. So instead of having "Chapter 1:1" having "Philipians 1:1" like it use to is ideal.

**Comment by neutrinog** [comment]
ok it's now using the project title.
