### ISSUE TITLE
ID tags are printed in the TOC when printing projects imported from USFM

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1827]
There is not any way for the user to remove these tags in tS so we shouldn't print them.
![screenshot_2017-02-10-17-47-30](https://cloud.githubusercontent.com/assets/8171759/22848045/354ccb8c-efb7-11e6-953b-6170b5bc8c3a.png)

**Comment by cckozie** [comment]
@PhotoNomad0 It looks like you're stripping these lines out when doing the usfm import. Is that true. What I'm seeing is that the codes are not printed in newly imported projects, but they do still print in existing ones.

**Comment by PhotoNomad0** [comment]
Correct - they were being included in the front matter on USFM import.  Now they are not.
