### ISSUE TITLE
Inconsistencies in update source text process

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1845]
I have seen two different things related to updating source texts that make me go hmmmm.
1) Inconsistent time it takes to download the sources depending and whether it was done within a project or using the new screens to select the source(s) to be downloaded. There's an order of magnitude difference.
2) Inconsistent reporting of how many new and updated source texts are available
The process I use to recreate these results are outlined here:

I was testing the download/update sources functionality. I changed the dates in the package.json file of the en_1th_ulb to make it look outdated, then ran the Update List of Available Source Texts. The success dialog reported 0 new and 0 updated source texts.
I then went into the 1th project and then into the source selection dialog. I clicked on the circular arrow for the English ULB and clicked YES to initiate the download. **The download took 50 seconds and reported that it was successful.**
I changed the dates in the package.json file again, then again ran the Update List of Available Source Texts. It again reported no new or updated sources.
It took me to the screen to select a language to download. I chose English, then NT, then 1th ULB. **The download in this case only took 5 seconds** and reported 3 sources downloaded.

I again changed the dates in the package.json file, then powered off the device, then powered it back on.
I opened tS and ran the Update List of Available Source Texts. Now it reports 75 new and 33 updated source texts available. (I have seen it report 75 new and 33 updated texts before sometimes after downloading the update in a project and then running the update list again. That seems to be somewhat random)

**Comment by PhotoNomad0** [comment]
> I was testing the download/update sources functionality. I changed the dates in the package.json file of the en_1th_ulb to make it look outdated, then ran the Update List of Available Source Texts. The success dialog reported 0 new and 0 updated source texts.

@cckozie - Unfortunately, changing the package.json will not make it look outdated to the app.  The app saves the dates in the internal database to save time.  Opening and rechecking all the package.json files would take too much time on an Android device.  

Taking a look at the updated counts.

**Comment by cckozie** [comment]
OK. Do you do use the db also on the source selection screen to indicate which ones have an update available.

**Comment by neutrinog** [comment]
@cckozie at that point the app will compare the modified date in the db with what's found in the downloaded file.

**Comment by neutrinog** [comment]
This has been fixed.

**Comment by PhotoNomad0** [comment]
@cckozie @neutrinog - it looks like the difference in timing is Translation Words is updated whenever you do download from the source selector dialog.  Is this actually necessary to do here?

**Comment by PhotoNomad0** [comment]
Fixed issue with cancelling initial loading dialog left loading dialog on screen.
