### ISSUE TITLE
failing to download palms ulb

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1854]
Notes
======
failing to download palms ulb (travis build 1164)

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 155
UDID | 3c7d0770c6265875
Android Release | 5.1.1
Android SDK | 22
Brand | google
Device | flo
Log history
======
```java
2/17/17 9:43 AM  E/DownloadSourcesDialog: Download failed: en_psa_ulb
     

```

**Comment by cckozie** [comment]
I went into the resources container folder and deleted the English ULB, then retried the download. This time it succeeded.

**Comment by neutrinog** [comment]
@cckozie we can't really reproduce it then. All the downloads work fine for me. Can we close this for now then next time if this happens make a copy of the resource container first and attach it to the issue.

**Comment by cckozie** [comment]
@neutrinog Sure. I'll close it pending any more issues. I did see that problem several times, but not in the last few builds, so hopefully it's fixed.
