### ISSUE TITLE
New source text upload - English text errors

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/ts-android#1876]
I just updated the source text in version 11 build 153 and the text for EN-ELB (Galatians specifically) is not rendered correctly.

![screenshot_2017-02-21-08-19-33 1](https://cloud.githubusercontent.com/assets/9850185/23166588/34fa0234-f80f-11e6-93d8-d2e163322dfc.png)

**Comment by cckozie** [comment]
No longer a problem with Travis build 1346
