### ISSUE TITLE
In project review mode a single card takes up the entire display window

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1898]
![screenshot_2017-02-24-11-54-18](https://cloud.githubusercontent.com/assets/8171759/23312552/d2c82730-fa7f-11e6-8d47-81d42bb36b78.png)

**Comment by PhotoNomad0** [comment]
@cckozie - this looks like a ts-desktop screen capture.  Cannot reproduce the behavior.

**Comment by cckozie** [comment]
It's definitely not a desktop screen capture. Top bar and Android bottom bar icons are not on desktop. Tried it again with another project using Travis build 1220 and got the same result.
![screenshot_2017-02-28-10-57-43](https://cloud.githubusercontent.com/assets/8171759/23415577/4462f8fc-fda5-11e6-8e7a-bcd0d1638096.png)

**Comment by PhotoNomad0** [comment]
@cckozie - sorry my goof.  Didn't recognize it was the review screen.

**Comment by cckozie** [comment]
This issue has been fixed. I have written up two other issues dealing with project review mode.
