### ISSUE TITLE
False hits when searching for double quote

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1921]
Double quotes are found and highlighted, but it looks like it is finding false positives in every chunk.

**Comment by PhotoNomad0** [comment]
@cckozie - interesting problem here, because we initially search the unrendered text (USX or USFM).  This is because rendering a whole book to search for text could take a long time.  And USX has lots of formatting characters that are not displayed.

**Comment by cckozie** [comment]
@PhotoNomad0 Are you saying that you can't make this work as expected without significantly degrading performance?

**Comment by PhotoNomad0** [comment]
@cckozie - looking to be more creative.  Have a couple things to try.

**Comment by PhotoNomad0** [comment]
@cckozie - the source text contains things such as:

<verse number="1" style="v" />

What I am thinking is if we find a match in the source, that we render the text and double check.  This will only significantly slow search down in a few cases, but reduce false positives overall.

**Comment by cckozie** [comment]
@PhotoNomad0 Sounds like a likely good solution to me. Worth a try.

**Comment by cckozie** [comment]
I did a search in the source of 1ch for the double quote. tS indicated Found in 63 chunks. I clicked the downarrow to navigate to the first chunk with the hit. No hit was seen on the display or in any chunks that were partially viewable. I repeated clicking the down arrow 5 more times before I saw a chunk that was showing double quotes.

**Comment by PhotoNomad0** [comment]
@cckozie - nuts - you found another special case - when the search string is in a note.
