### ISSUE TITLE
when viewing vertically I see text
but when vie...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1937]
Notes
======
when viewing vertically I see text
but when viewing horizontal I see no text
this is true for all three views

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 156
UDID | 6b8537242b5c9d0d
Android Release | 6.0
Android SDK | 23
Brand | lge
Device | p1

**Comment by cckozie** [comment]
I think this was on my phone
