### ISSUE TITLE
started clean (no tS folder)  created Psalms pr...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1954]
Notes
======
started clean (no tS folder)  created Psalms project. I select English ulb as source, click Confirm, and it comes back to source selection screen

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 158
UDID | 3c7d0770c6265875
Android Release | 5.1.1
Android SDK | 22
Brand | google
Device | flo
Log history
======
```java
3/7/17 3:52 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_psa_text_reg
3/7/17 3:52 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_psa_text_reg
3/7/17 3:52 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_psa_text_reg
     

```

**Comment by cckozie** [comment]
Closing cuz we don't think it's worth any more work.
