### ISSUE TITLE
Cannot create a Psalms project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1955]
Travis build 1256
I started clean by renaming the main translationStudio folder. Did the install, then created a Psalms project selecting English ULB as the source. After selecting it and clicking CONFIRM, it just takes me back to the mostly blank screen with the folder icon to select a source. Same thing happens with the UDB, but not the foreign languages. If I add ULB after a foreign language the entire screen goes blank except for the green top and bottom bars.

**Comment by neutrinog** [comment]
also cannot reproduce this. Did a clean install and it worked perfectly.

**Comment by neutrinog** [comment]
@cckozie I still haven't reproduced this. Are you still seeing this?

**Comment by cckozie** [comment]
@neutrinog No, we talked about this briefly after the standup yesterday and I suggested that I'll just keep the renamed folders in case we get reinterested in it later.
