### ISSUE TITLE
scrolled in project and while the spinners were...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1966]
Notes
======
scrolled in project and while the spinners were still going I clicked on the other source language. got the app crashed message, but it returned me to the home screen instead of the what were you doing screen

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 158
UDID | a4b66484d349dee1
Android Release | 5.0.2
Android SDK | 21
Brand | lge
Device | e9wifi

**Comment by PhotoNomad0** [comment]
Could not reproduce this fail.

@cckozie - weren't you going to park this one?
