### ISSUE TITLE
crash opening project

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1969]
Notes
======
crash opening project

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 158
UDID | 1f834090ae6cd47a
Android Release | 5.0.2
Android SDK | 21
Brand | lge
Device | e9wifi
Log history
======
```java
3/8/17 10:57 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_mat_text_reg
3/8/17 10:57 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_mat_text_reg
     

```

**Comment by PhotoNomad0** [comment]
@cckozie - are you auto-closing my issues?

**Comment by cckozie** [comment]
Not on purpose. Sorry.
