### ISSUE TITLE
Support Content Chunking

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-android#198]
It would be great if tS could support a "chunking" mode, that allows the user to arbitrarily set divisions (equivalent to \s5) in the source text and then use those as their frames when translating.

**Comment by neutrinog** [comment]
meaning they would be able to re-define the source frames?

**Comment by jag3773** [comment]
Correct.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer

**Comment by neutrinog** [comment]
It might be better to just allow them to split it up by dragging a marker... Like the verse markers. The less code a user has to enter the better.

**Comment by neutrinog** [comment]
Do we have a use case for this? e.g. will they be able to customize the chunks for obs or Bible projects? Doing so will pose problems when trying to merge things together.

**Comment by jag3773** [comment]
Not implemented.
