### ISSUE TITLE
Footnote - UDB

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/ts-android#1993]
As an end-user I would like to see the footnote icon when there is a footnote in the UDB. (Just like how it shows in the ULB.) 

This icon should show in the UDB both when it is being used as a resource and as a source text.

See also - https://github.com/unfoldingWord-dev/ts-desktop/issues/1121

**Comment by cckozie** [comment]
Footnotes in the UDB are being displayed.
CJ was thinking in terms of when the UDB was displayed as a resource, but since we don't do that, I'm closing the issue.
