### ISSUE TITLE
Unrecognized characters on source selection screen

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1995]
This is on a Lenovo HGE
![screenshot_2017-03-15-11-24-58](https://cloud.githubusercontent.com/assets/8171759/23959284/c728f0f6-0972-11e7-9105-ddc9b4679c0f.png)

**Comment by cckozie** [comment]
This appears to be device dependent and not OS version dependent.
Lenovo has the issue at 5.0.1
Moto X has the issue at 5.1
NeuTab has the issue at 5.1.1

Chromo does not have the issue at 4.4.2
LG does not have the issue at 5.0.2
Nexus does not have the issues at 5.1.1

**Comment by PhotoNomad0** [comment]
@neutrinog - do we have a font that would support all these characters?

**Comment by neutrinog** [comment]
@cckozie @PhotoNomad0 I updated the dialog to use the source font when rendering the text. However, I just checked all the fonts and none of them support these characters. You'll notice not only are there un-recognizable characters when choosing the source, but source itself has the same problem. Now we just need to find a font that supports those characters.

**Comment by cckozie** [comment]
@neutrinog If this hasn't been fixed, why is it in the QA lane?

**Comment by neutrinog** [comment]
it has been improved (they can change the font) but we need a font that will work for these characters for it to actually be fixed. I'm not a font expert so assign this to someone who is :)

**Comment by PhotoNomad0** [comment]
Ben suggested I ask Richard Mahn about this.  He says that they use Google Noto fonts and have a CSS sheet to map the correct font file based on character code.  It looks like they have a whole bunch of fonts for various languages.  It seems like it would be a major effort to embed all those fonts into the app and then lookup the font to use based on the character codes supported.

**Comment by PhotoNomad0** [comment]
Working on a brute force approach.  Adding fonts for gu, or, and pa (Gurmukhi).

**Comment by PhotoNomad0** [comment]
Of course as source languages are added, will have to add them into the app.

**Comment by cckozie** [comment]
Looks good on the source selection screen and on the source download screens. Missed the source language tab inside of a project.

**Comment by cckozie** [comment]
It is now good on the issues described here, but the custom font is not being used for the source texts themselves. Passing this issue and adding issue #2098 to handle the source texts.
