### ISSUE TITLE
Multiple problems running tS on a phone

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#2018]
Lots of screen real estate problems. Cannot confirm selection of a source text...
![screenshot_2017-03-17-16-21-35](https://cloud.githubusercontent.com/assets/8171759/24063572/5c38f7b0-0b2e-11e7-8702-f75e1cea0526.png)
![screenshot_2017-03-17-16-19-54](https://cloud.githubusercontent.com/assets/8171759/24063577/5f405ab6-0b2e-11e7-8b54-250ae3af5f90.png)

**Comment by cckozie** [comment]
Blank window with project in landscape mode
![screenshot_2017-03-17-16-28-15](https://cloud.githubusercontent.com/assets/8171759/24063802/2b910e3a-0b2f-11e7-91a4-6198fcb46932.png)

Unreadable vertical text
![screenshot_2017-03-17-16-29-01](https://cloud.githubusercontent.com/assets/8171759/24063806/372af5f8-0b2f-11e7-8cc9-8ff557682a62.png)

**Comment by PhotoNomad0** [comment]
I think this is going to be a huge effort.  We are going to have to do a whole UI redesign to support phones.  We need to discuss at standup if this is something we want to invest in right now.

**Comment by ChrisJarka** [comment]
I did some research and found out that the field hardly ever does translation on phones. The majority of Android phones on the field are flip phones according to my sources. 
So, it sounds like this is NOT a 'need'. Perhaps after the release we will hear differently.

**Comment by cckozie** [comment]
Closing this for now.
