### ISSUE TITLE
Problems rendering door43 project list on older devices with small screens

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#2037]
These screenshots came from my Chromo Android 4.1.1 device with a 6 1/2 inch screen. Pretty much the same issue on my phone (Moto X, 5.1)
![screenshot_2017-03-23-15-04-32](https://cloud.githubusercontent.com/assets/8171759/24265657/3f0846b6-0fd2-11e7-84fa-ec472cc2e2ec.png)
![screenshot_2017-03-23-15-10-20](https://cloud.githubusercontent.com/assets/8171759/24265762/9a5496aa-0fd2-11e7-8c56-13bc6550e3d1.png)
![screenshot_2017-03-23-15-05-16](https://cloud.githubusercontent.com/assets/8171759/24265658/3f0ee0b6-0fd2-11e7-9512-bb83ba61e8b3.png)

**Comment by cckozie** [comment]
Much better on my older small screen device, but still not very good on my phone.
![screenshot_2017-03-24-09-47-15](https://cloud.githubusercontent.com/assets/8171759/24299715/174eff60-1078-11e7-9fac-b425664a2b00.png)
![screenshot_2017-03-24-09-53-47](https://cloud.githubusercontent.com/assets/8171759/24299716/18154cec-1078-11e7-83a1-86363a8b2a75.png)

**Comment by PhotoNomad0** [comment]
@neutrinog - Any suggestions how to address this last issue?  I can see doing a custom layout for a small screen.  Use Smaller fonts might work for landscape mode, but I don't see a great solution for portrait mode.  I can play around with wrapping and see what I get.

**Comment by PhotoNomad0** [comment]
Beginning to look like fixing this will open a ton of new issues for supporting super small screens.  Maybe this is a discussion for standup whether this is actually a requirement or if this is an issue for this release.

**Comment by PhotoNomad0** [comment]
@cckozie - made some changes to font size and spacing.  Now have it usable on a small phone screen 800x480 dpi 160.
