### ISSUE TITLE
when updating source translations we need to preserve manually imported sources

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#2063]
@neutrinog commented on [Wed Mar 29 2017](https://github.com/unfoldingWord-dev/ts-desktop/issues/1141)

before the update we can export imported sources to a temp location then import them after the update.

---

@cdwhitfield73 commented on [Wed Mar 29 2017](https://github.com/unfoldingWord-dev/ts-desktop/issues/1141#issuecomment-290184917)

This has already been implemented in Desktop.

**Comment by neutrinog** [comment]
The app will now backup imports to the downloads directory during the app update. Once finished they will be re-imported.

**Comment by cckozie** [comment]
@neutrinog Am I correct in assuming that I'll need a build with a new version of the library to be able to test this?

**Comment by neutrinog** [comment]
correct.

**Comment by cckozie** [comment]
Blocked waiting for build with updated library.
