### ISSUE TITLE
Some of the resources are not being displayed sometimes

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#2064]
Travis build 1344
Created a John project using the English ULB as source and scrolled down to chapter 8, first by clicking on our scroll bar which took me to chapter 7, and then by swiping. When I got to chapter 8 chunk 9, Notes and Questions were displayed, but not Words. I opened the source selection dialog to ensure that I had the latest ULB source, then went back to the project. After waiting for a half minute or so with Words still not showing up, I rotated the device from portrait to landscape, and then the Words tab did get displayed.
![screenshot_2017-03-29-14-10-50](https://cloud.githubusercontent.com/assets/8171759/24472680/31161880-148c-11e7-9790-a8890a7cd87d.png)
![screenshot_2017-03-29-14-11-01](https://cloud.githubusercontent.com/assets/8171759/24472679/311530d2-148c-11e7-92c0-46cff3e8b329.png)

**Comment by cckozie** [comment]
This was experienced in Travis build 1351 on my Lenovo device.
Open 1ch and noticed chapter 1 chunk 1 only had the Words resource and chunk 2 did not have any. Waited for several seconds and still nothing for resources on chunk 2.  (There should be both Words and Notes for both chunks)
![screenshot_2017-03-31-08-39-13](https://cloud.githubusercontent.com/assets/8171759/24553875/54b31250-15f1-11e7-83ee-df5da711d1aa.png)

Rotated the device and now see Words for both chunks. 
![screenshot_2017-03-31-08-39-50](https://cloud.githubusercontent.com/assets/8171759/24553896/67a5b2aa-15f1-11e7-9e11-9a012f2cf135.png)

Closed and reopened the project and still see just Words for both chunks. 
I upgraded my Nexus to the same build and see both Words and Notes in those chunks.
I used a file explorer to go into the resource containers folder and noticed that there was no folder for en_1ch_tn, but there is an en_1ch_tn.tsrc file.
I closed and reopened the project and now see Words and Notes for both chunks. Went back into the resource containers folder and see that en_1ch_tn folder is now there.

**Comment by PhotoNomad0** [comment]
@neutrinog - I also see last behavior on my lenovo.

**Comment by neutrinog** [comment]
I cannot reproduce this on the lenovo.

**Comment by neutrinog** [comment]
I added some better error logging to this. I still cannot reproduce or determine where this error is coming from. @cckozie try again and let's see if we can get any error logs.

**Comment by cckozie** [comment]
@neutrinog See log in issue #2084

**Comment by PhotoNomad0** [comment]
Testing build 1364 on a couple different devices, not seeing this problem any more.

**Comment by cckozie** [comment]
@neutrinog I've done more testing on this issue and see that the problem exists on all of my devices and many projects, and I think I see some commonalities. It looks like when I open a project where the chunks are small enough that two are displayed, when I pull in the resources tab, the lower chunk's resource data is not getting updated. If I quickly pull in the resources tab, I see the spinning wheel on the top chunk, but no on the one below it. This appears to be the case on all of my devices.

**Comment by neutrinog** [comment]
wheeooo. I've finally discovered and fixed a tiny race condition in all our multi-threaded code. This should fix this issue and others related to things not showing when they should.

**Comment by cckozie** [comment]
Looking good so far. Going to leave it open for more testing on more devices.

**Comment by cckozie** [comment]
Looks good on all devices using Travis build 1379.
