### ISSUE TITLE
add notification when app starts if memory is low

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#2067]
@neutrinog commented on [Thu Mar 30 2017](https://github.com/unfoldingWord-dev/ts-desktop/issues/1144)

Display a dialog when the app starts telling them that their device does not meet the minimum hardware requirements.

Include a checkbox "don't show this again" so they can prevent the dialog from showing every time they start the app.

We should probably display this as soon as possible in case the app actually does crash. Maybe in the SplashScreenActivity either before or after we begin the update app task.

**Comment by PhotoNomad0** [comment]
Here is some example RAM availability on various devices I have.  Note that the one that I have crashes with is the Neutab which only provides the app with 48MB and only has 113MB available on the system.  Note that on all devices about 100MB of the installed RAM is not available to the system.

Lenovo TAB 2 A10-70F Android 5.0.1, API 21
	application memory limit: 128MB
	available memory on the system: 677MB
	total memory on the system (getMemoryInfo): 1.84GB
	total memory on the system (/proc/meminfo): 1.84GB
	low memory threshold on the system: 144MB
	
LGE LG-V700 Android 5.0.2, API 21
	application memory limit: 96MB
	available memory on the system: 231MB
	total memory on the system (getMemoryInfo): 878MB
	total memory on the system (/proc/meminfo): 878MB
	low memory threshold on the system: 120MB
	
ASUS P022 Android 5.0.2, API 21
	application memory limit: 96MB
	available memory on the system: 1.26GB
	total memory on the system (getMemoryInfo): 1.89GB
	total memory on the system (/proc/meminfo): 1.89GB
	low memory threshold on the system: 96MB
	
Samsung SGH-T989 Android 4.0.5, API 15 (Galaxy S2)
	application memory limit: 64MB
	available memory on the system: 307MB
	total memory on the system (/proc/meminfo): 768MB
	low memory threshold on the system: 64MB
	
Softwinner N7Pro Android 4.4.2, API 19 (Neutab)
	application memory limit: 48MB
	available memory on the system: 113MB
	total memory on the system (getMemoryInfo): 400MB
	total memory on the system (/proc/meminfo): 400MB
	low memory threshold on the system: 52.5MB
	
LGE VS980 4G Android 5.0.2, API21 (LG G2)
	application memory limit: 256MB
	available memory on the system: 692MB
	total memory on the system (getMemoryInfo): 1.81GB
	total memory on the system (/proc/meminfo): 1.81GB
	low memory threshold on the system: 192MB

**Comment by neutrinog** [comment]
added a check for minimum cpu of 2 and memory of 100mb. If either of these is not met a dialog is shown to the user before the app starts.

If you click "don't show again" you can re-enable the check by going into settings>advanced.

**Comment by PhotoNomad0** [comment]
@neutrinog - The call I found to use was:

        ActivityManager am = (ActivityManager) this.getSystemService(Context.ACTIVITY_SERVICE);
            int memoryLimit = am.getMemoryClass();

I will check devices on tomorrow to see how the Runtime.getRuntime().maxMemory(); performs.

**Comment by PhotoNomad0** [comment]
@neutrinog @cckozie - I tested this with all my devices.  Some notes:
- it failed the neutab which it should (4 processors but only 48MB available to apps)
- it also failed the LG G Pad 10" tablet which it probably shouldn't (4 processors 96MB memory limit)
- it also failed the Asus ZenPad 8 tablet which it probably shouldn't (4 processors 96MB memory limit)

Recommend lowering the limit to 96MB, since the LG G Pad is one of the recommended devices for MAST and will run the app well.

**Comment by cckozie** [comment]
@PhotoNomad0 Does it run without the warning now on your Asus ZenPad 8?

**Comment by cckozie** [comment]
The message does not appear on my phone.

**Comment by PhotoNomad0** [comment]
No warning on the Asus.  I have the warning on my Galaxy S2 which has only 64MB of RAM available.  No warning on my LG G2 which has 256MB of RAM available.

I think I'll add something to the developers tools to allow you to verify this.

**Comment by cckozie** [comment]
No warning on my phone:
![screenshot_2017-04-05-09-29-20](https://cloud.githubusercontent.com/assets/8171759/24710476/d2f21c66-19e2-11e7-8313-4b60f530f356.png)

**Comment by PhotoNomad0** [comment]
It looks like your phone barely meets the minimum requirements of memory and number of processors.

**Comment by cckozie** [comment]
I am still experiencing problems on my phone, both in getting tS to fully install as well as some screens not functioning properly. Therefore I propose that we add the sentence "You may also experience problems on some phones and other very small devices."
![screenshot_2017-04-06-16-37-14](https://cloud.githubusercontent.com/assets/8171759/24802989/6a312efe-1b6f-11e7-870c-cef3efd63e57.png)

**Comment by PhotoNomad0** [comment]
@cckozie - Maybe change that to "devices with small screens".

**Comment by neutrinog** [comment]
@cckozie I can detect if the device has a small screen. Would it be sufficient to simply additionally display the current message if they have a small screen?

**Comment by cckozie** [comment]
@PhotoNomad0 @neutrinog I'd like to keep "phones" in the text. One of the main issues with my phone probably is related to the screen size, but I seriously doubt that my problem installing the app had anything to do with that. 
I suspect that screen size is probably our only way to "determine" if it is a phone, so we do need to add that to whatever triggers the message. Currently, the message does not appear on my phone.

**Comment by neutrinog** [comment]
done. waiting for the updated source to finish building before I push up the changes.
