### ISSUE TITLE
Search button text does not show in landscape mode when keyboard is visible

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#2074]
This is the case on my NeuTab and my Nexus 7.
![2017_03_31_15 01 11](https://cloud.githubusercontent.com/assets/8171759/24567940/6a47f61a-1625-11e7-9f27-386ce5e9a22e.png)

**Comment by cckozie** [comment]
I'm not seeing a change in travis build 1362 on either device.

**Comment by PhotoNomad0** [comment]
It's working with build 1364 on the LG.  To troubleshoot the other devices I will need one.

**Comment by PhotoNomad0** [comment]
@cckozie - sorry, completely misunderstood the issue here.  I was fixing keyboard not hiding on search issue.

**Comment by PhotoNomad0** [comment]
@cckozie - I don't know the screen pixel counts or the dpi's of your tablets, so this is an estimation for new layout.  Let me know how this works.

**Comment by cckozie** [comment]
Works now with build 172 on all of my devices.
