### ISSUE TITLE
Importing source text process needs to inform the user when error conditions exist

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#2083]
The import source text process should gracefully fail and display a user friendly message on any of the following problem conditions: (there may be more)
1. Missing package.json, toc.yml, or config.yml file
2. Missing required elements in any of those files
3. Invalid data in any of those required elements

If it is not reasonable to catch some or all of these errors during the import process, then they should be caught when the user attempts to use the source text.

**Comment by neutrinog** [comment]
done.

**Comment by cckozie** [comment]
This works pretty well in Travis build 1379, but there needs to be some tweaking of the error messages. I've added a new issue for this, #2096.
