### ISSUE TITLE
Change wording on merge conflicts dialog.

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#2095]
I believe that the count of chunks with conflicts only refers to new conflicts that were created in the current merge. If any of the merged projects had previous conflicts, then the count displayed is not representative of all conflicts. Please change the wording in the second sentence to insert the word "new" between "contain" and "conflicts".
![screenshot_2017-04-06-08-53-14](https://cloud.githubusercontent.com/assets/8171759/24758447/0eb5156c-1aa8-11e7-8b56-0040c0fc7751.png)

**Comment by PhotoNomad0** [comment]
This will be significant effort and will significantly slow down merges by having to get merge conflict counts before and after (this is quite slow on the tablets).  If we do this, I think this should be in a later release.

**Comment by neutrinog** [comment]
@PhotoNomad0 this is just a text change. It's already only giving the number of new conflicts. @cckozie this is ready for review.

**Comment by PhotoNomad0** [comment]
@neutrinog - no this count is the total merge conflicts.  It will include pre-existing merge conflicts.  The task does a very simple count of the chunks with merge conflicts after the merge.
