### ISSUE TITLE
When merging projects causes conflicts, the message always indicates 0 new conflicts

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#2121]
Travis build 1384
I'm not sure when this started happening, but every time I merge projects that cause conflicts, now it reports 0 chunks with conflicts. It doesn't matter if one of the projects being merged has existing chunks or not, or how many new conflicts are created by the merge. If I allow the device to go to sleep, when I awaken it the message has changed to indicate the actual number of chunks with conflicts. When it wakes up it takes multiple clicks to dismiss the dialog.

I wrote this up yesterday but apparently never clicked the submit button. It still behaves the same on build 1385.

**Comment by cckozie** [comment]
This appears to now display the correct number of chunks with conflicts, but the Merge Complete dialog "hangs around". To replicate:
1. Import a project file
2. Import a project file that causes conflicts with 1. and choose the Merge Projects option
3a. If this was the first merge done since starting tS, click Close on the Merge Complete dialog
3b. If this was not the first merge since starting tS, the Merge Complete dialog is not displayed.
4. After the project opens, select Upload/Export on the 3 dot menu
5. Choose Export Project File
6. Choose the folder for the export and click Confirm
7. The Merge Complete dialog is now displayed over the dialog to select the output file name

**Comment by PhotoNomad0** [comment]
Was not saving the state when project editor was hidden - caused it to pop up again when it became visible again.

**Comment by cckozie** [comment]
I am still seeing the same problem in travis build 1406.

**Comment by PhotoNomad0** [comment]
Hmm...it didn't pick up the code changes.  Kicking off a new build.

**Comment by cckozie** [comment]
It is no longer displaying the Merge Complete message when doing the export.

It is still wrongfully displaying 0 chunks with conflicts sometimes. This occurs on first use after the app install. It also occurs on first use after going into Settings and do a Force Stop on tS. On subsequent merges it appears to work properly.

**Comment by PhotoNomad0** [comment]
@cckozie - by force stop, do you mean simulate crash?  When you are editing a project or when you are in home view?

**Comment by cckozie** [comment]
Go into Android Settings/Apps/translationStudio
Options there are Force Stop, Uninstall, Clear Data, and Clear Cache

**Comment by PhotoNomad0** [comment]
OK we are talking in the Android settings.  I like the warning it gives that if you force stop an app you may cause it to misbehave.

**Comment by PhotoNomad0** [comment]
@cckozie 
This is what I am doing to reproduce what you are seeing:
- start with clean system
- do force stop
- do USFM import of project
- do import of project that had a mod
- select merge
- see that I have two merge conflicts
- click OK
- do force stop on app
- start up app
- go into project (no summary as expect)
- got to home
- delete project
- do new USFM import
- do import of project that had a mod
- select merge
- see that I have two merge conflicts
- I do not click ok
- do force stop on app
- start up app
- go into project (no summary as expect)
- go to home
- delete project
- do new USFM import
- do import of project that had a mod
- select merge
- see that I have two merge conflicts
- click ok
- go to home
- do force stop on app
- start up app
- it goes straight into project (no summary as expect)

Not seeing any problems.  Am I missing something in my process?

**Comment by PhotoNomad0** [comment]
Using build 1409

**Comment by cckozie** [comment]
@PhotoNomad0 This may be device dependent, but it consistently fails on my Lenovo using 1409, sometimes even  without doing the force stop between tests.
I am importing tstudio files, although I doubt that matters.
1. Import file 1
2. Import file 2 choosing Merge Projects
When the dialog indicating 0 chunks with conflicts comes up, if I rotate the device it changes to indicate 1 conflict (1 is correct)

**Comment by cckozie** [comment]
It also fails consistently without doing the force stop on my Nexus device running 1409. I am just repeating steps 1 and 2, then deleting the project and repeating again.
I have not seen it fail yet running 1409 on my LG.

**Comment by PhotoNomad0** [comment]
OK, making a fix for possible race conditions due to the asynchronous nature of how we load sources (sometimes unpacking them) and the timings on device rotation.  Making sure that we have all items loaded before showing merge summary.

**Comment by cckozie** [comment]
This 0 conflicts message problem appears to be resolved in build Travis build 1412 so I'm going to pass this issue. There is another problem with the merge complete message being redisplayed that I will write up in a new issue.
