### ISSUE TITLE
USFM import fails to import text

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#2143]
[php_usfm_2_3.usfm.txt](https://github.com/unfoldingWord-dev/ts-android/files/914380/php_usfm_2_3.usfm.txt)
There is text in Chapter 1 chunks 3 and 7 in this file, but no target text is shown after importing.

**Comment by PhotoNomad0** [comment]
Thanks for a new test case for the unit tests.

**Comment by PhotoNomad0** [comment]
OK, found an issue that when final chapters are missing that last chapter read was getting overwritten.  Improved unit tests to catch this.
