### ISSUE TITLE
RTL font is not displayed in printed project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#2156]
https://git.door43.org/qa91/ar_mat_text_ulb

[iar_mat_text_ulb.pdf](https://github.com/unfoldingWord-dev/ts-android/files/917122/iar_mat_text_ulb.pdf)

**Comment by PhotoNomad0** [comment]
@cckozie - this is a messy issue.  Android has a feature that when drawing in the screen, if the current font does not have the language support, then if falls back to using the built in system fonts.

Unfortunately the pdf library has no access to this.  And the new multi-font apparently does not have glyphs defined to Arabic.  Looking at ways to resolve this.

**Comment by PhotoNomad0** [comment]
@neutrinog - Apparently our pdf library does not have dynamic RTL and LTR support.  So even when I do add a supporting font the characters are in reverse order.  itextpdf 5 only has RTL support in PdfPCells.  Unicode class has some detection of text direction, but you would have to create a new table to enclose the text going RTL.  Can we upgrade to itextpdf 7?  It seems to have more RTL support.
