### ISSUE TITLE
Fix the RTL Biblical references in printed OBS 

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#2169]
Testing on Travis build 1422
I am separating this out from issue #2156 
It appears that the reference text is not printed right to left.
Also, the sequence of the numbers in the reference appear to be inconsistent.
On device:
![screenshot_2017-04-18-10-25-15](https://cloud.githubusercontent.com/assets/8171759/25139491/0733368c-2423-11e7-9842-024534179f21.png)

In pdf:
![screenshot_2017-04-18-10-23-40](https://cloud.githubusercontent.com/assets/8171759/25139514/17eb6652-2423-11e7-8e53-b71530d2ed20.png)

**Comment by PhotoNomad0** [comment]
@cckozie - where can I get this project?
