### ISSUE TITLE
App is allowing out of range verse markers.

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#2178]
In v9, when a user had positioned verse markers in a chunk that should not be in that chunk, a message was displayed when the user attempted to mark the chunk as complete, and we didn't allow it to be so marked. In v11, that message is not displayed and we allow the chunk to be marked as complete even when it contains unrelated verse markers. We are allowing both the typing of wrong verse markers as well as dragging them into the wrong chunk.

![screenshot_2017-04-19-10-19-06](https://cloud.githubusercontent.com/assets/8171759/25188098/848b4332-24ea-11e7-8067-7dec3f42c527.png)

![screenshot_2017-04-19-10-33-41](https://cloud.githubusercontent.com/assets/8171759/25188487/dbb03202-24eb-11e7-8784-89f6c70f981c.png)

**Comment by neutrinog** [comment]
@cckozie is it sufficient to display a message "verse marker is out of range" when they attempt to mark it as done?

**Comment by cckozie** [comment]
@neutrinog Yes, I think that is good enough, at least for now.
