### ISSUE TITLE
Do not allow dragging verse markers into the wrong chunk

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#2201]

**Comment by neutrinog** [comment]
@cckozie the app does not allow you to drag verse markers into the wrong chunk. If you do it will automatically remove it.

**Comment by cckozie** [comment]
@neutrinog It did when I snapped this!
![screenshot_2017-04-19-10-33-41](https://cloud.githubusercontent.com/assets/8171759/25246895/c6120900-25ce-11e7-9c44-a4ccffc9498c.png)
But I do see that it doesn't in the latest build. Thanks!
