### ISSUE TITLE
All chunks displayed when in conflicts only mode

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#2255]
#Imported first project
Imported second project
App opened in conflicts only mode but shows all chunks
Switched to review mode then back to conflicts only mode and now it is correct

[en-x-demo1_php_text_ulb-m6.tstudio.zip](https://github.com/unfoldingWord-dev/ts-android/files/1046089/en-x-demo1_php_text_ulb-m6.tstudio.zip)
[en-x-demo1_php_text_ulb-m7.tstudio.zip](https://github.com/unfoldingWord-dev/ts-android/files/1046091/en-x-demo1_php_text_ulb-m7.tstudio.zip)
![screenshot_2017-06-01-17-31-53](https://cloud.githubusercontent.com/assets/8171759/26701783/ff27b30e-46e7-11e7-85c6-815af151369f.png)

**Comment by neutrinog** [comment]
[https://app.zenhub.com/files/24468283/fdd98872-c4cf-43a5-9cea-37c1f02c34b4/download](https://app.zenhub.com/files/24468283/fdd98872-c4cf-43a5-9cea-37c1f02c34b4/download)

[https://app.zenhub.com/files/24468283/494932c3-0801-404e-b5ce-bccd859ee33c/download](https://app.zenhub.com/files/24468283/494932c3-0801-404e-b5ce-bccd859ee33c/download)

**Comment by neutrinog** [comment]
[en-x-demo1_php_text_ulb-m7.tstudio.zip](https://github.com/unfoldingWord-dev/ts-android/files/3015689/en-x-demo1_php_text_ulb-m7.tstudio.zip)
[en-x-demo1_php_text_ulb-m6.tstudio.zip](https://github.com/unfoldingWord-dev/ts-android/files/3015690/en-x-demo1_php_text_ulb-m6.tstudio.zip)

**Comment by neutrinog** [comment]
not reproducible in latest code.
