### ISSUE TITLE
Failed to upload the translation of Matthew int...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#2361]
Notes
======
Failed to upload the translation of Matthew into Afaraf.
targetTranslation: aa_mat_text_reg
--------

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 176
UDID | b159ad65c5ea88a5
Android Release | 8.0.0
Android SDK | 26
Brand | google
Device | walleye

**Comment by neutrinog** [comment]
This has been fixed in https://github.com/unfoldingWord-dev/ts-android/commit/50336976782e40f502155afc7895c96a53216b7a
