### ISSUE TITLE
Version with Spanish and Portuguese resources pre-loaded

### ISSUE THREAD

**Issue by mondele** [unfoldingWord-dev/ts-android#2752]
As a supporter of Bible translation, I want to be able to distribute translationStudio to translators to install on their devices that already includes the Spanish and Portuguese sources. Many of these translators live in areas where Internet is limited or unavailable, and they are unable to install the sources after installation of the app.

**Comment by jag3773** [comment]
tS 12.0 should have these built in @mondele .
