### ISSUE TITLE
Using the back button on my p...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#295]
Notes
======
Using the back button on my phone pops me out of the app rather than taking me to the previous page I was viewing.

Environment
======
version: 2.1.0
build: 56
UDID: dd19773da22f5f
Android Release: 4.4.4
Androind SDK: 19
Brand: Verizon
Device: kltevzw
Log history
======
2/10/15 5:39 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading new projects
2/10/15 5:39 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project rev
2/10/15 5:39 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project phm
2/10/15 5:39 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project jud
2/10/15 5:39 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project jas
2/10/15 5:39 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project act
2/10/15 5:39 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project 2ti
2/10/15 5:39 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project 1ti
2/10/15 5:39 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project tit
2/10/15 5:39 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project luk
2/10/15 5:39 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project rut
2/10/15 5:39 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project obs
2/10/15 5:29 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading new projects
2/10/15 5:29 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project tit
2/10/15 5:29 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project luk
2/10/15 5:29 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project rut
2/10/15 5:29 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project obs
2/10/15 5:26 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading new projects
2/10/15 5:26 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project tit
2/10/15 5:26 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project luk
2/10/15 5:26 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project rut
2/10/15 5:26 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project obs
2/10/15 5:26 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading new projects
2/10/15 5:26 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project tit
2/10/15 5:26 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project luk
2/10/15 5:26 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project rut
2/10/15 5:26 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project obs
2/9/15 8:24 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading new projects
2/9/15 8:24 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project tit
2/9/15 8:24 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project luk
2/9/15 8:24 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project rut
2/9/15 8:24 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project obs
2/9/15 8:24 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading new projects
2/9/15 8:24 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project tit
2/9/15 8:24 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project luk
2/9/15 8:24 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project rut
2/9/15 8:24 PM  I/com.door43.translationstudio.projects.ProjectManager: downloading updates for project obs
2/9/15 6:06 PM [com.door43.translationstudio.projects.ProjectManager]:The notes were not found for project luk
eTranslations/luk/en/udb/notes.json

**Comment by neutrinog** [comment]
will be fixed in https://github.com/unfoldingWord-dev/ts-android/issues/429
