### ISSUE TITLE
Notebook Lines on Right Pane

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-android#30]
I'm pretty sure we want notebook style lines on the right pane, to help indicate that this is where the translation goes.  Visually, it creates a separation between the source and translation.  Apparently, the standard notebook lines are recognizable in most cultures, too.

**Comment by sampeckham** [comment]
Wondering why this was Closed or Some Day? It's a key part of the metaphor, which is only weakened if it's not consistent throughout the app. 

This only seems to be an issue in Chunk Mode, when not directly editing the text. We should be seeing the lines on the card, but they only appear if you tap the edit (pencil) icon.

**Comment by neutrinog** [comment]
Are you referring to the Checking mode instead? The chunk mode does display lines on the card unless it has been marked as done. In the checking mode I purposely left out the lines unless they tap the pencil because technically they cannot edit the text otherwise.
