### ISSUE TITLE
When choosing the "share" opt...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#319]
Notes
======
When choosing the "share" option the screen orientation changes to portrait without regard to the orientation that the device is being used in currently. On a tablet with a keyboard doc, this causes the entire screen to apear sideways.

Environment
======
version: 2.1.1
build: 57
UDID: e6cfa3f4536b34ab
Android Release: 4.4.2
Androind SDK: 19
Brand: asus
Device: K010
Log history
======
> truncated

**Comment by neutrinog** [comment]
This forced orientation is a temporary fix to prevent crashing while due to rotating the p2p sharing.

**Comment by neutrinog** [comment]
Began migrating the p2p client server code into the new task manager.
