### ISSUE TITLE
Add sd card support for export/import in Lollipop

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#356]

**Comment by neutrinog** [comment]
@leoraj if we could also figure out how to export to the external sd card with older versions of android (less then 5.0, greater that KitKat) that would be AMAZING! :)

**Comment by door43app** [comment]
store exported projects in `/translationStudio`

**Comment by PhotoNomad0** [comment]
@neutrinog Coming up empty on SD card writing for later devices.  Solutions involve rooting.  Should be able to support importing though.  Is that worth it?  Or would that just complicate matters?

**Comment by PhotoNomad0** [comment]
Possibilities:  http://stackoverflow.com/questions/26744842/how-to-use-the-new-sd-card-access-api-presented-for-lollipop

**Comment by neutrinog** [comment]
@PhotoNomad0 we can't depending on rooting. Post Kitkat Google provided an api for accessing the sdcard. That link above seems to be talking about this api.

**Comment by neutrinog** [comment]
might we be able to get access to the sd card if we specifically ask the user to choose a directory on the sd card? I don't know if there's an api for that or not, just a thought.

**Comment by PhotoNomad0** [comment]
Had success getting the dialog to pop up to grant access, but I don't have a micro SD card available.  Don't think my wife will like me disassembling her phone to get that one.  

Will pick one up today and give it a try.

As a note this is a very horrible user experience.  Many others have vented frustration about this.

**Comment by PhotoNomad0** [comment]
Wow.  It's a challenge actually getting a path to the actual SD card.
* Environment.getExternalStorageDirectory() returns path to emulated internal storage.
* Some manufacturers mount the SDcard in different locations.

Found some info here:
http://stackoverflow.com/questions/11281010/how-can-i-get-external-sd-card-path-for-android-4-0

**Comment by neutrinog** [comment]
yeah.... that's part of the problem we've experienced in the past. Sure would be nice if there was a standard!

**Comment by PhotoNomad0** [comment]
@neutrinog - On Android 5.0.1, I have had success creating a download folder on an SD card and creating a file in it!  

Still much more work to make it convenient to use.  We end up having to use the URI returned by the permissions activity.  Then using the DocumentFile class we can create folders and files.  We also save this URI for future access.

**Comment by neutrinog** [comment]
great!

**Comment by PhotoNomad0** [comment]
@neutrinog - i think we will need UI changes.  Maybe we have two file export options: "export to downloads folder" and "export to SD card".  We only show the export SD card option if an SD card is installed and mounted on device.  We will also have to do something similar on import since the navigation is through a content uri rather than the normal file system.

**Comment by neutrinog** [comment]
agreed. I'd like to get @sampeckham in on the design of this.
I was thinking something sorta like this:

![screenshot_122215_020817_pm](https://cloud.githubusercontent.com/assets/166412/11967148/73c0e6e0-a8b5-11e5-85cb-9c0060ea2a81.jpg)

so the user can easily select either the phone storage or the sd card.

**Comment by neutrinog** [comment]
this is related to https://github.com/unfoldingWord-dev/ts-android/issues/979

**Comment by PhotoNomad0** [comment]
SD card usage cases:
* Pre-kitkat - SD card folder easily read/writeable and can get path calling getExternalStoragePublicDirectory()
* kitkat - SD card folder only easily read/writeable if default write disk set to SD card?  And then can get path calling getExternalStoragePublicDirectory()
* Lollipop and greater without SD card - emulated card folder easily read/writeable and can get path calling getExternalStoragePublicDirectory()
* Lollipop and greater with SD card - 
  * If SD card is set as default write disk - emulated card folder easily read/writeable and can get path calling getExternalStoragePublicDirectory()
  * If SD card is not set as default write disk - to access SD card you must display the file dialog where user allows app to access the SD card.  When the access is granted using the dialog a special URI is returned to the app that the app needs to use to access the SD card.  To make use of this URI it must be used to create a DocumentFile instance.
