### ISSUE TITLE
Support Key Term Links in Notes

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-android#407]
We need to support Important Term links in the notes, similar to:
the first is `en:bible:notes:gen:03:04` and the second is `en:obs:notes:frames:01-11`.

These look like `en:bible:notes:key-terms:demonpossessed`.  Example in Luke 4:33.

**Comment by neutrinog** [comment]
@jag3773 I looked up Luke 4:33 and the note on the unclean spirit has a link formatted like `[[en:obe:kt:demonpossessed]]`. Is that valid? What is `obe`?

**Comment by jag3773** [comment]
Yes.  All of the key terms are in the obe namespace now.  So you may have
obe:kt: or obe:other: links.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer

**Comment by neutrinog** [comment]
I thought we are moving towards the translationWord terminology. So shouldn't it be `obe:tw:` ?

**Comment by neutrinog** [comment]
@jag3773 **bump** see previous comment
