### ISSUE TITLE
obs 5:10 may have an incorrec...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#414]
Notes
======
obs 5:10 may have an incorrect link in the notes for "the stars in the sky"

Environment
======
version: 2.1.4
build: 78
UDID: c16d19f40cbe170e
Android Release: 4.4.1
Androind SDK: 19
Brand: Samsung
Device: SPH-D710
Log history
======
4/2/15 12:50 PM  W/com.door43.translationstudio.panes.right.tabs.TermsTabFragment: unknown term God the Son
4/2/15 12:50 PM  W/com.door43.translationstudio.panes.right.tabs.TermsTabFragment: unknown term God the Son
4/2/15 12:35 PM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:ta:translate:translatenames
4/2/15 12:35 PM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:ta:translate:translatenames
4/2/15 12:35 PM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:ta:translate:translatenames
4/2/15 12:35 PM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:ta:translate:translatenames
4/2/15 12:35 PM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:ta:translate:translatenames
4/2/15 12:35 PM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:ta:translate:translatenames
4/2/15 12:20 PM  I/com.door43.translationstudio.projects.data.DataStore: clearing the asset cache to support api version 2.9

**Comment by neutrinog** [comment]
@jag3773 can someone look into the notes for this? I suspect it's corrupt at least that was the case in April.
