### ISSUE TITLE
IT resets after screen sleep

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#427]
Notes
======
IT resets after screen sleep

Environment
======
version: 2.1.5
build: 79
UDID: d8d097ad47b4c1ff
Android Release: 4.4.2
Androind SDK: 19
Brand: samsung
Device: degaswifiue
Log history
======
> truncated

**Comment by jag3773** [comment]
I navigated within IT and then screen went to sleep.  When I turned the screen back on i was taken back to the IT list for the frame that I was on.  Reproducible on any frame.

**Comment by neutrinog** [comment]
we might need to fix https://github.com/Door43/translationStudio2/issues/430 before getting to this.

**Comment by neutrinog** [comment]
we'll need to fix this first https://github.com/Door43/translationStudio2/issues/429
