### ISSUE TITLE
App apk Update Feature

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-android#440]
Would be nice to have an app update feature that can check to see if there is a newer version.  This is redundant for the Play store, but if someone installed via an apk would be great to help them update the app itself.

**Comment by neutrinog** [comment]
How do you envision this playing out?
Since we don't want the app to automatically do any network things the user will need to manually request for an update check.

**Comment by neutrinog** [comment]
check if there is an apk update when checking for content updates (google play or possibly github for a newer release).

**Comment by neutrinog** [comment]
Right now this is a feature when a user submits a crash report or a bug report.
