### ISSUE TITLE
Verify Compression for JSON

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-android#441]
The web server is set to compress in-transit JSON payloads that are in excess of 10K if the client accepts that.

1. Does tS support that?
2. Is it working?
3. Should we lower the threshold to 1K?

**Comment by neutrinog** [comment]
@jag3773 we could probably lower the threshold on this. Could you give me an example of a compressed file so I can test it in the app? I'm guessing it'll probably work fine if it's normal server to client compression e.g. gzip.

**Comment by jag3773** [comment]
Any file on the api larger than 10K should be automatically compressed (yes it is the "normal server to client compression").

Try https://api.unfoldingword.org/ts/txt/2/1pe/en/ulb/source.json.

**Comment by neutrinog** [comment]
this is working. Is there a reason why you are just compressing files larger than 10K? Why not compress everything?

**Comment by jag3773** [comment]
Great.  I've lowered the threshold to 1k.
