### ISSUE TITLE
support translating tW 

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-android#451]
Relates to #195.

**Comment by neutrinog** [comment]
@jag3773 you mentioned postponing this so I'll schedule it as so.

**Comment by neutrinog** [comment]
translationWords could fit in the current project model if we make each word a chapter with the term as the title. In each chapter we will have a frame for the definition, definition title, and the term.

> Note: aliases appear to have no use anymore.

**Comment by neutrinog** [comment]
@jag3773 bump

**Comment by jag3773** [comment]
Sounds good.

**Comment by neutrinog** [comment]
@jag3773 how do you want to start a new project? We could add a third step to the new project process. 

* choose language
* choose book
* *new* - choose what to translate

The last step would be a list like the following:

* book
* notes
* questions
* words

choosing book would start a new translation project like we have already and clicking on any of the others would start a new translation project for that type of content.

**Comment by neutrinog** [comment]
or another way (perhaps we could have both) would be once you have opened a translation project you can begin translating the other material by clicking on some item in the menu.

Perhaps adding a new menu item called `translate resources` that would open a dialog where you could choose which resource you wanted to translate.

**Comment by neutrinog** [comment]
@tjklemz @cdwhitfield73 fyi. ^^
We'll schedule to have this implemented in desktop soon. Please provide any input.

**Comment by neutrinog** [comment]
we will not support translating tW in the android app
