### ISSUE TITLE
Export USFM Zipball

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-android#452]
Users should be able to export Scripture as USFM formatted text.  Multiple books should be exportable as a zip file.

Contributor and license information should be included.  Filenames should follow what is seen on https://api.unfoldingword.org/avd/txt/1/avd-ar/.

**Comment by neutrinog** [comment]
more details on exporting can be found at https://github.com/unfoldingWord-dev/ts-requirements/wiki/ts.Translator#exporting-human-readable.

@jag3773 where do you want to store the contributor and license information? Within each USFM file or in a global file?
