### ISSUE TITLE
the key term links are not pr...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#489]
Notes
======
the key term links are not properly loading the chapter and frames.

Environment
======
version: 2.2.0
build: 83
UDID: c16d19f40cbe170e
Android Release: 4.4.1
Androind SDK: 19
Brand: Samsung
Device: SPH-D710
Log history
======
5/29/15 5:13 PM  E/com.door43.translationstudio.projects.ProjectManager: the source languages could not be loaded for the project gen
5/29/15 4:51 PM  E/com.door43.translationstudio.projects.ProjectManager: the source languages could not be loaded for the project gen
5/29/15 4:38 PM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:ta:translate:exclusive
5/29/15 4:38 PM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:ta:translate:exclusive
5/29/15 4:38 PM  W/com.door43.translationstudio.projects.ProjectManager: no chapter or frame exists for that note luk:24:52
5/29/15 4:37 PM  E/com.door43.translationstudio.projects.ProjectManager: the source languages could not be loaded for the project gen

**Comment by neutrinog** [comment]
the chapters and frames need to be loaded after clicking on the link.
