### ISSUE TITLE
KT -> tW

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-android#509]
Instead of Key Terms we should call them 'translationWords' in the UI.

**Comment by neutrinog** [comment]
I've lost count how many times we've changed that :P

**Comment by neutrinog** [comment]
@jag3773 with this change I'm assuming there will be no translation for this in the locale correct? Because it is now a name of something.

**Comment by jag3773** [comment]
Correct.

**Comment by jag3773** [comment]
@neutrinog sorry for the whiplash (again)... as I see that we have "Notes" in the right hand fly out, I think it would better to just use "Words".  This will conserve space for smaller screens as well, and it is translatable.  Sound OK?

**Comment by neutrinog** [comment]
....really? lol.
OK!
