### ISSUE TITLE
the source text is squished

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#512]
Notes
======
the source text is squished to the left.

Environment
======
version: 2.2.0
build: 86
UDID: 7792b4f461ec9d4f
Android Release: 4.4.4
Androind SDK: 19
Brand: Lenovo
Device: A10-70F

**Comment by neutrinog** [comment]
this is a result of changing the fonts

**Comment by neutrinog** [comment]
![screenshot_2015-07-21-17-32-34](https://cloud.githubusercontent.com/assets/166412/8815535/4ef3b02c-2fcf-11e5-9b7b-f5f41a2aa2af.png)

**Comment by neutrinog** [comment]
We've identified the issue as the fonts being used. Here is a list of working and broken fonts

BROKEN:
---
* tuladha jejeg
* Tai Heritage Pro
* scheherazade
* Padauk
* Miao Unicode
* Linux Libertine G Regular
* Linux Biolinum G Regular
* Gentium Plus
* FreeMono Tengwar-embedding
* Doulos SIL Cipher
* Doulos SIL
* Dai Banna SIL Light
* Charis SIL
* Annapurna SIL
* Andika
* Adinatha Tamil Brahmi
* Abyssinica SIL

WORKING:
---
* Sophia Nubian
* Zawgyi-One
* Chiangsaen Alif
* Lanna Alif

**Comment by neutrinog** [comment]
@jag3773 where do you want to go from here?
We could excluded the fonts that do not work, search for fonts that do work, or try to get android to work with what we have (I would not suggest that if at all possible).

**Comment by jag3773** [comment]
Is this an Android version issue or a Lenovo hardware issue?

**Comment by neutrinog** [comment]
good call I just did a test on an emulator and the text is rendering correctly. So quite possibly a hardware issue. Can we have this tested on different devices to see how they compare?

**Comment by jag3773** [comment]
Sounds like this Lenovo is the only one, doesn't it?

**Comment by neutrinog** [comment]
I haven't tested it on any other physical **tablets**. I'd want to do that before coming to that conclusion.

**Comment by neutrinog** [comment]
for now we will default to a working font on this device.
