### ISSUE TITLE
Incorporate tA Text

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-android#549]
We need to incorporate translationAcademy as soon as it is ready.

**Comment by jag3773** [comment]
Demo tA endpoint is at http://td-demo.unfoldingword.org/publishing/ta-en.json.  We are missing some of the metadata at the moment, but that shouldn't be necessary for getting going on this.

**Comment by neutrinog** [comment]
I think that looks good thanks.

**Comment by jag3773** [comment]
Updated JSON is on the #door43-dev channel in Slack.  The structure has changed to represent the TOC more adequately.

**Comment by neutrinog** [comment]
will the ta url eventually find it's way into the api? e.g. in the resource catalog.

**Comment by sampeckham** [comment]
There's a lot of UX questions around this too.

Is this going to appear as a tab in the resource pane?
How does anyone navigate through the content of tA?
How is the language of tA chosen?

**Comment by neutrinog** [comment]
I'm not sure if we will have a tab for ta. We will make it available via links within the other resources. Displaying something from ta should use the same ui as displaying a translationWord or any other resource.
