### ISSUE TITLE
Link Key Terms with Source Key Terms

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-android#55]
We need to provide the ability for translators to link their translations of English key terms with the English key terms themselves.

Potentially this could be a separate story that just lists all the key terms and asks for a translation for them?  Or, maybe this would be a dialog that would show when a key term is touched?

**Comment by neutrinog** [comment]
I think this relates to https://github.com/Door43/translationStudio2/issues/195 .
Are you talking about allowing translators to tag key terms within the translation they are creating, provide some description, then linking that to the English key term?

For linking to work we'll need to have some id that associates key terms in different languages together. The English key term would probably be sufficient for an id. In that case we'll need to add a new **id** field to the key term catalogs.

Then more generically a translator will be able to link their translated key term with any key term in any language, which would effectively link it to all key terms with a matching id.

**Comment by neutrinog** [comment]
this is related to https://github.com/Door43/translationStudio2/issues/374

**Comment by neutrinog** [comment]
we'll let translators translate key terms inline. Then we'll use this to pre-seed the kt projects.
We can also begin tagging key terms in the translation text using usx/usfm.

The usfm syntax is `\k my key term\k*`. The usx syntax is `<char style="keyterm">my key term</char>`. 

> Note: in usx the **char** needs to be placed inside a **para**.

**Comment by neutrinog** [comment]
see http://dbl.ubs-icap.org:8090/display/DBLDOCS/USX#USX-k

**Comment by neutrinog** [comment]
we really some id's on the kt's if possible https://github.com/unfoldingWord-dev/ts-android/issues/466

**Comment by neutrinog** [comment]
this is no longer applicable.
