### ISSUE TITLE
Add footnote support to the app

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#551]
We had this before but disabled it for some reason.
There should be a toggle switch in the ui so translators can switch between passage notes and footnotes.

**Comment by ChrisJarka** [comment]
I am looking at some of the footnotes in tS 3.0.0. build 101. In Acts 8:37 and Acts 15:33 the source text that has a footnote is highlighted. In Romans 16:23 the source text is not highlighted. 
It looks like a footnote marking in the usfm file determines the highlighting?

Here is Act-08 in epad
\v 37 \f + \ft Some ancient authorities add, in whole or in part, v. 37.
\fqa Philip said, "If you believe with all your heart, you may be baptized." The Ethiopian answered, "I believe that Jesus Christ is the Son of God." \f*
\v 38 So the Ethiopian commanded the chariot to stop, and they went down into the water, both Philip and the eunuch; and Philip baptized him.

Here is act-15 from epad
\v 33 After they had spent some time there, they were sent away in peace from the brothers to those who had sent them.
\v 34 \f + Some ancient authorities insert, with variations, v. 34.
\fqa But it seemed good to Silas to remain there.\f*

Here is Rom-16
\v 24 \f + Some ancient authorities insert here v. 24 \fqa May the grace of our Lord Jesus Christ be with you all. Amen. \ft and omit the like words in v 20.\f*

**Comment by ChrisJarka** [comment]
tS 3.0.0 build 101 does not show footnotes.

**Comment by lrsallee** [comment]
Not sure what is happening, but the Act 18 and Rom 16 notes were missing the "\ft" code at the front of the notes. I added that to EP.

**Comment by neutrinog** [comment]
@ChrisJarka the missing `\ft` code that @lrsallee mentioned above would be the cause of this broken footnote.

**Comment by ChrisJarka** [comment]
How soon will be able to see the changes in tS?

Blessings,
Christine
407-852-5343

**Comment by neutrinog** [comment]
you can see it now if you open `Update Library` from the home screen and then download the English update for Romans. Keep in mind the interface for downloading updates is still a little buggy.
Otherwise the update will be available in the next release (either the 22nd or 29th of Oct)

**Comment by neutrinog** [comment]
I still need to hook up the notes so that you can tap on them to read the note. For now they just show as non-clickable highlighted text.

**Comment by lrsallee** [comment]
If I understand correctly, the current italicized note in the text will only display when someone clicks the link (once activated). Is that right? If so, that's what we want.

**Comment by ChrisJarka** [comment]
In version 2.x the text with the footnote was highlighted in yellow and the footnote appeared when the user tapped on the text.
