### ISSUE TITLE
restore from backups when installing app

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#555]
The app should ask users if they would like to restore from a backup when re-installing the app after it has been uninstalled. It should also ask the user about restoring a backup when they open a project that does not have any translations but for which a backup has been found.

These features should rely on the backups located in the `AppContext.getPublicDirectory()`.

**Comment by neutrinog** [comment]
The backups are being created every 5 minutes by the backup service [https://github.com/unfoldingWord-dev/ts-android/blob/master/app/src/main/java/com/door43/translationstudio/service/BackupManager.java](BackupManager.java). 

> Note: the service only runs while the screen is not sleeping (might change later).

The only known user case for this is when a fresh install of the app is made. e.g. the app was uninstalled and then reinstalled. When the app starts up it will ask the user if they would like to import backed up translations.

Suggestions
--

* Check if a backup exists in the `primaryBackupDir` (see backup manager) in the `SlashScreenActivity` if the app had not previously crashed. If a backup exists for which there is no translation in progress in the app the user should be shown an interface where they can choose to import the backup(s).
* Create a new activity where users will be asked if they want to import the backups. For an example of how the user is redirected to this new activity and then back to the `SplashScreenActivity` take a look at the `CrashReporterActivity`.

**Comment by christianmother27** [comment]
I'm looking at this one.

**Comment by neutrinog** [comment]
We may not need this if we complete #835  . it will depend on the persistence of the external files... E.g. are they deleted after an uninstall.

**Comment by neutrinog** [comment]
closing this because moving the translations to the external files directory will fix this.
