### ISSUE TITLE
Fix navigation tests

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#559]
The [Travis test](https://travis-ci.org/unfoldingWord-dev/ts-android/builds/71616498) on pull request https://github.com/unfoldingWord-dev/ts-android/pull/558 failed. 

You can run the tests locally with `gradlew connectedAndroidTest`. On my machine this runs all the tests correctly including those meant to fail (note: it is generally discouraged to submit code with intentionally breaking tests).  

I suspect the issue resides with the travis configuration, possibly with the ui not being created: `-no-window` ??? I would suggest setting up travis on your fork so that you can tweak and test the travis configuration.

**Comment by gslaughenhaupt** [comment]
It is a UI test meant to be run on a device or possibly an emulator. I will familiarize myself with Travis
