### ISSUE TITLE
Keyterms link (in the source text) not highlighted

### ISSUE THREAD

**Issue by markellishancock** [unfoldingWord-dev/ts-android#564]
It would be good to have the keyterms in the source text to be highlighted by default.  I understand that it can be set on the settings but it would be good to have that as a standard.

**Comment by neutrinog** [comment]
@markellishancock that was the standard but @jag3773 decided to change that I think mostly because we were encountering issues with incorrect key terms mapping e.g. out of context.

**Comment by jag3773** [comment]
Note: not my decision but that of the Notes team(s).
