### ISSUE TITLE
translationWords for APP

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/ts-android#625]
It seems that the tW in the APP are not the same as on Door43. This is also on Slack in the #translationstudio group
 Here is an example:
 I noticed that the website for frame [23-06] has this list of tW shepherds, Bethlehem, Messiah, angel, Master while the app has good news, Bethlehem, Messiah, angel and lord.
 I understand that 'lord' goes to the page that has the same information as 'master' and is the result of the removed pipe in the link.
 The issue is that the key term information on the app is not what the updated information on https://door43.org/en/obe/kt/lord has. The section on 'Translation Suggestions' is missing on the APP page.
 Please also note that the tW 'shepherds' is not showing on the app.

**Comment by ChrisJarka** [comment]
We have also found another issue beyond the APP not having the updated information from the tW page.
 In tN 09-08, the tW (key terms) show 'servant' while the story text has 'slave' and the tW page is titled 'servant' but also describes 'slave.' The website https://door43.org/en/obs/notes/frames/09-08 of that frame has 'slave' as an tW but it is hard coded (syntax is [[:en:obe:other:servant|slave]]).
 This was an issue today when a translator wanted to look up the explanation of 'slave' but did not see 'slave' on the list of tW. It was a moment of confusion when I said to look up servant for the word slave.

**Comment by ChrisJarka** [comment]
Hi Joel,
How do I move the issue from where it is to where it should be?
Also, we are using 2.2.0 build 86.
Blessings,
Christine
407-852-5343

**Comment by ChrisJarka** [comment]
Another issue - frame 40-01
Website has:
mocked, Jesus, crucify, Christ
APP 2.2.2 build 88 has:
crucify, cross, death, Jesus

**Comment by jag3773** [comment]
Relates to unfoldingWord-dev/tools#107
