### ISSUE TITLE
Missing support for 'cl'

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-android#669]
Psalms in Arabic uses the 'cl' USFM code, which does not appear to be supported in tS.

**Comment by neutrinog** [comment]
did you mean USX?
Could you give me a sample passage to look at?

**Comment by jag3773** [comment]
Please see the usfm or usx reference manual for examples. In tS, Psalm 1:1 has this.

**Comment by neutrinog** [comment]
This is for the chapter label. It now displays as bold text.
