### ISSUE TITLE
Unify Output Format

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-android#675]
The DokuWiki vs. translationStudio output format option is confusing and probably unnecessary.  Can we unify to just use 1 format.  What format would that be?

**Comment by neutrinog** [comment]
using the translationStudio format is better for importing to another app. It includes the entire translation history, can package multiple projects into a single export, and maintains a record of source translations used. However this format is only useable to the average user if they import it into the app again.

the dokuwiki format is immediately readable by the user, but is considerably less helpful for exporting projects to another device.

I would suggest using translationStudio as the output and then possibly provide a publish option elsewhere in the app that would spit out dokuwiki if you still want that available.

**Comment by kjhaugh** [comment]
Does the tStudio export format also include the translator's notes? If not, would it be possible to include that for data retention purposes as well?
Ken Haugh

**Comment by neutrinog** [comment]
@kjhaugh  agreed. it does not currently but it definitely should be included in the export.

**Comment by jag3773** [comment]
Note that for Scripture, we will want to support exporting to USFM format.  As an "export" option, USFM should be the default.  For backup purposes, however, I think the tS format would be preferable.  The new UI is seeking to address this issue as well.

**Comment by neutrinog** [comment]
so you're thinking export will be user readable formats and backup will be translationsStudio?

That sounds fine to me. So we'll be using the tstudio format in auto backups, when exporting between devices directly (not manually), and when the user manually performs a backup.
