### ISSUE TITLE
Auto Publish on Upload Level 1

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-android#676]
There are a lot of moving parts here, but the goal is that a tS user can use the publish feature to "automatically" publish to the unfoldingWord catalog.  There are several provisions that need to be accounted for:

1. Nothing currently exists in Door43 for that language and project.
2. The git merge tool is setup to auto merge if no. 1 above is true. (see https://github.com/unfoldingWord-dev/Door43/issues/176)
3. We have some sort of hook or request that we can send to tD to initiate the publishing process.

This is a large task, to be worked on quarter 4.

**Comment by neutrinog** [comment]
@richmahn I believe this is now in your court.

**Comment by richmahn** [comment]
@jag3773 What does "nothing existing" include for #1? What if the language has a repo, but no obs directory? Or what if it has a obs directory but the language content is still a source's content and not modifications have been made? But can we even check the latter?

**Comment by jag3773** [comment]
This issue was moved to unfoldingWord-dev/Door43#303
