### ISSUE TITLE
Need to improve indexer to avoid problems with block sizes.

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#689]
@channel: we may need to make some tweaks to the indexer due to issues with the cluster size in Android. The index currently contains over 62,000 really small files which introduces a lot of overhead because a short json file doesn't come close to filling even a single block. Therefore a 60MB index consumes around 300MB on an android device.

Joel Lonbeck [12:50 PM] 
I'm thinking for each hash in the data directory we could maintain a table of the contained content then organize the content in a number of files (no more folders) that are filled up to some specified size (at least 32KB and up to 1MB)

Joel Lonbeck [12:51 PM]
then when reading the actual content you can use a file pointer to read the appropriate range of data.

Joel Lonbeck [12:53 PM]
indexed content only changes at the hash level .. that is `data/[md5 hash]` so this should not introduce complications in maintaining updating content in the index.

Joel Lonbeck [12:54 PM]
This is something that will need to be fixed within the next 2 weeks so I'd appreciate feedback/ideas.

**Comment by tjklemz** [comment]
Database? SQLite? There would be compression.

What are our memory constraints? Seems like we should be allowed to have up to 1GB in memory. This not true?

**Comment by neutrinog** [comment]
That's a lot of memory, besides I don't think Android would allow a single app to have that much of the system memory. It's been my experience anything over 60MB will cause resources to be re-allocated (read given away) and the app restarted.

**Comment by tjklemz** [comment]
SQLite should not load everything into memory—very few databases do that, viz. Redis, and only for servers with 32GB of RAM.

You should only need one SQLite file/database. You could also create a NoSQL database like MongoDB (whatever the equivalent is for Android), which would play well with the existing JSON.

Simply, if you're trying to optimize space and read and write operations, you're creating a database. Someone's done that. Of course, mobile's a (relatively) new area. But again, huge games run on mobile, so I'm guessing we should be able find a solution. It'd be nice, too, if it was homogeneous with the Desktop version.

(FYI, iPad limits to ~200MB of RAM before force-quitting the app. Just for reference/comparison.)

**Comment by neutrinog** [comment]
the sqlite version of the indexer needs to support retrieving directories (for in the case of chapters).
