### ISSUE TITLE
update backup manager to use new library and translator

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#691]
We need to re-implement exporting for target translations (this **was** in the sharing class). Once the exporting has been implementing we basically just need to switch to using the new classes when checking on languages and projects (noted below).

**Comment by thomas3217** [comment]
Task's involved 

Language - only bakcup translation language.

Projects - change location.

line 143 project manager.

line 158 sharing class.

sharing will be part of the translator.
/*Back burner while deciding which direction to go.*/

backup goes to two locations -- downloads directory and backup directory.
