### ISSUE TITLE
Highlight Active Mode Icon

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-android#731]
We need some sort of indication of what stage/mode you are in. Perhaps highlighting the tab or a color inverse or something.

**Comment by sampeckham** [comment]
This is in the design, just not implemented. 
![screen shot 2015-09-24 at 16 21 41](https://cloud.githubusercontent.com/assets/323212/10077484/5c060346-62d8-11e5-8fdc-a4e1c8e21d53.png)
![screen shot 2015-09-24 at 16 21 33](https://cloud.githubusercontent.com/assets/323212/10077483/5c05eea6-62d8-11e5-9a5e-5c9f099809eb.png)
