### ISSUE TITLE
selecting  en-demo-2 does not actually start a ...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#739]
Notes
======
selecting  en-demo-2 does not actually start a project.

Environment
======
Environment Key | Value
:----: | :----:
version | 3.0.0
build | 95
UDID | e37c929dc01796f
Android Release | 5.0.2
Android SDK | 21
Brand | samsung
Device | gt58wifi

**Comment by jag3773** [comment]
start at 30 seconds on this video and you'll see the issue https://app.testfairy.com/projects/1370638-translationstudio/builds/1816290/sessions/3/?accessToken=0MuAjGhCRzQPQG/oi8yrjtid5JE
