### ISSUE TITLE
Tap to bring in resources

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-android#740]
Similar to the source/draft switch, user should be able to tap on the right to bring in the resources (as well as slide in from the right).

**Comment by sampeckham** [comment]
The mechanism is all there. Works really well. Just needs the content I guess!

**Comment by neutrinog** [comment]
@sampeckham we have the swipe to open resources, but I disabled tapping on the resource card that pokes out from the right in order to open them. I still need to re-enable the tap.
