### ISSUE TITLE
Design backup screens

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#743]
instead of sharing and backup we will just have backup
give an option for online or local backup. online backup is just an upload.
local backup will give options for importing/exporting.

**Comment by neutrinog** [comment]
what's the status on these designs? I'd love to get these tomorrow of possible. Pretty please :)

**Comment by sampeckham** [comment]
See:
https://projects.invisionapp.com/d/main#/console/4494516/111667780/preview

Not sure what further steps there are. The main point here is the language needs to be simple and consistent. I deliberately moved "Import from..." as that is the opposite of Backup. That should go elsewhere and in a different context.

**Comment by neutrinog** [comment]
Agreed. My thought was to place another menu item next to backup that would provide import from the various locations.

**Comment by sampeckham** [comment]
For the import though it doesn't seem to make sense to do this from within an open project. I would imagine this is something for the home screen, possibly even below the list of Projects?

**Comment by neutrinog** [comment]
ah good point.
