### ISSUE TITLE
Add title and reference card for OBS chapters

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#751]
for chapter title and reference we will have a seperate card at the chapter break where users can see the chapter title and reference and be able to translate it. We'll have this in chunk mode and review mode.

**Comment by sampeckham** [comment]
I like this idea. Just wondering how you pick up on people who translate the title right in the main body?

**Comment by neutrinog** [comment]
I think having it as a separate card will give enough of a visual break to keep the translation in the correct card. After all this is how they are translating the frames and if they can't translate the title correctly they probably won't get the frames correct either. It will show up as a warning in the publish interface at any rate.

**Comment by neutrinog** [comment]
I've implemented this in the chunk mode. I'll post a build later today and let people look at it before I do the same for the review mode.

**Comment by jag3773** [comment]
Works for me.

**Comment by jag3773** [comment]
This is still not implemented for review mode.
