### ISSUE TITLE
Remember My Place

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#754]
Notes
======
remember my place setting should take user to the first frame not marked "done" in any given project

Environment
======
Environment Key | Value
:----: | :----:
version | 3.0.0
build | 97
UDID | 3be7663bc980729a
Android Release | 4.2.2
Android SDK | 17
Brand | google
Device | toro

**Comment by neutrinog** [comment]
@jag3773 thoughts? I personally think it should pick right where the user left off.

**Comment by sampeckham** [comment]
@neutrinog Agree the app should open where the user left off. Or the tapping a project should take them to exactly where they left off.

**Comment by jag3773** [comment]
The following scenarios need to be met:

* [ ] User leaves app, come back in, they come back to the same spot they were at before.
* [ ] User leaves app, comes back in, goes to a *new* project, they are taken to their last place in that project

Essentially, there should be an app level and project level "last place".

**Comment by sampeckham** [comment]
By *new* you mean *different* project right? A new project would start at the beginning surely. But otherwise yes correct.

**Comment by jag3773** [comment]
Correct.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer

**Comment by neutrinog** [comment]
yes right now we have project level "remember my place". So we just need to add the app level.

**Comment by PhotoNomad0** [comment]
@neutrinog - I am not finding the project level "remember my place" in chunk mode or review mode.

**Comment by PhotoNomad0** [comment]
@neutrinog i can find it in the settings, but rememberLastPosition() doesn't seem to be used anywhere.

**Comment by neutrinog** [comment]
@PhotoNomad0 there is none. You'll need to create it.

**Comment by PhotoNomad0** [comment]
@neutrinog - when you said 'we have project level "remember my place"' - did you mean we remember the last project?
