### ISSUE TITLE
Remove Verse Numbers

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#755]
Notes
======
remove verse markers from blind draft mode

Environment
======
Environment Key | Value
:----: | :----:
version | 3.0.0
build | 97
UDID | 694f7e286991a5ec
Android Release | 4.4.2
Android SDK | 19
Brand | samsung
Device | degaswifiue

**Comment by neutrinog** [comment]
@jag3773 I think they mean the verse markers in the source. thoughts?

**Comment by sampeckham** [comment]
Verses in general should not be visible for either Source or Translation until the Checking Mode.

**Comment by neutrinog** [comment]
@sampeckham I disabled the verse numbers in the blind draft mode but left them on in the read mode. Do you want the read mode to hide the verses as well? I feel like the read mode should show the text in it's complete form.
