### ISSUE TITLE
Review Chunk Done UI

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#759]
Notes
======
when toggling done a section let's  use a checkmark in a check box icon, that  should indicate that it can be toggled off  more clearly

Environment
======
Environment Key | Value
:----: | :----:
version | 3.0.0
build | 97
UDID | 694f7e286991a5ec
Android Release | 4.4.2
Android SDK | 19
Brand | samsung
Device | degaswifiue

**Comment by jshuma** [comment]
Just added a [pull request](https://github.com/unfoldingWord-dev/ts-android/pull/941) for this.

![screen shot 2015-10-27 at 12 50 15 pm](https://cloud.githubusercontent.com/assets/7755451/10770680/cef9d720-7ca9-11e5-8654-fe117df83ceb.png)
