### ISSUE TITLE
Fix Portrait view UI

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#761]
Notes
======
some scrunching  of headers and icons in portrait orientation  on the home screen

Environment
======
Environment Key | Value
:----: | :----:
version | 3.0.0
build | 97
UDID | 694f7e286991a5ec
Android Release | 4.4.2
Android SDK | 19
Brand | samsung
Device | degaswifiue

**Comment by sampeckham** [comment]
In portrait view all the screens that have a white card in the middle should be full width of the screen. I should have made this more clear. But if you look at the cards in landscape the width is actually the same as the height of the screen (in theory).

**Comment by sampeckham** [comment]
Quick snapshot here. I'll add these to InVision
![screen shot 2015-09-24 at 16 00 01](https://cloud.githubusercontent.com/assets/323212/10076828/611a138e-62d5-11e5-8e06-786262a4e19d.png)

**Comment by neutrinog** [comment]
just a note: we could place a FAB in the bottom right corner of the home screen.

**Comment by sampeckham** [comment]
@jshuma How's this one going? Need any UI input, just let me know.

**Comment by jshuma** [comment]
@sampeckham I needed to be at work last week, but I'm back on this now. I'm hoping to have changes in soon.

**Comment by jshuma** [comment]
Just added a [pull request](https://github.com/unfoldingWord-dev/ts-android/pull/1068) for some more refinements on this for small screens.
