### ISSUE TITLE
Add subtitles to New Project flow

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#763]
Notes
======
we should add subtitles to each of the new project screens, perhaps Choose Target Language, Choose Project, Choose Source Language.

Environment
======
Environment Key | Value
:----: | :----:
version | 3.0.0
build | 97
UDID | dd19773da22f5f
Android Release | 5.0
Android SDK | 21
Brand | Verizon
Device | kltevzw
Log history
======
```java
9/22/15 8:01 PM  E/com.door43.translationstudio.projects.ProjectManager: reloadProject: the source languages could not be loaded for the project obs
     
```

**Comment by sampeckham** [comment]
Also, see the design regarding the deeper title/bar. The Android design pattern is the Card sits over the green bar and thats where the title goes.

**Comment by neutrinog** [comment]
yeah but that requires more work! :P

**Comment by jshuma** [comment]
Added a [pull request](https://github.com/unfoldingWord-dev/ts-android/pull/936) for subtitles.

Some items of note for this:
* For now, this is adjacent to the list -- not above the green bar.
* I was missing some strings, so I went with what I had. They're slightly different from the [spec](https://invis.io/823Z7UBRQ) but hopefully not too far off.
* Search and update are not yet hooked up, in line with TODOs that were already in the code.
* If I'm understanding the writeup correctly, source language selection already had this done.

![screen shot 2015-10-26 at 4 15 29 pm](https://cloud.githubusercontent.com/assets/7755451/10745326/f35654ba-7bfd-11e5-807d-55c76aa5c2cb.png)
![screen shot 2015-10-26 at 4 15 38 pm](https://cloud.githubusercontent.com/assets/7755451/10745330/f737d612-7bfd-11e5-89bc-d74bb8154f03.png)
![screen shot 2015-10-26 at 4 15 44 pm](https://cloud.githubusercontent.com/assets/7755451/10745331/fb084894-7bfd-11e5-8021-585449750999.png)
![screen shot 2015-10-26 at 4 16 00 pm](https://cloud.githubusercontent.com/assets/7755451/10745332/fe0353cc-7bfd-11e5-81f1-df638147acee.png)
