### ISSUE TITLE
Tweak Overflow Menu

### ISSUE THREAD

**Issue by sampeckham** [unfoldingWord-dev/ts-android#773]
Couple of tweaks here.

The menu should show the full list without scrolling.
The menu card should be white (currently background light grey)
The Menu should position over the overflow icon (see image)
I think My Translations should be Home (this is a stronger and more familiar concept)
![screen shot 2015-09-24 at 16 29 48](https://cloud.githubusercontent.com/assets/323212/10077814/e5278040-62d9-11e5-9a06-0f20543e49ef.png)

**Comment by neutrinog** [comment]
do you want to remove the icons as well?

**Comment by sampeckham** [comment]
No I like the icons actually. Nice touch.

**Comment by neutrinog** [comment]
@thomas3217 see if you can figure this one out. We'll need to make this change in `newui.translate.TargetTranslationActivity` and `newui.home.HomeActivity`.

**Comment by thomas3217** [comment]
where are you storing the AppTheme? I am thinking that would be the best place to adjust the style of the menu.

**Comment by neutrinog** [comment]
the app styles are in `src/main/res/values/styles.xml`

**Comment by thomas3217** [comment]
there are two styles.xml one says v21 the other does not have a version which one should I Use?

**Comment by thomas3217** [comment]
NVM I see v21 is empty. must be a future state thing.

**Comment by PhotoNomad0** [comment]
@sampeckham @neutrinog - this might get complicated since the default styling of popup menus is different for the various API levels of android.  On API 16 - towards the lower end of what we support, there is not a border or drop down shading on the popup menus.  In that case the gray background helps the popups stand out against the white background of our app.  I will dig in to see if we can even do that back to API 15.

**Comment by neutrinog** [comment]
@PhotoNomad0 for now it will probably be ok to fix this for current devices and then we can add backwards compatibility later.

**Comment by PhotoNomad0** [comment]
@neutrinog - I am able to implement this in API 21 and greater.  Am adding this in styles.xml under values-21.  Still investigating how to do this in API 19 and 16.

**Comment by PhotoNomad0** [comment]
Summary:
Was able to get popup menu to overlap the overflow icon in API 21and greater.
Was able to get white background to popup menu working for API 15 and greater.
Changed "My Translations" to "Home"
