### ISSUE TITLE
Align text to paper lines

### ISSUE THREAD

**Issue by sampeckham** [unfoldingWord-dev/ts-android#778]
This maybe quite tricky: can we align the translation text typed to match the lines exactly?

If not the lines should be much fainter as they clash with reading right now. Also, the title on the translation might need a think (on my part).
![screen shot 2015-09-24 at 17 31 10](https://cloud.githubusercontent.com/assets/323212/10079571/b70f7c04-62e2-11e5-9126-f88ae9b465cb.png)

**Comment by neutrinog** [comment]
aligning would be quite tricky. I'll make them fainter for now.

**Comment by sampeckham** [comment]
I'm reopening this as I think it adds important polish to the editing experience. Currently the lines start close to correct but the alignment drifts as each new line is created, which looks like a bug. (I know it's just a background for now).

I had a little look around and doesn't seem too hard to do. It's used on Basecamp Text Documents and other apps. Here's a quick code example: http://stackoverflow.com/questions/8667506/how-to-use-ruled-horizontal-lines-to-align-text-in-edittext-in-android

Given the top title (Book/Chapter/Verses) is a different font size I'm happy for that to not sit on the line, but just have a larger margin around it. 
![screen shot 2015-10-29 at 12 36 45](https://cloud.githubusercontent.com/assets/323212/10818476/c3fe23bc-7e39-11e5-8843-8512d015f5dc.png)

@jag3773 Any thoughts?

**Comment by neutrinog** [comment]
@PhotoNomad0 we'll need to create a new edittext class like is described in that stackoverflow question. Then just update the edittext for the target cards in all the translation modes (read, chunk review).

**Comment by PhotoNomad0** [comment]
Merged
