### ISSUE TITLE
Add new menu option to just download available updates

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#784]
We have a download all button already. This will be in addition to the download all.
The download updates method needs some work as well. It is not correctly merging the downloads into the app index.

**Comment by neutrinog** [comment]
stubbed this out. Just need to finish the download task.

**Comment by sampeckham** [comment]
@neutrinog Is this the "Update Library" menu item or something else? Just conscious we need to be very careful and clear with our language it tripped people up a lot in testing. "upload, download, update backup, import, save" and "project, translation, source, library".

**Comment by neutrinog** [comment]
this is **in** the `Update Library`. In the top corner there is a menu option to download all the projects. This will fit into that menu.
