### ISSUE TITLE
Publish: Review: Cards Should be Clickable

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-android#804]
In particular, the License Agreement, Translation Guidelines and Statement of Faith should be view able on this 3rd screen.  Potentially, we could add a "Review" button on each of those three lines that would pop up a modal window with the content of the item?  What do you think @sampeckham ?

**Comment by neutrinog** [comment]
@thomas3217 for now you can just open a dialog for each of the related documents when you click on the list item.
Look in the TermsOfUseActivity for an example of displaying the documents in a dialog.

**Comment by sampeckham** [comment]
Yep, from Review screen of Publish flow, I want to click on License, Guidelines or SoF and see the full text I am agreeing to.

**Comment by neutrinog** [comment]
@thomas3217 I made some adjustments to how the legal documents are displayed elsewhere in the app (so we have just one method).

```
Intent intent = new Intent(MyCurrentActivity.this, LegalDocumentActivity.class);
intent.putExtra(LegalDocumentActivity.ARG_RESOURCE, theCorrectResourceId);
startActivity(intent);
```

That's all you need. This will be available in a few minutes after I push this up.

**Comment by jshuma** [comment]
Just added a [pull request](https://github.com/unfoldingWord-dev/ts-android/pull/949) for this. Here's what it looks like:

![screen shot 2015-10-27 at 9 14 05 pm](https://cloud.githubusercontent.com/assets/7755451/10779593/4a288702-7cf0-11e5-9713-c8b5f6221293.png)

Any feedback is welcome.

**Comment by sampeckham** [comment]
Here's the prototype for this, see: https://projects.invisionapp.com/d/main#/console/4494516/97651971/preview

**Comment by neutrinog** [comment]
@jshuma could you update this? See above. Also could you make the entire row clickable instead of just the button?
