### ISSUE TITLE
Home Screen - Language title not aligned to column

### ISSUE THREAD

**Issue by sampeckham** [unfoldingWord-dev/ts-android#859]
Language title is shifted right. It should align (left justified) to the language column.

![screenshot_2015-10-07-12-55-31](https://cloud.githubusercontent.com/assets/323212/10336717/bec9b3aa-6cf2-11e5-9e00-158eab955ef7.png)

**Comment by neutrinog** [comment]
@a-gundy this should work in portrait/landscape mode for tablets and phones.
