### ISSUE TITLE
cursor jumps out of the text field while swipin...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#872]
Notes
======
cursor jumps out of the text field while swiping on the keyboard in chunk mode

Environment
======
Environment Key | Value
:----: | :----:
version | 3.0.0
build | 104
UDID | bd49ee6d9a9447ed
Android Release | 5.1
Android SDK | 22
Brand | google
Device | flo

**Comment by neutrinog** [comment]
In general I don't think swiping can be relied upon for translating since Android will not have the swipe dictionaries for most languages. So this is not a huge priority.

**Comment by neutrinog** [comment]
This is due to re-rendering when large chunks of text are inserted into the view so that any usx is displayed correctly. It we can remember and place the cursor back this should be fixed.

**Comment by neutrinog** [comment]
@a-gundy can you disable swipe text on keyboards for now?

**Comment by neutrinog** [comment]
this will be resolved once the editor is finished. #1288
