### ISSUE TITLE
After reviewing and approving all the frames on...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#879]
Notes
======
After reviewing and approving all the frames on door43, it is not obvious enough that you need "request to publish"

Environment
======
Environment Key | Value
:----: | :----:
version | 3.0.0
build | 104
UDID | fb2be1e70c7e5393
Android Release | 5.0.1
Android SDK | 21
Brand | Lenovo
Device | A10-70F

**Comment by neutrinog** [comment]
@jag3773 thoughts on this? I'm not sure if they mean the publish process in the app or the actual "request to publish" on door43.

**Comment by jag3773** [comment]
There is a now a link on the page that directs them to the correct place.
