### ISSUE TITLE
Demo Mode

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/ts-android#880]
Several workshop attendees asked of a Demo Mode could be created on the app for partnership development purposes that draws from the demo repository to help demonstrate what we are doing with tS & MAST, etc.

**Comment by benjore** [comment]
They were thinking that we would keep en-x-demo1 and en-x-demo2...

**Comment by neutrinog** [comment]
@jag3773 do you have any thoughts/direction on this?

**Comment by jag3773** [comment]
Superseded by #1259
