### ISSUE TITLE
Need to add front and back matter to OBS for tS

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-android#885]
Currently there is no way to translate the front or back matter in tS, we need to fix this.  Options are to either have tS read the exiting endpoints for those (e.g. https://api.unfoldingword.org/obs/txt/1/en/obs-en-front-matter.json), or include the front and back matter in the obs-en.json file (we could make them sisters to the "chapters" list).  I'm leaning toward the second option, what do you think @neutrinog ?

**Comment by jag3773** [comment]
We could tackle this in a v3 endpoint from tD.

**Comment by neutrinog** [comment]
the second option would be easiest in my opinion.

**Comment by neutrinog** [comment]
A proposal that reflects the suggestions above is viewable at https://github.com/unfoldingWord-dev/ts-requirements/wiki/APIv3-Draft#source

**Comment by neutrinog** [comment]
@cdwhitfield73 see above.

**Comment by neutrinog** [comment]
the new api spec is written to support front and back matter.https://github.com/unfoldingWord-dev/ts-requirements/wiki/APIv3-Draft
