### ISSUE TITLE
Add Contributors

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-android#887]
We need to add an "Add Contributors" option to each project.  This should be available in the publishing interface (on the profile page) and also on the information dialog pop-up for each project where "Translators" are currently listed.

The form needs to have the following fields:

* [x] Your Name or Pseudonym
* [x] This person has agreed to the License Agreement, Statement of Faith, and Translation Guidelines.

The last field should be a check box and each of the documents referred to should be links that open a pop up dialog with the text of the document.

> UPDATE: email and phone are not required.

**Comment by jag3773** [comment]
@sampeckham This one.

**Comment by sampeckham** [comment]
Add Contributor button below, and stack up contributor profile items like chapters. 
See:
https://projects.invisionapp.com/d/main#/console/4494516/97640091/preview
https://projects.invisionapp.com/d/main#/console/4494516/111675498/preview

**Comment by neutrinog** [comment]
@sampeckham what is the expected to happen when I click on the stacked cards? Also how can I see all the contributors?

**Comment by jag3773** [comment]
This should be required when using the Backup method.

**Comment by neutrinog** [comment]
@PhotoNomad0 the translators should be stored in the target translation manifest. https://github.com/unfoldingWord-dev/ts-requirements/wiki/ts.Translator.TargetTranslation#manifest-structure

There are already some method stubs for adding and retrieving translators in `core.TargetTranslation`. Those are `getTranslators()` and `addTranslator()` (we may want a remove method, but we can skip that for now until we have a ui for that). There is a `NativeSpeaker` class that has fields for the necessary translator information.

Also, when working with the manifest class, it's mostly a fancy wrapper around a `JSONObject` and you can treat it as such.

**Comment by neutrinog** [comment]
@sampeckham how do you envision a user editing/deleting one of the recorded contributors?

**Comment by neutrinog** [comment]
This is blocked by #1286

**Comment by neutrinog** [comment]
The migration methods have already been created for the new manifest. We just need to update the ui and how we store the translators to the manifest.

**Comment by neutrinog** [comment]
We still need to place this somewhere in the information pop-up but it's complete enough to no longer block other issues.
