### ISSUE TITLE
Translator/Checker Comment Box

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/ts-android#890]
Could we add a feature that allows users to comment on chunks within projects? I noticed one checking team (during the Orlando workshop) made notes/suggestions below the translation itself. I think it would be more helpful (and potentially less problematic) if there was a designated area where comments could be added. Perhaps it could even have a toggle to "resolve before done" with a way to indicate when it was resolved (preventing it from being "done" until that comment was "resolved"). This would also remove the necessity of writing comments on paper (which a lot of workshop teams did) and all the potential difficulties that might present (e.g. losing them).

**Comment by neutrinog** [comment]
@jag3773 can you review this?

**Comment by neutrinog** [comment]
We already have a field in the manifest called `comments`. We can simply add a comment button in the translation info dialog where users can open a comment input.

**Comment by PhotoNomad0** [comment]
@neutrinog - Are you talking about down scoping this to just be a comment field for the whole project?  Do we want to split this to multiple issues?  Maybe separate out a phase two with comments per chunk and todo checkboxes?

**Comment by neutrinog** [comment]
I just re-read it and realized it was with regards to the chunks. Oops. However, there is already a comments field that exists in the manifest. That would be for project wide, but also a separate issue.

**Comment by neutrinog** [comment]
Issue moved to [unfoldingWord-dev/ts-requirements #134](https://github.com/unfoldingWord-dev/ts-requirements/issues/134) via [**ZenHub.io**](https://www.zenhub.io/)
