### ISSUE TITLE
Step Back into Publishing

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-android#891]
User should be able to hit the "back" button to get back into publishing.

e.g. User is on first publish screen and they click on "Review" to go fix a chunk, after they fix that chunk the back button should take them straight back into the publish screen.

Related to #774.

**Comment by neutrinog** [comment]
There are lots of issues with that because what if they decide they don't want to go back into publishing but then continue on to another project or navigate to some other location in the app. If they hit back at that point then they will experience unexpected behavior.
