### ISSUE TITLE
tS Downloads from Door43

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-android#895]
A tS user should be able to download and edit an existing translation on *Door43*.

Related to #502 and unfoldingWord-dev/Door43#337.

**Comment by neutrinog** [comment]
we already have an issue for adding back in support for opening draft translations. #833. How is this issue different from #502 or #833?

**Comment by neutrinog** [comment]
@PhotoNomad0 We already support downloading drafts. So we just need to provide a way for users to actually access it.

Let's place an extra menu item in the translation activity if there is a draft available for that language. We could call it `View Draft`. When they click on the draft they should be able to see the draft content in a dialog. For the display let's go with something similar to the read mode except there will only be one card (not stacked). In this dialog users should be able to scroll through the draft content and have the option to import it as their translation. This will replace their current translation (warn them first) with the draft content and close the dialog.

**Comment by neutrinog** [comment]
@PhotoNomad0 there's a method to retreive downloaded draft translations at `core.Library.getDraftTranslations` This will give you every draft translation in project, so you'll need to search through to find the one that matches your target language.

**Comment by PhotoNomad0** [comment]
@neutrinog - it looks like there might be more than one draft translation per project.  How would you like to do the selection if there is more than one?

**Comment by PhotoNomad0** [comment]
@neutrinog - about only having one card: that might take forever to render if they are doing something like the Psalms.  Maybe we would like to have one card per chapter?

**Comment by neutrinog** [comment]
sorry that's what I meant. In the normal ui there are two cards stacked one for the source and one for the translation. For these there will be no translation and thus only "one" card rather than two stacked.

**Comment by PhotoNomad0** [comment]
@sampeckham - need an icon to be able to select edit of draft translation.  As shown it is temporarily using ic_library_books_black_24dp scaled up to 36dp.

![draft option](https://cloud.githubusercontent.com/assets/14238574/12293538/30aa1ca0-b9c2-11e5-9d1c-a1a7ffb64012.png)

**Comment by PhotoNomad0** [comment]
@sampeckham - need a UI design for draft preview screen.  Have a rough mock-up here.  The edit button on the lower right corner is to confirm loading draft as target translation.  Navigation in upper left corner or back button will cancel and go back to translations list.

![draft preview](https://cloud.githubusercontent.com/assets/14238574/12293607/b67e26d2-b9c2-11e5-8ab1-c59138b9e08b.png)
