### ISSUE TITLE
The translationWord for "manager" has some incorrect formatting.

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#902]
the last bit of the definition looks like this
```
===== Translation Suggestions =====
<ul>
  <li>This could also be translated as, "supervisor" or "organizer" or "person who manages" or "person who organizes."</li>
</ul>
<h2>Translation Suggestions</h2>
<ul>
    <li>This could also be translated as, "supervisor" or "organizer" or "person who manages" or "person who organizes."</li>
</ul>
```

however this should probably be trimmed down to
```
<h2>Translation Suggestions</h2>
<ul>
    <li>This could also be translated as, "supervisor" or "organizer" or "person who manages" or "person who organizes."</li>
</ul>
```

**Comment by neutrinog** [comment]
@jag3773 this is a source issue.

**Comment by lrsallee** [comment]
This is the source:

===== Translation Suggestions =====

  * This could also be translated as, "supervisor" or "organizer" or "person who manages" or "person who organizes." 

There does not appear to be anything wrong with the wiki code.

**Comment by lrsallee** [comment]
Added missing colon in heading. Maybe that will make a difference.
