### ISSUE TITLE
tS Privacy Notice

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-android#909]
On the profile page, we need to have a privacy notice that details the following:

"Your name or pseudonym will be published along with your translation in the unfoldingWord catalog.  We do not publish your email address or phone number."

**Comment by neutrinog** [comment]
@jshuma follow the same approach taken in the feedback dialog with regard to the WiFi.

**Comment by jshuma** [comment]
Created a [pull request](https://github.com/unfoldingWord-dev/ts-android/pull/951) to pop up a confirmation dialog when the user clicks the "Next Step" button in the profile page. Here's what it looks like:
![screen shot 2015-10-28 at 4 21 19 am](https://cloud.githubusercontent.com/assets/7755451/10787109/bb7f14da-7d2b-11e5-848a-0a407d145b2a.png)

**Comment by neutrinog** [comment]
Nice, 
@jag3773 is that what you were thinking? or do you want it displayed above the fields on the screen?

**Comment by dsm-git** [comment]
Looks good.

**Comment by jag3773** [comment]
This is not working in build 106.

**Comment by jag3773** [comment]
Nevermind, see #975 for the issue I was having.
