### ISSUE TITLE
tS skips over the notes that don’t contain bullets

### ISSUE THREAD

**Issue by DonRitchey** [unfoldingWord-dev/ts-android#911]
Following is a request for help (Help Desk Ticket 519)

We see that the current version of tS skips over the notes that don’t contain bullets. Is there a plan to include them any time soon? Or do we need to reformat all notes without bullets?

See:
https://door43.org/en/bible/notes/mat/10/01
https://door43.org/en/bible/notes/rev/05/06
https://door43.org/en/bible/notes/mat//06/01
In Him,
Larry Sallee
Training Specialist

**Comment by neutrinog** [comment]
I believe for now they must be bullets.

**Comment by neutrinog** [comment]
@DonRitchey @jag3773 These appear to be mostly resolved. The only issues I see is with https://door43.org/en/bible/notes/mat/06/01. The note `Jesus is talking to a group...` is not properly prefixed with bold text so the note does not appear in the app.

**Comment by neutrinog** [comment]
the app has been updated to still render translation notes that either are not properly formatted or do not have titles by design.
