### ISSUE TITLE
Clicking anywhere on the target translation card should also open the keyboard

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#916]
When in chunk mode. The keyboard needs to open up when clicking anywhere on the card. Right now the cursor goes into the edit text, but the keyboard does not open. I think if you tell the edittext field to be focused it will open the keyboard.

**Comment by jshuma** [comment]
Thanks for pointing this out. I'm not really sure why it wasn't popping up the keyboard in response to requestFocus(). The usual culprits, including having the EditText not be focusable or focusableInTouchMode, didn't seem to apply. I was able to fix this by explicitly requesting the keyboard in this case.
