### ISSUE TITLE
tapping on a target translation card (including the title) should not open the keyboard if the frame is marked as done.

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#926]
Right now if you mark a frame as done then go back to the chunk mode and tap on the target translation card or it's title the keyboard pops up. This should not happen because the translation is no longer editable for that frame.

As a side note... we'll eventually place a button on such cards so that users can quickly continue editing frame without having to first go back to the review mode, mark has not-finished, return to the chunk mode, and continue editing. We will display the same confirmation dialog (that currently does not exist) when they mark a frame as not-finished.

**Comment by jshuma** [comment]
Initiated [pull request](https://github.com/unfoldingWord-dev/ts-android/pull/930)
