### ISSUE TITLE
there should be no notes, words, etc. available for chapter titles and references.

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#927]
We'll just need to empty the resource view (stored in the holder) if the item in the list is a chapter title/reference.
This applies to the review mode.

**Comment by jshuma** [comment]
Sent a [pull request](https://github.com/unfoldingWord-dev/ts-android/pull/938) for this. I wasn't 100% sure about the desired behavior so I opted to hide the resource tab for chapter titles and references.

![screen shot 2015-10-26 at 5 48 00 pm](https://cloud.githubusercontent.com/assets/7755451/10747328/1189d6ba-7c11-11e5-9b1a-56df9b026b22.png)

If some other behavior is desired, let me know.

**Comment by neutrinog** [comment]
I think we'll leave the card there, and instead just leave it blank..
However, later I think we'll style the card slightly differently for these and any frame that doesn't have any resources. Perhaps a shade of gray with text like "there are no resources for this frame."

**Comment by neutrinog** [comment]
@sampeckham do you have any suggestions?

**Comment by jshuma** [comment]
If I'm understanding correctly, that's what I think I'm seeing for the default behavior:

![screen shot 2015-10-27 at 11 33 04 am](https://cloud.githubusercontent.com/assets/7755451/10768490/a8d9e554-7c9e-11e5-8e6b-b0e0a7bb33a2.png)

This behavior comes from there being a call to renderResourcesCard() in renderFrame() but not in renderChapterTitle() or renderChapterReference(). Is there something else I should be doing for this? I can also touch this up with some alternative text/styling if needed.

**Comment by neutrinog** [comment]
hm... I had seen some of the resources pop up in a chapter row before, but maybe android studio was just using some old caches when building the apk (it does that every once in awhile... frustrating.).

You can leave it alone for now. I'm restructuring a lot of the reviewadapter anyway to make it a little more organized. Adding in editing for the target card was a little too much for the current structure.
