### ISSUE TITLE
In review mode, editing text and clicking Done leaves the keyboard up

### ISSUE THREAD

**Issue by jshuma** [unfoldingWord-dev/ts-android#950]
Steps to reproduce:
1. Open review mode
2. Click the pencil icon
3. (optionally) edit some text
4. Click "Done"

Results:
The keyboard is still up, having no obvious effect.

Expected behavior:
After step 4, since the text is no longer editable, and the pencil icon that would normally dismiss the icon is now gone, the keyboard should go away.

Workaround:
Always click the pencil icon when done editing text, before clicking Done.

**Comment by neutrinog** [comment]
hm.. I thought I had fixed that.. Another thought I had was to hide the done button while they are in edit mode. That might be good so they are forced to review (and adjust if needed) the verse markers again before clicking done.

**Comment by neutrinog** [comment]
related to https://github.com/unfoldingWord-dev/ts-android/issues/1005
