### ISSUE TITLE
Inconsistent Padding in Chunks

### ISSUE THREAD

**Issue by sampeckham** [unfoldingWord-dev/ts-android#957]
Looking through chunks of source text there seems to be inconsistent padding at the bottom of each. I guess this maybe due to natural breaks in source text where paragraph or line break characters are included below a chunk?

Example here from Exodus.
![screen shot 2015-10-29 at 13 35 46](https://cloud.githubusercontent.com/assets/323212/10819805/05e255ac-7e42-11e5-9435-4c7bcfe9c72b.png)

**Comment by neutrinog** [comment]
@sampeckham this is because the cards in a row are forced to be the same height. So if the resources card or the target card happens to be longer the source card will have extra padding at the bottom.

**Comment by PhotoNomad0** [comment]
@neutrinog - I see the inconsistent spacing in review mode.  I don't see any extra whitespace at the end of the text that would explain the extra white space on some cards.  Will have to investigate further.  It does look like cards are being dynamically generated.  Could be due to card reuse - changing the text in an existing card?

**Comment by PhotoNomad0** [comment]
@neutrinog - think i figured out the inconsistent spacing issue.  It was not obvious on a small screen, but when I set up an emulator with a large screen, I noticed the notes to the right.  It looks like if there are a lot of notes shown, the height of the fragment adjusts to fit them all.  If I select a tab with a shorter list (like words or questions), the height will shrink down.  It looks like this is all design behavior.

**Comment by sampeckham** [comment]
I believe all 3 cards are set to the height of the longest card, so what we're seeing here is cards where the Resources card is longest, which varies by chunk, and therefore the space below source or translation will vary accordingly.

If that is the case, that's fine for now. I guess this will be best we can do, as either the card must extend or the gap between cards is extends. 

(I'm working on the Resources layout some more, so will look at this again after that.)

**Comment by neutrinog** [comment]
related to https://github.com/unfoldingWord-dev/ts-android/issues/978
