### ISSUE TITLE
simplifly complexity of measuring view dimensions in translator

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#964]
in the translation mode we are having to do some tricky value passing to get the dimensions of a view after it is rendered. We could try using this answer http://stackoverflow.com/questions/5820287/android-textview-has-height-and-width-of-0

**Comment by neutrinog** [comment]
the purpose here is to eliminate complexity.

**Comment by PhotoNomad0** [comment]
@neutrinog - where do we try to get the view dimensions?

**Comment by neutrinog** [comment]
I think an example is in usages of `newui.translate.ReviewModeFragment.onTranslationWordClick`. But this actually isn't a huge priority so let's backlog this.
