### ISSUE TITLE
save the open source translation tabs in the target translation manifest.

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-android#967]
This will allow us to maintain tabs and selection between exporting and importing.

**Comment by neutrinog** [comment]
This is already "almost" hooked up. It just need to be debugged.

**Comment by neutrinog** [comment]
Note: right now the target translation is just maintaining a list of any source translation that was ever opened, not just ones that are currently opened.  The list of currently open source translations is maintained in the `AppContext`. I'm not sure if we'll want to do that in the `TargetTranslation` or continue with the current line of thought.

@jag3773 do you want to record any source translation ever opened or just the currently opened ones in the target translation?

**Comment by jag3773** [comment]
We want to record any source translation ever opened.

**Comment by neutrinog** [comment]
perfect @PhotoNomad0 it's already set up to do that. Just need to make sure it's saving.

**Comment by PhotoNomad0** [comment]
@neutrinog - I found a class named manifest that handles saving of stuff.  Stepping through this it looks like it is saving when you add a source from any translation views.  It looks like the source list is being retained on restarting the app.  Is there anything more that I need to verify?

**Comment by neutrinog** [comment]
@PhotoNomad0 actually I just verified this was working while working on some updates for exporting. But to answer your question, you'd just need to open a target translation in the app, select some source translations then backup it up and email it to yourself so you can inspect the archive.

Sorry I probably could have been more clear in the issue description. But it's all done now! Thanks :)
