### ISSUE TITLE
Inconsistant Tab Behaviour

### ISSUE THREAD

**Issue by sampeckham** [unfoldingWord-dev/ts-android#977]
The tabs on cards behave differently in each place they appear.

Read Mode & Chunk Mode
The Source tabs are ok, but the switch is a little slow/jumpy as it loads. Accept that's in part due to the amount of content being loaded.

Checking Mode
If the Notes/Words card is open then the Source Tabs visually move the whole card up/down as they switch and are very jumpy, this definitely needs addressing.
The Notes/Words tabs themselves are perfect, very smooth with nice sliding visual of the underline bar.

The main concern here is the Source Tabs in Checking Mode as it's visually jarring and looses the context of where the user is reading. Ideally all tabs would behave as nicely as the Notes/Words tabs do.

**Comment by neutrinog** [comment]
@sampeckham I'm not seeing the card moving up/down. I do see the source tabs don't smoothly transition like the tabs on the resources card.
