### ISSUE TITLE
Styling of Notes/Words detail

### ISSUE THREAD

**Issue by sampeckham** [unfoldingWord-dev/ts-android#978]
The styling of Notes and Words detail screen needs some love! 
![screen shot 2015-11-04 at 12 08 50](https://cloud.githubusercontent.com/assets/323212/10937743/ef2bf8fe-82ec-11e5-898b-76c21f0f8c6e.png)

**Comment by neutrinog** [comment]
have any thoughts regarding this? I made the note title smaller so it's not quite as overwhelming.

**Comment by sampeckham** [comment]
Sorry delayed response! 

I'd like to go in this direction, to maintain context for the user and general style visually. Rather than another activity overlaid, it's inside the current card (this is actually the same concept we had in 2.3).

I am wondering what implications this has on the card lengths, how are they all set? Would scrolling inside a card work or be confusing etc.

@jag3773 any thoughts here?
![screen shot 2015-11-16 at 12 35 36](https://cloud.githubusercontent.com/assets/323212/11181982/0a333b3c-8c5f-11e5-8153-1d51c0954b75.png)

**Comment by sampeckham** [comment]
One idea (thinking aloud as it were). The Resources card could be just a single card for the whole open project. and simply change content based on the chunk that is 'in focus'. That could solve a number of problems with card length, card scrolling and long content in the resources card.

**Comment by jag3773** [comment]
Per #549 , we are going to need to fit tA in there somewhere, I think.  Maybe we could just rely on the links in the words/notes to bring up the tA modules, but I think we'll want some way for people to browse tA too.

**Comment by neutrinog** [comment]
scrolling within cards is not possible. Imagine a scroll-able list within a scroll-able list. In the android community this is regarded as a bad design pattern that should be avoided at all costs.

**Comment by sampeckham** [comment]
That's what I figured hence the fixed card suggestion. Would it work to expand the card dynamically? Or is that going to be weird or too hard? 

Regarding tA this small space is getting crowded. Do you have any sample of what tA looks like, how it's structured and how much content per chunk there is? Is it even per chunk based content?

**Comment by neutrinog** [comment]
@sampeckham could you elaborate on what you mean by "expand the card dynamically"?

**Comment by sampeckham** [comment]
@neutrinog By dynamic I mean that if all cards (source, translation, resources) have a set height while scrolling through chunks, would it work if I view a specific translation Word that has very long content - would all 3 cards be able to expand in length to contain the content?
![screen shot 2015-11-18 at 15 46 18](https://cloud.githubusercontent.com/assets/323212/11245618/8a314236-8e0b-11e5-9c16-4bbfa7ef3d23.png)

**Comment by neutrinog** [comment]
@sampeckham yes they would expand. My concern would be that they expand so much it could become cumbersome to scroll back to your original location after reading through the resource material.

**Comment by sampeckham** [comment]
I think I agree, but wanted to check the technical possibilities of that first.

Another thought is on a fixed Resource card, that changes content based on the 'current' or 'active' chunk. Something like this:

![screen shot 2015-11-18 at 17 00 44](https://cloud.githubusercontent.com/assets/323212/11247904/0816d4cc-8e16-11e5-9e97-40cced404d83.png)

**Comment by neutrinog** [comment]
that should work.

**Comment by sampeckham** [comment]
@jag3773 You thoughts would be good here. I think this fixed resource card could help in a number of ways. Looking through the new tA to see how best that should fit in.

@neutrinog If we went with the fixed Resource Card would that scroll internally (so there's a scroll bar and you always see the top and bottom of the card) or would the card itself scroll (on a different 'track' to the source and translation cards)?

![screen shot 2015-11-19 at 10 11 34](https://cloud.githubusercontent.com/assets/323212/11267900/efd77228-8ea5-11e5-8a1d-ae1634314166.png)

**Comment by jag3773** [comment]
@sampeckham tA looks like this https://test.unfoldingword.org/academy/

**Comment by jag3773** [comment]
@sampeckham I do like the idea.  Either the internal or external scroll would work.  I'm not sure which would be more intuitive without trying it though.

**Comment by neutrinog** [comment]
@sampeckham either would work. Like @jag3773 I'm not sure which would be more intuitive.

**Comment by neutrinog** [comment]
@sampeckham  @jag3773  bump

**Comment by neutrinog** [comment]
@cdwhitfield73 @vleong2332 @tjklemz welcome to the discussion.

**Comment by sampeckham** [comment]
Not sure where this issue is at, but i think the outstanding question was which approach to resource scrolling is better.

I think scrolling the whole resource card is better UX, as nested scrolling inside elements isn;t good practice and can get confusing. 

So, I would go for the left hand mockup above, where the whole resource card scrolls up is need be.

**Comment by neutrinog** [comment]
I agree
