### ISSUE TITLE
Import Modal Dialog

### ISSUE THREAD

**Issue by sampeckham** [unfoldingWord-dev/ts-android#979]
@jag3773 @neutrinog Can someone explain what I'm seeing here?

This needs some redesign, but to be honest I don't understand what this screen is showing (the information hierarchy is flat) and the actions are unclear. Thanks.

![screen shot 2015-11-04 at 12 17 42](https://cloud.githubusercontent.com/assets/323212/10937899/1370862a-82ee-11e5-953a-bb7626d8e077.png)

**Comment by neutrinog** [comment]
this is a list of files in the directory. If they end in `tstudio` they are parsed and the project details are displayed with the date formatted in a readable fashion.

The `automatic backups` is just a directory that is styled to indicate that's where automatic backups are located. Everything else is just listed by name.

**Comment by neutrinog** [comment]
This has been improved some but still needs some work.
