### ISSUE TITLE
Wrong Project Title on Info modal

### ISSUE THREAD

**Issue by sampeckham** [unfoldingWord-dev/ts-android#982]
The Info modal from the Home screen is showing the wrong title.

I have 3 projects (Exodus - Afaraf, OBS - Ghomara, Philemon - Afaraf), each info modal shows the title "Open Bible Stories - Arfaraf"

![screenshot_2015-11-04-12-48-14](https://cloud.githubusercontent.com/assets/323212/10938491/999a9d0e-82f2-11e5-99bf-9fee18d49fa9.png)

**Comment by sampeckham** [comment]
Update, regardless of the Source and the Target Language I get "Open Bible Stories - Afaraf" every time. Tested with a bunch of different book/language combinations.

Android 4.4.2

**Comment by neutrinog** [comment]
lol. Totally forgot I hard coded that way back before data was hooked up! :P
