### ISSUE TITLE
Improved UX for Chunk Done

### ISSUE THREAD

**Issue by sampeckham** [unfoldingWord-dev/ts-android#983]
@jag3773 @neutrinog 
Reviewing the UX around marking a chunk as done.

Current problem
The empty tick box doesn't communicate in the context and is used in apps primarily as a selection device. (Tick this item then do something with it). When ticked/done it's unclear you can un-tick this to go back and edit it. The green bar no longer looks like a button and the wording is still affirmative "Done".

It's also unique within the app and doesn't reinforce any other common tasks or button behaviour we're using - which is bad for overall UX and familiarity. 

Maybe the wording needs tweaking or the green done state needs reworking, but while looking at it i came up with these two other options, be interested in your feedback.

![screen shot 2015-11-04 at 17 04 11](https://cloud.githubusercontent.com/assets/323212/10945919/9113f8e0-8317-11e5-90ba-431952b3ee99.png)

**Comment by neutrinog** [comment]
I like the bottom two. Maybe we can add a light gray horizontal between the text and the bottom of the card to better separate the functionality. Then in addition to direct interactions with the switch we could allow users to tap anywhere along the bottom of the card to flip the switch.

**Comment by neutrinog** [comment]
@sampeckham If we are in agreement I'll go ahead and have this implemented.

**Comment by neutrinog** [comment]
@PhotoNomad0 please implement the bottom two designs.

**Comment by PhotoNomad0** [comment]
Merged
