### ISSUE TITLE
Paper lines do not appear on all devices

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord-dev/ts-android#999]
When target card is editable, do not see paper lines in emulator Google Nexus 7 - 4.1.1 - API 16

Yet it works on:
   phone LG G2 5.0.2 API 21
   emulator Motorola Xoom - 4.1.1 API 16

**Comment by neutrinog** [comment]
was this with the old paper lines or the new ones you are working on?

**Comment by PhotoNomad0** [comment]
@neutrinog - Yes it was the old paper lines.  I do not see the problem with the new line drawing.
